Repository yt-project/yt, pull requests merged in 2019-04, with the labels that each got.

#1848 Field display widget
  doc/source/analyzing/_images/fields_ipywidget.png
  doc/source/analyzing/fields.rst
  yt/data_objects/static_output.py
  yt/fields/field_type_container.py
Labels: enhancement

#1844 Adding a display_ytarray() function
  doc/source/reference/api/api.rst
  yt/__init__.py
  yt/data_objects/static_output.py
  yt/units/tests/test_ytarray.py
  yt/units/yt_array.py
  yt/utilities/exceptions.py
Labels: enhancement

#1807 Support Arepo data as a modified Gadget dataset
  doc/source/examining/loading_data.rst
  tests/tests.yaml
  yt/frontends/api.py
  yt/frontends/arepo/__init__.py
  yt/frontends/arepo/api.py
  yt/frontends/arepo/data_structures.py
  yt/frontends/arepo/fields.py
  yt/frontends/arepo/io.py
  yt/frontends/arepo/tests/__init__.py
  yt/frontends/arepo/tests/test_outputs.py
  yt/frontends/gadget/io.py
  yt/frontends/gadget/tests/test_outputs.py
Labels: code frontends, new feature

#2105 Improve curvilinear geometries support for vector field conversion and plot modifications
  yt/data_objects/construction_data_containers.py
  yt/data_objects/tests/test_covering_grid.py
  yt/fields/field_info_container.py
  yt/fields/fluid_fields.py
  yt/fields/fluid_vector_fields.py
  yt/fields/vector_operations.py
  yt/geometry/coordinates/cylindrical_coordinates.py
  yt/geometry/geometry_handler.py
  yt/geometry/selection_routines.pyx
  yt/visualization/plot_modifications.py
  yt/visualization/tests/test_callbacks.py
Labels: coordinates: non-cartesian, enhancement, new feature

#2186 Facilitate SPH visualization of non-SPH particles
  doc/source/examining/loading_data.rst
  yt/frontends/stream/data_structures.py
  yt/frontends/stream/tests/test_stream_particles.py
  yt/frontends/stream/tests/test_update_data.py
  yt/utilities/lib/bounded_priority_queue.pxd
  yt/utilities/lib/bounded_priority_queue.pyx
  yt/utilities/lib/particle_kdtree_tools.pyx
Labels: viz: 2D
