Repository yt-project/yt, pull requests merged in 2019-09, with the labels that each got.

#2328 Solve the cython numpy array resizing issue
  yt/utilities/lib/bounded_priority_queue.pxd
  yt/utilities/lib/bounded_priority_queue.pyx
  yt/utilities/lib/tests/test_nn.py
Labels: bug

#2329 Backporting unyt PR 102 for clip
  yt/units/tests/test_ytarray.py
  yt/units/yt_array.py
Labels: bug, units

#2315 [FEATURE] Add "minimal sphere" implementation
  doc/source/analyzing/objects.rst
  tests/test_requirements.txt
  yt/data_objects/data_containers.py
  yt/data_objects/selection_data_containers.py
  yt/data_objects/tests/test_spheres.py
  yt/funcs.py
  yt/utilities/on_demand_imports.py
Labels: new feature
