Repository yt-project/yt, pull requests merged in 2019-03, with the labels that each got.

#2193 fix tipsy IO via ds.all_data()
  yt/frontends/tipsy/io.py
Labels: demeshening

#2191 add missing argument to RockstarBinaryFile initializer
  yt/frontends/rockstar/data_structures.py
Labels: triage

#2170 [bugfix] Set max value in contour finder to be max value in clump finder.
  yt/data_objects/level_sets/clump_handling.py
Labels: bug

#2155 [bugfix] fix particle index initialization in gadget_fof frontend
  yt/frontends/ahf/io.py
  yt/frontends/gadget_fof/data_structures.py
  yt/frontends/gadget_fof/io.py
  yt/frontends/halo_catalog/data_structures.py
  yt/frontends/halo_catalog/io.py
  yt/frontends/rockstar/io.py
Labels: bug, code frontends

#2043 Reverse angular momentum orientation
  yt/fields/angular_momentum.py
  yt/fields/particle_fields.py
  yt/fields/tests/test_angular_momentum.py
Labels: backwards incompatible

#2204 [BUGFIX] Fix missing argument in stack ufunc
  yt/units/tests/test_ytarray.py
  yt/units/yt_array.py
Labels: bug, yt core

#2215 Code to find object bounding boxes for SPH projections.
  yt/data_objects/data_containers.py
  yt/data_objects/selection_data_containers.py
  yt/data_objects/tests/test_bbox.py
  yt/geometry/coordinates/cartesian_coordinates.py
Labels: demeshening

#2194 Deprecate smoothed fields
  doc/source/analyzing/fields.rst
  doc/source/cookbook/calculating_information.rst
  doc/source/cookbook/smoothed_field.py
  yt/data_objects/static_output.py
  yt/fields/particle_fields.py
  yt/fields/tests/test_fields.py
  yt/frontends/gadget/fields.py
  yt/frontends/gizmo/fields.py
  yt/frontends/owls/fields.py
  yt/frontends/sph/data_structures.py
Labels: backwards incompatible, demeshening
