Repository yt-project/yt, pull requests merged in 2020-11, with the labels that each got.

#2961 Bump versions for bugfix release
  doc/source/conf.py
  doc/source/reference/changelog.rst
  setup.py
  yt/__init__.py
Labels: infrastructure, yt core

#2960 [bugfix] RAMSES: do not fail when impossible to convert from conformal → physical time.
  yt/frontends/ramses/data_structures.py
Labels: bug, code frontends

#2954 switch csv writer file IO mode for python 3
  yt/utilities/parameter_file_storage.py
Labels: bug

#2966 Remove the redundant display_ytarray
  yt/units/yt_array.py
Labels: api-consistency, bug, refactor

#2945 cut region AMRGrid selector fix
  tests/tests.yaml
  yt/geometry/selection_routines.pyx
Labels: bug, yt core

#2944 futurefix: fix a deprecation warning from mpl 3.3
  yt/visualization/base_plot_types.py
Labels: api-consistency, bug

#2963 Migrate from Travis to GitHub Actions
  .github/workflows/build-test.yaml
  .travis.yml
  appveyor.yml
  tests/ci_install.sh
  tests/travis_before_install.sh
  tests/travis_install.sh
Labels: enhancement, infrastructure, tests: running tests

#2968 Allow .plot() to run outside of the notebook
  yt/data_objects/construction_data_containers.py
  yt/data_objects/selection_objects/slices.py
Labels: enhancement

#2951 fix: autocomplete some missing entries in sample data registry file
  yt/sample_data_registry.json
Labels: bug, infrastructure

#2975 fix installation against python 3.9
  pyproject.toml
Labels: bug, infrastructure

#2836 [bugfix] fix particle selection for clump objects
  doc/source/cookbook/find_clumps.py
  yt/data_objects/derived_quantities.py
  yt/data_objects/selection_objects/cut_region.py
  yt/data_objects/selection_objects/data_selection_objects.py
Labels: bug

#2977 fix: bump bugbear to latest version and fix newly detected bugs
  tests/lint_requirements.txt
  yt/utilities/parallel_tools/parallel_analysis_interface.py
Labels: bug, code style, infrastructure

#2971 Minor updates to the dev docs
  doc/source/developing/releasing.rst
Labels: docs, infrastructure

#2962 ensure cosmology_answers.yml will be included in distribution
  MANIFEST.in
Labels: bug, tests: running tests

#2958 Enable ghost zones > 1 for octrees
  yt/frontends/ramses/data_structures.py
  yt/frontends/ramses/tests/test_outputs.py
  yt/geometry/oct_container.pyx
  yt/geometry/oct_geometry_handler.py
  yt/geometry/oct_visitors.pxd
  yt/geometry/oct_visitors.pyx
Labels: code frontends, enhancement, index: octree

#2984 add whitespace between url and '.' to make link clickable.
  tests/report_failed_answers.py
Labels: infrastructure
