Repository yt-project/yt, pull requests merged in 2020-09, with the labels that each got.

#2884 Add an option to strictly enforce requires_file
  yt/config.py
  yt/testing.py
  yt/utilities/answer_testing/framework.py
Labels: enhancement, tests: running tests

#2886 Fix uninitialized values in bbox selection
  yt/geometry/selection_routines.pxd
  yt/geometry/selection_routines.pyx
Labels: bug, index: unstructured mesh

#2882 hotfix: only trigger style checks on PR (avoid duplicated runs)
  .github/workflows/style-checks.yaml
Labels: bug, code style, infrastructure

#2885 skip tests whose requirements are not met
  tests/nose_runner.py
  tests/test_requirements.txt
  tests/tests.yaml
  yt/frontends/enzo/answer_testing_support.py
  yt/testing.py
  yt/utilities/answer_testing/framework.py
  yt/utilities/answer_testing/utils.py
Labels: enhancement, infrastructure, tests: running tests

#2880 hotfix error message format
  yt/data_objects/time_series.py
  yt/loaders.py
  yt/utilities/exceptions.py
Labels: bug

#2888 Squeeze domain center array in data_containers
  yt/data_objects/data_containers.py
  yt/data_objects/tests/test_center_squeeze.py
Labels: bug

#2894 [load_sample] Don't try to untar hdf5 files
  yt/loaders.py
Labels: bug

#2895 add a missing NotImplementedError
  yt/fields/field_info_container.py
  yt/utilities/lib/misc_utilities.pyx
Labels: bug

#2873 Remove unreachable code
  yt/data_objects/tests/test_streamlines.py
  yt/data_objects/unstructured_mesh.py
  yt/frontends/art/data_structures.py
  yt/frontends/sdf/tests/test_outputs.py
  yt/geometry/grid_geometry_handler.py
  yt/loaders.py
  yt/utilities/parallel_tools/parallel_analysis_interface.py
  yt/visualization/eps_writer.py
  yt/visualization/volume_rendering/old_camera.py
Labels: dead code

#2867 remove dead test file
  yt/geometry/tests/test_neighbor_search.py
Labels: dead code

#2871 Add a filter to ytLogger to avoid duplicated successive entries
  yt/utilities/logger.py
Labels: bug, proposal

#2829 Rearrange index component objects
  yt/data_objects/api.py
  yt/data_objects/index_subobjects/__init__.py
  yt/data_objects/index_subobjects/grid_patch.py
  yt/data_objects/index_subobjects/octree_subset.py
  yt/data_objects/index_subobjects/particle_container.py
  yt/data_objects/index_subobjects/unstructured_mesh.py
  yt/frontends/_skeleton/data_structures.py
  yt/frontends/amrvac/data_structures.py
  yt/frontends/art/data_structures.py
  yt/frontends/artio/data_structures.py
  yt/frontends/athena/data_structures.py
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/boxlib/data_structures.py
  yt/frontends/chombo/data_structures.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/enzo_p/data_structures.py
  yt/frontends/exodus_ii/data_structures.py
  yt/frontends/fits/data_structures.py
  yt/frontends/flash/data_structures.py
  yt/frontends/gamer/data_structures.py
  yt/frontends/gdf/data_structures.py
  yt/frontends/moab/data_structures.py
  yt/frontends/open_pmd/data_structures.py
  yt/frontends/ramses/data_structures.py
  yt/frontends/stream/data_structures.py
  yt/frontends/ytdata/data_structures.py
  yt/geometry/coordinates/cartesian_coordinates.py
  yt/geometry/particle_geometry_handler.py
Labels: refactor

#2900 Ensure that all test suites work on stable
  .travis.yml
  tests/nose_runner.py
  tests/test_requirements.txt
Labels: infrastructure, tests: running tests

#2898 [doctest] fix docstrings in yt.loaders
  yt/loaders.py
Labels: bug, docs, infrastructure

#2899 [doctest] fix errors in yt.funcs docstrings
  yt/funcs.py
Labels: bug, docs

#2610 Volume rendering for octrees
  appveyor.yml
  doc/source/cookbook/render_two_fields.py
  doc/source/cookbook/various_lens.py
  setup.py
  yt/data_objects/index_subobjects/octree_subset.py
  yt/frontends/ramses/data_structures.py
  yt/frontends/stream/data_structures.py
  yt/geometry/oct_container.pxd
  yt/geometry/oct_container.pyx
  yt/utilities/answer_testing/utils.py
  yt/utilities/lib/_octree_raytracing.hpp
  yt/utilities/lib/_octree_raytracing.pxd
  yt/utilities/lib/_octree_raytracing.pyx
  yt/utilities/lib/ewah_bool_wrap.pyx
  yt/utilities/lib/field_interpolation_tables.pxd
  yt/utilities/lib/fixed_interpolator.c
  yt/utilities/lib/fixed_interpolator.cpp
  yt/utilities/lib/fixed_interpolator.hpp
  yt/utilities/lib/fixed_interpolator.pxd
  yt/utilities/lib/image_samplers.pxd
  yt/utilities/lib/image_samplers.pyx
  yt/utilities/lib/marching_cubes.pyx
  yt/utilities/lib/octree_raytracing.py
  yt/utilities/lib/partitioned_grid.pyx
  yt/visualization/volume_rendering/api.py
  yt/visualization/volume_rendering/interactive_loop.py
  yt/visualization/volume_rendering/off_axis_projection.py
  yt/visualization/volume_rendering/old_camera.py
  yt/visualization/volume_rendering/render_source.py
  yt/visualization/volume_rendering/scene.py
  yt/visualization/volume_rendering/shader_objects.py
  yt/visualization/volume_rendering/tests/test_composite.py
  yt/visualization/volume_rendering/tests/test_lenses.py
  yt/visualization/volume_rendering/tests/test_points.py
  yt/visualization/volume_rendering/tests/test_scene.py
  yt/visualization/volume_rendering/tests/test_varia.py
  yt/visualization/volume_rendering/tests/test_vr_orientation.py
  yt/visualization/volume_rendering/tests/test_zbuff.py
  yt/visualization/volume_rendering/utils.py
  yt/visualization/volume_rendering/volume_rendering.py
Labels: code frontends, new feature, viz: volume rendering, yt-4.0

#2828 Rearrange data objects
  yt/data_objects/api.py
  yt/data_objects/construction_data_containers.py
  yt/data_objects/data_containers.py
  yt/data_objects/index_subobjects/grid_patch.py
  yt/data_objects/index_subobjects/octree_subset.py
  yt/data_objects/index_subobjects/particle_container.py
  yt/data_objects/index_subobjects/unstructured_mesh.py
  yt/data_objects/selection_data_containers.py
  yt/data_objects/selection_objects/__init__.py
  yt/data_objects/selection_objects/boolean_operations.py
  yt/data_objects/selection_objects/cut_region.py
  yt/data_objects/selection_objects/data_selection_objects.py
  yt/data_objects/selection_objects/disk.py
  yt/data_objects/selection_objects/object_collection.py
  yt/data_objects/selection_objects/point.py
  yt/data_objects/selection_objects/ray.py
  yt/data_objects/selection_objects/region.py
  yt/data_objects/selection_objects/slices.py
  yt/data_objects/selection_objects/spheroids.py
  yt/data_objects/tests/test_disks.py
  yt/frontends/adaptahop/data_structures.py
  yt/frontends/gadget_fof/data_structures.py
  yt/frontends/halo_catalog/data_structures.py
  yt/frontends/ytdata/data_structures.py
  yt/geometry/coordinates/cartesian_coordinates.py
  yt/utilities/answer_testing/utils.py
  yt/utilities/exceptions.py
  yt/utilities/particle_generator.py
  yt/visualization/plot_modifications.py
  yt/visualization/plot_window.py
  yt/visualization/profile_plotter.py
  yt/visualization/volume_rendering/utils.py
Labels: enhancement, refactor

#2902 Add reqs that needs to be installed before test_requirements.txt
  .travis.yml
  tests/test_prerequirements.txt
  tests/tests.yaml
  yt/visualization/tests/test_particle_plot.py
Labels: enhancement, infrastructure, tests: running tests

#2904 hotfix: make Dataset an abstract class again
  yt/data_objects/static_output.py
Labels: bug

#2691 deprecate simulation answer testing framework
  yt/utilities/answer_testing/framework.py
Labels: infrastructure, tests: running tests

#2843 Bugfix 2838
  yt/geometry/grid_geometry_handler.py
Labels: bug

#2798 feature: support for gradient computation of several fields at a time, and support simple fnames as inputs
  yt/data_objects/static_output.py
  yt/fields/tests/test_fields.py
Labels: api-consistency, new feature, yt-4.0

#2709 RAMSES code refactoring
  yt/frontends/ramses/data_structures.py
  yt/frontends/ramses/field_handlers.py
  yt/frontends/ramses/particle_handlers.py
Labels: code frontends, refactor

#2722 fix: add support to init from pathlike objects for time series
  yt/data_objects/tests/test_time_series.py
  yt/data_objects/time_series.py
Labels: api-consistency, enhancement, yt-4.0

#2807 fix: refactor boxlib dataformat validators (code deduplication), fix bugs revealed on the way there
  tests/tests.yaml
  yt/frontends/boxlib/data_structures.py
  yt/frontends/boxlib/tests/test_outputs.py
Labels: api-consistency, bug, code frontends, enhancement, refactor

#2906 hotfix/flaking_ramses
  yt/frontends/ramses/field_handlers.py
Labels: bug, code frontends, code style

#2901 cleanup: remove deprecated particle_position_relative field
  yt/fields/particle_fields.py
Labels: backwards incompatible, enhancement

#2907 Reissue #2800: backport #2754 to stable
  yt/utilities/png_writer.py
Labels: bug

#2910 ci: only test against latest python version on windows to reduce CI bottleneck
  appveyor.yml
Labels: enhancement, infrastructure, proposal

#2909 Fix indexing issues in sph pixelization
  tests/tests.yaml
  yt/utilities/answer_testing/framework.py
  yt/utilities/lib/pixelization_routines.pyx
Labels: bug

#2915 Fix: matplotlib deprecation warnings
  tests/tests.yaml
  yt/visualization/base_plot_types.py
  yt/visualization/image_writer.py
  yt/visualization/tests/test_offaxisprojection.py
Labels: api-consistency, bug

#2916 fix a FutureWarning from numpy
  yt/frontends/gadget/testing.py
  yt/geometry/grid_container.pyx
Labels: api-consistency, bug

#2920 bugfix: fix a brittle array conversion
  yt/data_objects/static_output.py
Labels: bug

#2908 [PROPOSITION] Run windows tests on travis
  .travis.yml
  appveyor.yml
  tests/test_requirements.txt
  tests/travis_before_install.sh
  tests/travis_install.sh
  yt/visualization/tests/test_fits_image.py
Labels: infrastructure, proposal

#2918 Simplify isort conf
  .pre-commit-config.yaml
  pyproject.toml
  setup.cfg
  tests/lint_requirements.txt
  yt/utilities/lib/basic_octree.pyx
  yt/utilities/lib/grid_traversal.pyx
Labels: code style, enhancement, infrastructure

#2922 bugfix/2892
  setup.py
Labels: bug

#2683 Parallelize pixelize_sph_kernel_projection. Fixes #2682
  yt/utilities/lib/pixelization_routines.pyx
Labels: enhancement, parallelism, yt core

#2593 add support for arbitrary polyhedra in the ExodusII format
  yt/frontends/exodus_ii/data_structures.py
  yt/geometry/coordinates/cartesian_coordinates.py
Labels: code frontends, enhancement

#2927 [bugfix] Construct log message using args.
  yt/utilities/logger.py
Labels: bug
