Repository yt-project/yt, pull requests merged in 2020-04, with the labels that each got.

#2485 Set symlog to log if vmin > 0
  yt/visualization/plot_container.py
Labels: yt-3.6

#2418 Export data container and profile fields to AstroPy QTables and pandas DataFrames
  doc/source/analyzing/astropy_integrations.rst
  doc/source/analyzing/generating_processed_data.rst
  doc/source/conf.py
  yt/data_objects/data_containers.py
  yt/data_objects/profiles.py
  yt/data_objects/tests/test_data_containers.py
  yt/data_objects/tests/test_profiles.py
Labels: yt-3.6

#2466 extend support of some plot callbacks to polar geometries
  doc/source/visualizing/callbacks.rst
  yt/visualization/plot_modifications.py
Labels: coordinates: non-cartesian, enhancement, viz: 2D, yt-3.6

#2488 Fix some invalid escape sequences.
  yt/visualization/plot_container.py
Labels: yt-3.6

#2514 Update to matplotlib's current png interface
  yt/utilities/png_writer.py
Labels: yt-3.6

#2482 Extend region expression to 2d datasets
  yt/data_objects/region_expression.py
  yt/data_objects/tests/test_dataset_access.py
Labels: enhancement, yt-3.6

#2494 [doc] Add existing packages in the documentation
  doc/source/installing.rst
Labels: yt-3.6

#2517 hotfix: bug in cylindrical coordinates background color with log norm
  doc/source/developing/testing.rst
  tests/tests.yaml
  yt/geometry/coordinates/coordinate_handler.py
  yt/geometry/coordinates/cylindrical_coordinates.py
  yt/geometry/coordinates/geographic_coordinates.py
  yt/geometry/coordinates/spherical_coordinates.py
  yt/geometry/coordinates/tests/test_cylindrical_coordinates.py
  yt/testing.py
  yt/utilities/answer_testing/framework.py
Labels: bug, viz: 2D, yt-3.6

#2520 add donation badge and numfocus section to README
  README.md
Labels: yt-3.6

#2483 Extend Dataset.add_gradient_fields to curvilinear geometries
  yt/data_objects/static_output.py
  yt/fields/field_info_container.py
  yt/fields/fluid_fields.py
  yt/fields/tests/test_fields.py
Labels: coordinates: non-cartesian, enhancement, yt-3.6

#2521 update pressure units for artio frontend
  yt/frontends/artio/fields.py
Labels: yt-3.6

#2524 Set physical/plot bounds consistently across all callbacks. Fixes #2293
  yt/visualization/plot_modifications.py
Labels: yt-3.6

#2378 Address some cartopy issues. Fixes #2373.
  yt/data_objects/static_output.py
  yt/visualization/plot_window.py
  yt/visualization/tests/test_geo_projections.py
Labels: yt-3.6

#2529 refactor annotate_grids callback
  yt/visualization/plot_modifications.py
Labels: enhancement, viz: 2D

#2541 [AMRVAC] bugfix geometry parsing
  yt/frontends/amrvac/data_structures.py
Labels: bug, code frontends

#2531 Adding workflow for enforcing PR labels
  .github/mergeable.yml
Labels: infrastructure, proposal

#2544 add reversed version of turbo colormap
  yt/visualization/color_maps.py
Labels: bug

#2547 fix a bug in PlotContainer.set_minorticks
  yt/visualization/plot_container.py
Labels: bug

#2468 Pytest unittest
  conftest.py
  pytest.ini
  yt/__init__.py
  yt/testing.py
  yt/tests/test_testing.py
Labels: infrastructure, tests: running tests

#2510 Remove gperftools wrapper
  .gitignore
  setup.py
  yt/utilities/lib/perftools_wrap.pyx
Labels: bug

#2487 Change order of operations.
  yt/frontends/athena/fields.py
Labels: bug

#2502 Adding repr methods for particle unions
  yt/data_objects/particle_unions.py
  yt/data_objects/unions.py
Labels: enhancement

#2534 Allow for local plugin file (not system wide)
  doc/source/reference/configuration.rst
  yt/funcs.py
Labels: enhancement, proposal

#2551 Test enhancement for #2525
  yt/visualization/tests/test_callbacks.py
Labels: enhancement

#2549 add explicit support for jpeg exports
  yt/funcs.py
Labels: enhancement, proposal, viz: 2D

#2561 refactor Dataset.box (hotfix #2560)
  yt/data_objects/static_output.py
Labels: bug

#2566 [bugfix] Put pytest import inside function.
  yt/testing.py
Labels: bug, tests: running tests
