Repository yt-project/yt, pull requests merged in 2020-01, with the labels that each got.

#2411 Gadget io fewer calls to reading
  yt/frontends/gadget/io.py
Labels: demeshening, performance

#2419 bugfix for numpy 1.18
  yt/visualization/plot_container.py
Labels: bug

#2387 [AMRVAC] Add auto-discovery of dust fields and set some corresponding derived fields
  doc/source/examining/loading_data.rst
  yt/frontends/amrvac/fields.py
  yt/frontends/amrvac/tests/test_outputs.py
Labels: code frontends
