Repository yt-project/yt, pull requests merged in 2020-05, with the labels that each got.

#2562 add a list_annotations() method
  doc/source/visualizing/callbacks.rst
  yt/visualization/plot_window.py
Labels: new feature

#2570 Store unitful field values and don't compare weight fields
  tests/tests.yaml
  yt/utilities/answer_testing/framework.py
Labels: infrastructure

#2563 [bugfix] add units to profile weight field
  yt/data_objects/profiles.py
  yt/data_objects/tests/test_profiles.py
Labels: bug, yt core

#2572 Fix some typos in documentation
  doc/source/analyzing/analysis_modules/absorption_spectrum.rst
  doc/source/examining/loading_data.rst
  doc/source/reference/changelog.rst
Labels: docs

#2579 [EnzoSimulation] Ensure that my_initial_time is initialized. Fixes #2578
  yt/frontends/enzo/simulation_handling.py
Labels: bug, code frontends

#2568 Change the default answer test unit system to code
  tests/tests.yaml
  yt/frontends/boxlib/data_structures.py
  yt/utilities/answer_testing/framework.py
  yt/utilities/answer_testing/utils.py
Labels: infrastructure, tests: running tests

#2582 Execute setup only on a parent thread to prevent a failure with spawn
  setup.py
Labels: bug

#2580 Remove unused arg in string formatting
  yt/visualization/eps_writer.py
Labels: enhancement

#2585 Boolean comparisons. Fixes #2576
  setup.py
  tests/test_install_script.py
  yt/analysis_modules/halo_finding/rockstar/rockstar.py
  yt/analysis_modules/halo_mass_function/halo_mass_function.py
  yt/data_objects/analyzer_objects.py
  yt/data_objects/construction_data_containers.py
  yt/data_objects/data_containers.py
  yt/data_objects/static_output.py
  yt/data_objects/time_series.py
  yt/fields/derived_field.py
  yt/fields/field_functions.py
  yt/fields/vector_operations.py
  yt/frontends/boxlib/tests/test_outputs.py
  yt/frontends/gamer/data_structures.py
  yt/frontends/ytdata/data_structures.py
  yt/funcs.py
  yt/geometry/coordinates/spec_cube_coordinates.py
  yt/startup_tasks.py
  yt/testing.py
  yt/units/unit_object.py
  yt/units/yt_array.py
  yt/utilities/answer_testing/answer_tests.py
  yt/utilities/answer_testing/framework.py
  yt/utilities/command_line.py
  yt/utilities/grid_data_format/conversion/conversion_athena.py
  yt/utilities/grid_data_format/writer.py
  yt/utilities/math_utils.py
  yt/utilities/parallel_tools/parallel_analysis_interface.py
  yt/utilities/parameter_file_storage.py
  yt/visualization/line_plot.py
  yt/visualization/particle_plots.py
  yt/visualization/plot_window.py
  yt/visualization/profile_plotter.py
  yt/visualization/tests/test_profile_plots.py
  yt/visualization/volume_rendering/off_axis_projection.py
  yt/visualization/volume_rendering/old_camera.py
  yt/visualization/volume_rendering/render_source.py
  yt/visualization/volume_rendering/tests/test_varia.py
  yt/visualization/volume_rendering/transfer_functions.py
Labels: bug, code frontends

#2584 Coerce mx, my, mz to code-length
  yt/data_objects/static_output.py
Labels: bug, coordinates: non-cartesian, yt core

#2583 Hotfix literal comparisons (yt 4.0)
  yt/frontends/flash/data_structures.py
  yt/frontends/open_pmd/data_structures.py
  yt/frontends/ramses/data_structures.py
  yt/utilities/grid_data_format/conversion/conversion_athena.py
  yt/visualization/plot_container.py
  yt/visualization/profile_plotter.py
Labels: bug

#2586 Fix bug with raw fields when there is no ghost cells
  yt/frontends/boxlib/io.py
Labels: bug, code frontends

#2591 add clarification about uniqueness in _is_valid method
  yt/frontends/_skeleton/data_structures.py
Labels: docs

#2590 [yt-4.0] urllib bugfix
  yt/funcs.py
Labels: bug

#2405 allow loading from path objects (py3.6 or above)
  tests/tests.yaml
  yt/convenience.py
  yt/tests/test_load_from_path.py
Labels: enhancement

#2587 make set_zlim units aware (sanitize zmin and zmax)
  yt/visualization/plot_container.py
Labels: enhancement

#2588 [yt-4.0] setup typo
  setup.py
Labels: bug

#2607 [bugfix] Pass center kwarg on to reloaded projection dataset.
  yt/visualization/plot_window.py
Labels: bug
