Repository yt-project/yt, pull requests merged in 2020-06, with the labels that each got.

#2621 Update bitmask_version for #2575
  yt/geometry/particle_oct_container.pyx
Labels: bug, demeshening

#2594 Add mode argument to h5py.File
  doc/source/analyzing/analysis_modules/absorption_spectrum.rst
  doc/source/developing/external_analysis.rst
  yt/analysis_modules/cosmological_observation/light_cone/tests/test_light_cone.py
  yt/units/yt_array.py
  yt/utilities/answer_testing/answer_tests.py
Labels: enhancement

#2618 [yt-4.0] added domain_overrride to fix bbox
  yt/frontends/gadget/data_structures.py
  yt/frontends/sdf/data_structures.py
  yt/frontends/tipsy/data_structures.py
  yt/geometry/particle_geometry_handler.py
Labels: bug, demeshening

#2632 [bugfix] Don't clobber coeff if units not given in annotate_scale
  yt/visualization/plot_modifications.py
Labels: bug

#2643 Use 'a' mode for saving arrays to hdf. Fixes #2642
  yt/units/yt_array.py
Labels: bug

#2623 Add mode kwarg to h5py.File calls
  doc/source/analyzing/analysis_modules/absorption_spectrum.rst
  doc/source/analyzing/ionization_cube.py
  doc/source/cookbook/extract_fixed_resolution_data.py
  doc/source/developing/external_analysis.rst
  doc/source/visualizing/callbacks.rst
  yt/analysis_modules/absorption_spectrum/absorption_spectrum.py
  yt/analysis_modules/absorption_spectrum/absorption_spectrum_fit.py
  yt/analysis_modules/cosmological_observation/light_cone/light_cone.py
  yt/analysis_modules/cosmological_observation/light_cone/tests/test_light_cone.py
  yt/analysis_modules/halo_analysis/halo_callbacks.py
  yt/analysis_modules/halo_finding/halo_objects.py
  yt/analysis_modules/photon_simulator/photon_simulator.py
  yt/analysis_modules/photon_simulator/spectral_models.py
  yt/analysis_modules/star_analysis/sfr_spectrum.py
  yt/analysis_modules/two_point_functions/two_point_functions.py
  yt/data_objects/particle_trajectories.py
  yt/fields/xray_emission_fields.py
  yt/frontends/chombo/data_structures.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/enzo/io.py
  yt/frontends/enzo_p/data_structures.py
  yt/frontends/enzo_p/io.py
  yt/frontends/enzo_p/tests/test_outputs.py
  yt/frontends/gadget/io.py
  yt/frontends/gadget_fof/data_structures.py
  yt/frontends/gadget_fof/io.py
  yt/frontends/gdf/data_structures.py
  yt/frontends/gdf/io.py
  yt/frontends/halo_catalog/data_structures.py
  yt/frontends/halo_catalog/io.py
  yt/frontends/moab/data_structures.py
  yt/frontends/owls_subfind/data_structures.py
  yt/frontends/owls_subfind/io.py
  yt/frontends/ytdata/data_structures.py
  yt/frontends/ytdata/io.py
  yt/frontends/ytdata/utilities.py
  yt/geometry/geometry_handler.py
  yt/geometry/grid_geometry_handler.py
  yt/units/yt_array.py
  yt/utilities/amr_kdtree/amr_kdtree.py
  yt/utilities/answer_testing/answer_tests.py
  yt/utilities/file_handler.py
  yt/utilities/grid_data_format/writer.py
  yt/utilities/io_handler.py
  yt/visualization/fixed_resolution.py
  yt/visualization/volume_rendering/image_handling.py
Labels: enhancement

#2617 Abstract some particle tests
  yt/frontends/ahf/tests/test_outputs.py
  yt/frontends/arepo/tests/test_outputs.py
  yt/frontends/art/tests/test_outputs.py
  yt/frontends/eagle/tests/test_outputs.py
  yt/frontends/flash/tests/test_outputs.py
  yt/frontends/gadget/tests/test_outputs.py
  yt/frontends/gadget_fof/tests/test_outputs.py
  yt/frontends/owls/tests/test_outputs.py
  yt/frontends/rockstar/tests/test_outputs.py
  yt/frontends/swift/tests/test_outputs.py
  yt/frontends/tipsy/tests/test_outputs.py
  yt/testing.py
Labels: index: particle, infrastructure, tests: running tests, yt-4.0

#2627 Adding nbody answer tests using particle plots
  yt/frontends/flash/tests/test_outputs.py
  yt/utilities/answer_testing/framework.py
Labels: demeshening, index: particle, infrastructure

#2644 Don't allow edges to extend beyond domain for SPH region sources.
  yt/geometry/coordinates/cartesian_coordinates.py
Labels: bug, index: particle, viz: 2D

#2624 Update TNG tests and add another dont_cache check for loading
  tests/tests.yaml
  yt/frontends/arepo/tests/test_outputs.py
  yt/geometry/particle_geometry_handler.py
Labels: bug, demeshening

#2613 Modified artio frontend fields to ytep 0003 conv: Issue/2608/artio
  yt/fields/field_aliases.py
  yt/frontends/artio/fields.py
Labels: enhancement

#2569 annotate_clear -> clear_annotations
  doc/source/cookbook/find_clumps.py
  doc/source/reference/api/api.rst
  doc/source/visualizing/callbacks.rst
  yt/visualization/plot_window.py
Labels: enhancement, viz: 2D, yt-4.0

#2634 [yt-4.0] check for bbox before reverting to all_data
  yt/geometry/selection_routines.pyx
Labels: bug, yt-4.0

#2559 Dataset abstraction: Default unique identifier
  yt/data_objects/static_output.py
  yt/frontends/_skeleton/data_structures.py
  yt/frontends/ahf/data_structures.py
  yt/frontends/art/data_structures.py
  yt/frontends/artio/data_structures.py
  yt/frontends/chombo/data_structures.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/enzo_p/data_structures.py
  yt/frontends/fits/data_structures.py
  yt/frontends/flash/data_structures.py
  yt/frontends/gadget/data_structures.py
  yt/frontends/gadget_fof/data_structures.py
  yt/frontends/gamer/data_structures.py
  yt/frontends/owls_subfind/data_structures.py
  yt/frontends/ramses/data_structures.py
  yt/frontends/rockstar/data_structures.py
  yt/frontends/sdf/data_structures.py
  yt/frontends/tipsy/data_structures.py
  yt/frontends/ytdata/data_structures.py
Labels: enhancement, proposal, yt core, yt-4.0

#2663 Changing the order of ops to prevent unyt error. Fixes #2662
  yt/frontends/enzo_p/fields.py
Labels: bug

#2606 add progress bar display for yt.load_sample() (requires tqdm)
  yt/utilities/load_sample.py
Labels: enhancement

#2660 CI: optimize testing time for AMRVAC
  tests/tests.yaml
  yt/frontends/amrvac/tests/test_outputs.py
Labels: code frontends, enhancement, tests: running tests

#2677 [BUGFIX] Call function wrapped with requires_file
  tests/tests.yaml
  yt/frontends/arepo/tests/test_outputs.py
  yt/frontends/owls_subfind/tests/test_outputs.py
  yt/frontends/ramses/tests/test_outputs.py
  yt/testing.py
  yt/utilities/tests/test_minimal_representation.py
Labels: blocker, bug, tests: running tests, yt-4.0

#2678 [BUGFIX] adaptahop frontend
  yt/frontends/adaptahop/data_structures.py
  yt/frontends/adaptahop/io.py
  yt/frontends/adaptahop/tests/test_outputs.py
  yt/frontends/halo_catalog/data_structures.py
Labels: bug, yt-4.0

#2679 [BUGFIX] Prevent RAMSES fail with recent versions of `f90nml`
  yt/frontends/ramses/data_structures.py
Labels: bug, code frontends, yt-4.0

#2680 [BUGFIX] ValueError with mesh deposition mechanism
  yt/data_objects/octree_subset.py
  yt/geometry/tests/test_particle_deposit.py
Labels: bug, yt-4.0

#2681 Allow throttling of number of cores for build.
  setup.py
Labels: bug

#2686 Update OpenPMD test to include 'nbody' ptype
  yt/frontends/arepo/tests/test_outputs.py
  yt/frontends/open_pmd/tests/test_outputs.py
Labels: bug, yt-4.0

#2689 Remove the reference to conda nighthlies since they're not being buil…
  README.md
  doc/source/installing.rst
Labels: docs

#2654 [bugfix] update art frontend to be compatible with numpy 1.18
  yt/frontends/art/io.py
Labels: bug, code frontends

#2697 Updating enzo active particle tests
  yt/frontends/enzo/tests/test_outputs.py
Labels: bug, code frontends

#2698 Fix Rockstar PSC tests with a nulp check
  yt/testing.py
Labels: bug, code frontends

#2696 Fix khi_cartesian_2D filename
  tests/tests.yaml
  yt/frontends/amrvac/tests/test_outputs.py
Labels: bug, tests: running tests

#2693 [bugfix] ewah_bool_wrap needs C++11 on some Linux machines
  setup.py
Labels: bug

#2688 [BUGFIX] Art: fix dm_only frontend
  yt/frontends/art/data_structures.py
  yt/frontends/art/io.py
  yt/frontends/art/tests/test_outputs.py
Labels: bug, tests: running tests, yt-4.0

#2701 promote log message from warning to error in add_field methods
  yt/data_objects/static_output.py
  yt/fields/local_fields.py
Labels: api-consistency, enhancement

#2690 Time series enhancements
  yt/convenience.py
  yt/data_objects/tests/test_time_series.py
  yt/data_objects/time_series.py
Labels: api-consistency, backwards incompatible, enhancement

#2705 Bump unyt to 2.7.2
  appveyor.yml
  setup.py
  tests/test_minimal_requirements.txt
  tests/test_requirements.txt
Labels: infrastructure, units, yt core

#2661 Offset particle selection test for unitary coords
  yt/testing.py
Labels: enhancement, tests: running tests
