Repository yt-project/yt, pull requests merged in 2020-12, with the labels that each got.

#2985 Optimize Athena++ i/o
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/athena_pp/io.py
Labels: enhancement, performance

#2939 Fix GCC 5 Builds
  setup.py
  setupext.py
  yt/geometry/particle_oct_container.pyx
  yt/utilities/lib/cykdtree/kdtree.pyx
  yt/utilities/lib/cykdtree/utils.pyx
  yt/utilities/lib/cyoctree.pyx
  yt/utilities/lib/field_interpolation_tables.pxd
  yt/utilities/lib/geometry_utils.pyx
  yt/utilities/lib/grid_traversal.pyx
  yt/utilities/lib/image_samplers.pyx
  yt/utilities/lib/misc_utilities.pyx
  yt/utilities/lib/partitioned_grid.pyx
  yt/utilities/lib/pixelization_routines.pyx
  yt/utilities/lib/platform_dep.h
  yt/utilities/lib/platform_dep_math.hpp
Labels: bug, infrastructure, yt-4.0

#2938 fix: implement AMReXDataset._is_valid
  yt/frontends/boxlib/data_structures.py
  yt/frontends/boxlib/tests/test_outputs.py
Labels: bug, code frontends

#2993 Update apt cache to avoid random missing packages
  tests/ci_install.sh
Labels: enhancement, tests: running tests

#2990 maint: drop mock as a third party dependency
  tests/test_minimal_requirements.txt
  tests/test_requirements.txt
  yt/data_objects/tests/test_projection.py
  yt/data_objects/tests/test_slice.py
  yt/utilities/tests/test_config.py
  yt/visualization/tests/test_particle_plot.py
Labels: enhancement, infrastructure

#2995 Splitting selection_routines into subfiles
  yt/geometry/_selection_routines/always_selector.pxi
  yt/geometry/_selection_routines/boolean_selectors.pxi
  yt/geometry/_selection_routines/compose_selector.pxi
  yt/geometry/_selection_routines/cut_region_selector.pxi
  yt/geometry/_selection_routines/cutting_plane_selector.pxi
  yt/geometry/_selection_routines/data_collection_selector.pxi
  yt/geometry/_selection_routines/disk_selector.pxi
  yt/geometry/_selection_routines/ellipsoid_selector.pxi
  yt/geometry/_selection_routines/grid_selector.pxi
  yt/geometry/_selection_routines/halo_particles_selector.pxi
  yt/geometry/_selection_routines/indexed_octree_subset_selector.pxi
  yt/geometry/_selection_routines/octree_subset_selector.pxi
  yt/geometry/_selection_routines/ortho_ray_selector.pxi
  yt/geometry/_selection_routines/point_selector.pxi
  yt/geometry/_selection_routines/ray_selector.pxi
  yt/geometry/_selection_routines/region_selector.pxi
  yt/geometry/_selection_routines/selector_object.pxi
  yt/geometry/_selection_routines/slice_selector.pxi
  yt/geometry/_selection_routines/sphere_selector.pxi
  yt/geometry/selection_routines.pyx
Labels: refactor

#2994 fix: replace all spurious occurences of 'raise SyntaxError'
  yt/data_objects/static_output.py
  yt/utilities/math_utils.py
  yt/visualization/plot_modifications.py
Labels: api-consistency, enhancement

#2996 Ignore old commits authored by 'convert-repo' in git blame
  .git-blame-ignore-revs
Labels: infrastructure

#2999 cleanup: remove leftover copyright blurbs
  yt/frontends/adaptahop/api.py
  yt/frontends/adaptahop/tests/test_outputs.py
  yt/frontends/ytdata/tests/test_old_outputs.py
Labels: docs, enhancement

#2988 [bugfix] preserve result_id with dynamic_parallel_objects
  yt/utilities/parallel_tools/task_queue.py
Labels: bug

#2896 Remove interactive volume rendering to repackage it elsewhere
  yt/__init__.py
  yt/visualization/volume_rendering/api.py
  yt/visualization/volume_rendering/glfw_inputhook.py
  yt/visualization/volume_rendering/input_events.py
  yt/visualization/volume_rendering/interactive_loop.py
  yt/visualization/volume_rendering/interactive_vr.py
  yt/visualization/volume_rendering/interactive_vr_helpers.py
  yt/visualization/volume_rendering/shader_objects.py
  yt/visualization/volume_rendering/shaders/__init__.py
  yt/visualization/volume_rendering/shaders/apply_colormap.fragmentshader
  yt/visualization/volume_rendering/shaders/default.vertexshader
  yt/visualization/volume_rendering/shaders/drawlines.fragmentshader
  yt/visualization/volume_rendering/shaders/max_intensity.fragmentshader
  yt/visualization/volume_rendering/shaders/mesh.fragmentshader
  yt/visualization/volume_rendering/shaders/mesh.vertexshader
  yt/visualization/volume_rendering/shaders/noop.fragmentshader
  yt/visualization/volume_rendering/shaders/passthrough.fragmentshader
  yt/visualization/volume_rendering/shaders/passthrough.vertexshader
  yt/visualization/volume_rendering/shaders/projection.fragmentshader
  yt/visualization/volume_rendering/shaders/transfer_function.fragmentshader
Labels: proposal, refactor, viz: volume rendering, yt-4.0

#2991 doc: add minimal structure to SkeletonDataset class
  doc/source/developing/creating_frontend.rst
  yt/frontends/_skeleton/data_structures.py
Labels: docs, enhancement

#2893 Clarify some utility functions (`yt.funcs`) with more_itertools
  doc/source/reference/api/api.rst
  tests/test_minimal_requirements.txt
  tests/test_requirements.txt
  yt/__init__.py
  yt/data_objects/construction_data_containers.py
  yt/data_objects/data_containers.py
  yt/data_objects/derived_quantities.py
  yt/data_objects/index_subobjects/grid_patch.py
  yt/data_objects/index_subobjects/particle_container.py
  yt/data_objects/profiles.py
  yt/data_objects/selection_objects/boolean_operations.py
  yt/data_objects/selection_objects/cut_region.py
  yt/data_objects/selection_objects/data_selection_objects.py
  yt/data_objects/selection_objects/disk.py
  yt/data_objects/selection_objects/object_collection.py
  yt/data_objects/selection_objects/ray.py
  yt/data_objects/selection_objects/region.py
  yt/data_objects/selection_objects/slices.py
  yt/data_objects/selection_objects/spheroids.py
  yt/data_objects/static_output.py
  yt/data_objects/time_series.py
  yt/data_objects/unions.py
  yt/fields/derived_field.py
  yt/fields/local_fields.py
  yt/fields/vector_operations.py
  yt/frontends/amrvac/io.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/enzo_p/misc.py
  yt/frontends/enzo_p/tests/test_misc.py
  yt/frontends/fits/data_structures.py
  yt/frontends/stream/data_structures.py
  yt/frontends/stream/definitions.py
  yt/funcs.py
  yt/geometry/coordinates/coordinate_handler.py
  yt/geometry/grid_geometry_handler.py
  yt/loaders.py
  yt/testing.py
  yt/tests/test_funcs.py
  yt/utilities/amr_kdtree/amr_kdtree.py
  yt/utilities/command_line.py
  yt/utilities/grid_data_format/writer.py
  yt/utilities/minimal_representation.py
  yt/utilities/parallel_tools/parallel_analysis_interface.py
  yt/visualization/base_plot_types.py
  yt/visualization/fits_image.py
  yt/visualization/fixed_resolution.py
  yt/visualization/line_plot.py
  yt/visualization/particle_plots.py
  yt/visualization/plot_container.py
  yt/visualization/plot_modifications.py
  yt/visualization/plot_window.py
  yt/visualization/profile_plotter.py
  yt/visualization/volume_rendering/camera.py
  yt/visualization/volume_rendering/off_axis_projection.py
  yt/visualization/volume_rendering/old_camera.py
  yt/visualization/volume_rendering/render_source.py
  yt/visualization/volume_rendering/transfer_functions.py
Labels: api-consistency, refactor

#3002 fix: add more_itertools to requirements in setup.py
  setup.py
Labels: bug, infrastructure

#2739 cleanup: harmonise _is_valid methods (followup #2695)
  yt/data_objects/static_output.py
  yt/frontends/_skeleton/data_structures.py
  yt/frontends/adaptahop/data_structures.py
  yt/frontends/ahf/data_structures.py
  yt/frontends/amrvac/data_structures.py
  yt/frontends/arepo/data_structures.py
  yt/frontends/art/data_structures.py
  yt/frontends/artio/data_structures.py
  yt/frontends/athena/data_structures.py
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/boxlib/data_structures.py
  yt/frontends/chombo/data_structures.py
  yt/frontends/eagle/data_structures.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/enzo_p/data_structures.py
  yt/frontends/exodus_ii/data_structures.py
  yt/frontends/fits/data_structures.py
  yt/frontends/flash/data_structures.py
  yt/frontends/gadget/data_structures.py
  yt/frontends/gadget_fof/data_structures.py
  yt/frontends/gamer/data_structures.py
  yt/frontends/gdf/data_structures.py
  yt/frontends/gizmo/data_structures.py
  yt/frontends/halo_catalog/data_structures.py
  yt/frontends/http_stream/data_structures.py
  yt/frontends/moab/data_structures.py
  yt/frontends/open_pmd/data_structures.py
  yt/frontends/owls/data_structures.py
  yt/frontends/owls_subfind/data_structures.py
  yt/frontends/ramses/data_structures.py
  yt/frontends/rockstar/data_structures.py
  yt/frontends/sdf/data_structures.py
  yt/frontends/stream/data_structures.py
  yt/frontends/swift/data_structures.py
  yt/frontends/tipsy/data_structures.py
  yt/frontends/ytdata/data_structures.py
Labels: api-consistency, code frontends, enhancement, refactor

#3004 maint: add missing entries for generated cpp files to .gitignore
  .gitignore
Labels: enhancement, infrastructure

#2989 [bugfix] Use axes unit in scale bar if set by user.
  yt/visualization/base_plot_types.py
  yt/visualization/plot_modifications.py
Labels: bug

#3000 refactor: remove yt.funcs.ensure_tuple
  yt/frontends/amrvac/data_structures.py
  yt/frontends/athena/data_structures.py
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/enzo_p/data_structures.py
  yt/frontends/gdf/data_structures.py
  yt/funcs.py
Labels: refactor

#3006 boxlib: Fix _read_header for 2D data
  yt/frontends/boxlib/data_structures.py
Labels: bug, code frontends

#3014 doc: markup shell snippets in README.md
  README.md
Labels: docs, enhancement

#3011 maint: remove redundant style-checker (pep8speaks)
  .pep8speaks.yml
Labels: code style, dead code, infrastructure

#3008 maint: remove vendored packages
  .coveragerc
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.rst
  CREDITS
  doc/Makefile
  pyproject.toml
  setup.cfg
  setup.py
  tests/test_requirements.txt
  yt/data_objects/construction_data_containers.py
  yt/extern/__init__.py
  yt/extern/_dummy_thread32.py
  yt/extern/parameterized.py
  yt/extern/peewee.py
  yt/extern/pydot.py
  yt/extern/pykdtree.py
  yt/extern/reprlib32.py
  yt/extern/tqdm/LICENSE
  yt/extern/tqdm/__init__.py
  yt/extern/tqdm/_tqdm.py
  yt/extern/tqdm/_tqdm_gui.py
  yt/extern/tqdm/_tqdm_pandas.py
  yt/extern/tqdm/_utils.py
  yt/extern/tqdm/_version.py
  yt/funcs.py
  yt/loaders.py
  yt/utilities/command_line.py
Labels: code style, dead code

#3009 maint: fix several problems in .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: bug, code style, infrastructure
