Repository yt-project/yt, pull requests merged in 2020-07, with the labels that each got.

#2650 fix an unintuitive behaviour in ProfilePlot
  yt/visualization/profile_plotter.py
Labels: api-consistency, enhancement

#2637 Fields autocompletion for data objects
  yt/data_objects/data_containers.py
  yt/data_objects/region_expression.py
Labels: new feature, yt-4.0

#2509 Use cython distutils directives
  .gitignore
  setup.py
  setupext.py
  tests/test_install_script.py
  yt/frontends/artio/_artio_caller.pyx
  yt/frontends/ramses/io_utils.pyx
  yt/geometry/fake_octree.pyx
  yt/geometry/grid_container.pyx
  yt/geometry/grid_visitors.pyx
  yt/geometry/oct_container.pyx
  yt/geometry/oct_visitors.pyx
  yt/geometry/particle_deposit.pyx
  yt/geometry/particle_oct_container.pyx
  yt/geometry/particle_smooth.pyx
  yt/geometry/selection_routines.pyx
  yt/utilities/cython_fortran_utils.pyx
  yt/utilities/lib/allocation_container.pyx
  yt/utilities/lib/alt_ray_tracers.pyx
  yt/utilities/lib/amr_kdtools.pyx
  yt/utilities/lib/basic_octree.pyx
  yt/utilities/lib/bitarray.pyx
  yt/utilities/lib/bounding_volume_hierarchy.pyx
  yt/utilities/lib/contour_finding.pyx
  yt/utilities/lib/cykdtree/kdtree.pyx
  yt/utilities/lib/cykdtree/utils.pyx
  yt/utilities/lib/cyoctree.pyx
  yt/utilities/lib/depth_first_octree.pyx
  yt/utilities/lib/distance_queue.pyx
  yt/utilities/lib/element_mappings.pyx
  yt/utilities/lib/embree_mesh/__init__.py
  yt/utilities/lib/embree_mesh/mesh_construction.pxd
  yt/utilities/lib/embree_mesh/mesh_construction.pyx
  yt/utilities/lib/embree_mesh/mesh_intersection.pxd
  yt/utilities/lib/embree_mesh/mesh_intersection.pyx
  yt/utilities/lib/embree_mesh/mesh_samplers.pxd
  yt/utilities/lib/embree_mesh/mesh_samplers.pyx
  yt/utilities/lib/embree_mesh/mesh_traversal.pxd
  yt/utilities/lib/embree_mesh/mesh_traversal.pyx
  yt/utilities/lib/ewah_bool_wrap.pyx
  yt/utilities/lib/fnv_hash.pyx
  yt/utilities/lib/fortran_reader.pyx
  yt/utilities/lib/geometry_utils.pyx
  yt/utilities/lib/grid_traversal.pyx
  yt/utilities/lib/image_samplers.pyx
  yt/utilities/lib/image_utilities.pyx
  yt/utilities/lib/interpolators.pyx
  yt/utilities/lib/lenses.pyx
  yt/utilities/lib/marching_cubes.pyx
  yt/utilities/lib/mesh_utilities.pyx
  yt/utilities/lib/misc_utilities.pyx
  yt/utilities/lib/origami.pyx
  yt/utilities/lib/particle_kdtree_tools.pyx
  yt/utilities/lib/particle_mesh_operations.pyx
  yt/utilities/lib/partitioned_grid.pyx
  yt/utilities/lib/pixelization_routines.pyx
  yt/utilities/lib/points_in_volume.pyx
  yt/utilities/lib/primitives.pyx
  yt/utilities/lib/quad_tree.pyx
  yt/visualization/volume_rendering/render_source.py
  yt/visualization/volume_rendering/utils.py
Labels: infrastructure

#2712 Make sure we include IDs as a particle type in Gadget FOF
  yt/frontends/gadget_fof/data_structures.py
  yt/frontends/gadget_fof/tests/test_outputs.py
Labels: bug, code frontends

#2732 Docstring example corrections for profile_plotter
  yt/visualization/profile_plotter.py
Labels: docs

#2717 [BUGFIX] Update con_args parsing for current h5py
  tests/test_requirements.txt
  yt/frontends/ytdata/data_structures.py
  yt/frontends/ytdata/tests/test_old_outputs.py
  yt/frontends/ytdata/tests/test_outputs.py
  yt/frontends/ytdata/tests/test_unit.py
Labels: bug, code frontends

#2592 Style: enforce import ordering with isort (YTEP0037 1/6)
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  CONTRIBUTING.rst
  setup.cfg
  tests/lint_requirements.txt
  yt/exthook.py
  yt/funcs.py
  yt/testing.py
Labels: code style, enhancement, proposal, yt-4.0

#2598 Add pyproject.toml (YTEP0037 3/6)
  pyproject.toml
Labels: infrastructure, proposal, yt-4.0

#2596 Black adoption (YTEP0037 4/6)
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  README.md
  pyproject.toml
  scripts/strip_trailing_whitespace.py
  setup.cfg
  tests/lint_requirements.txt
  yt/data_objects/derived_quantities.py
  yt/frontends/artio/data_structures.py
  yt/frontends/flash/data_structures.py
  yt/frontends/open_pmd/data_structures.py
  yt/frontends/open_pmd/fields.py
  yt/frontends/open_pmd/io.py
  yt/frontends/open_pmd/misc.py
  yt/frontends/ramses/data_structures.py
  yt/frontends/sdf/tests/test_outputs.py
  yt/frontends/stream/sample_data/hexahedral_mesh.py
  yt/funcs.py
  yt/utilities/parallel_tools/parallel_analysis_interface.py
  yt/utilities/sdf.py
  yt/visualization/_colormap_data.py
  yt/visualization/eps_writer.py
  yt/visualization/fixed_resolution.py
  yt/visualization/plot_modifications.py
  yt/visualization/plot_window.py
  yt/visualization/volume_rendering/off_axis_projection.py
  yt/visualization/volume_rendering/old_camera.py
  yt/visualization/volume_rendering/scene.py
  yt/visualization/volume_rendering/shader_objects.py
Labels: code style, enhancement, proposal, yt-4.0

#2595 ci: bump flake8 linter version, fix newly detected errors (YTEP0037 2/6)
  tests/lint_requirements.txt
  yt/data_objects/tests/test_fluxes.py
  yt/frontends/tipsy/data_structures.py
  yt/geometry/tests/test_particle_octree.py
Labels: bug, code style, yt-4.0

#2750 YTEP0037 (doc) add black and pre-commit hooks sections to CONTRIBUTING.rst
  CONTRIBUTING.rst
Labels: code style, docs, enhancement

#2753 Cleanup copyright blurb
  CONTRIBUTING.rst
  COPYING.txt
  yt/frontends/adaptahop/__init__.py
  yt/frontends/adaptahop/data_structures.py
  yt/frontends/adaptahop/definitions.py
  yt/frontends/adaptahop/fields.py
  yt/frontends/adaptahop/io.py
  yt/frontends/amrvac/__init__.py
  yt/frontends/amrvac/api.py
  yt/frontends/amrvac/data_structures.py
  yt/frontends/amrvac/fields.py
  yt/frontends/amrvac/io.py
Labels: docs, enhancement

#2754 hotfix: support matplotlib 3.3.0
  yt/utilities/png_writer.py
Labels: api-consistency, bug

#2600 Add precommit hooks for flake8, isort and black (YTEP0037 5/6)
  .pre-commit-config.yaml
Labels: code style, infrastructure, proposal, yt-4.0

#2758 add ignore list for git blame
  .git-blame-ignore-revs
Labels: enhancement, infrastructure

#2641 Cleanup legacy python checks
  .coveragerc
  .pep8speaks.yml
  setup.cfg
  yt/data_objects/construction_data_containers.py
  yt/fields/tests/test_fields_plugins.py
  yt/frontends/exodus_ii/util.py
  yt/frontends/sdf/data_structures.py
  yt/frontends/tipsy/data_structures.py
  yt/funcs.py
  yt/utilities/io_handler.py
  yt/utilities/lodgeit.py
  yt/utilities/lru_cache.py
  yt/utilities/poster/streaminghttp.py
  yt/utilities/tests/test_config.py
  yt/visualization/plot_window.py
Labels: enhancement, proposal, yt-4.0

#2725 fix: automatic slice->region expansion support for 1D and 2D datasets
  yt/data_objects/region_expression.py
Labels: api-consistency, bug, enhancement, yt-4.0

#2425 Octree ghost zones — reloaded
  tests/tests.yaml
  yt/data_objects/data_containers.py
  yt/data_objects/octree_subset.py
  yt/fields/fluid_fields.py
  yt/fields/geometric_fields.py
  yt/frontends/ramses/data_structures.py
  yt/frontends/ramses/io_utils.pyx
  yt/frontends/ramses/tests/test_outputs.py
  yt/geometry/fake_octree.pyx
  yt/geometry/oct_container.pxd
  yt/geometry/oct_container.pyx
  yt/geometry/oct_visitors.pxd
  yt/geometry/oct_visitors.pyx
Labels: index: octree, new feature, yt-4.0

#2768 Disable homebrew update during Travis/OSX build
  .travis.yml
Labels: infrastructure, tests: running tests

#2759 Parallel linting pass
  .travis.yml
Labels: bug, code style, infrastructure

#2771 Random tests optimization (take 2)
  appveyor.yml
  tests/test_minimal_requirements.txt
  tests/test_requirements.txt
  yt/data_objects/tests/test_projection.py
  yt/data_objects/tests/test_slice.py
  yt/visualization/tests/test_particle_plot.py
Labels: infrastructure, tests: running tests

#2668 fix flake8-bugbear B009 (YTEP0037 6/6, part 2)
  yt/data_objects/static_output.py
  yt/frontends/ytdata/data_structures.py
  yt/testing.py
  yt/utilities/command_line.py
Labels: code style, enhancement, yt-4.0

#2671 fix flake8-bugbear B001 (bare excepts) (YTEP0037 6/6 part 5)
  yt/frontends/arepo/data_structures.py
  yt/utilities/lib/cykdtree/tests/test_kdtree.py
Labels: code style, enhancement, yt-4.0

#2669 ignore flake8-bugbear B008 errors (YTEP0037 6/6 part 3)
  yt/testing.py
Labels: enhancement, yt-4.0

#2672 fix flake8-bugbear B010 errors (YTEP0037 6/6 part 6)
  yt/data_objects/profiles.py
  yt/data_objects/static_output.py
Labels: code style, enhancement, yt-4.0

#2673 fix flake8-bugbear B011 errors (YTEP0037 6/6 part 7)
  yt/visualization/volume_rendering/tests/test_off_axis_SPH.py
Labels: code style, enhancement, yt-4.0

#2670 fix flake8-bugbear B014 errors (redundancy in exception catching) (YTEP0037 6/6, part 4)
  yt/frontends/flash/data_structures.py
  yt/frontends/open_pmd/data_structures.py
Labels: code style, enhancement, yt-4.0

#2736 Remove all occurences of VR.render() called right before VR.save()
  doc/source/cookbook/amrkdtree_downsampling.py
  doc/source/cookbook/camera_movement.py
  doc/source/cookbook/opaque_rendering.py
  doc/source/cookbook/sigma_clip.py
  doc/source/cookbook/various_lens.py
  yt/utilities/answer_testing/answer_tests.py
  yt/utilities/answer_testing/framework.py
  yt/visualization/volume_rendering/tests/test_lenses.py
Labels: docs, tests: running tests

#2719 Hotfix broken raise statement
  yt/fields/field_info_container.py
Labels: api-consistency, bug

#2765 cleanup: remove version checks for python 3
  doc/source/cookbook/tests/test_cookbook.py
  setup.py
  setupext.py
  tests/nose_runner.py
  yt/frontends/art/io.py
  yt/utilities/lodgeit.py
Labels: enhancement

#2762 cleanup: legacy python doc
  benchmarks/asv.conf.json
  doc/activate
  doc/install_script.sh
  doc/source/analyzing/parallel_computation.rst
  doc/source/developing/debugdrive.rst
  doc/source/developing/external_analysis.rst
  doc/source/developing/testing.rst
  doc/source/installing.rst
  setup.py
Labels: bug, docs

#2770 Bump IPython version for py38 support. Fixes #2741
  doc/source/intro/index.rst
  tests/test_requirements.txt
Labels: docs, infrastructure

#2772 Flake8 errors fixup
  setup.cfg
  yt/data_objects/analyzer_objects.py
  yt/data_objects/time_series.py
  yt/frontends/art/io.py
  yt/utilities/decompose.py
  yt/visualization/volume_rendering/old_camera.py
Labels: code style, enhancement

#2556 Abstract data structures
  doc/source/examining/low_level_inspection.rst
  yt/data_objects/static_output.py
  yt/frontends/_skeleton/data_structures.py
  yt/frontends/_skeleton/io.py
  yt/frontends/enzo/io.py
  yt/frontends/gadget_fof/data_structures.py
  yt/geometry/geometry_handler.py
  yt/geometry/grid_geometry_handler.py
  yt/utilities/io_handler.py
Labels: enhancement, yt core, yt-4.0

#2674 ci: add flake8-bugbear to travis linting (YTEP0037 6/6 part 0)
  setup.cfg
  tests/lint_requirements.txt
  yt/data_objects/data_containers.py
  yt/data_objects/particle_container.py
  yt/data_objects/selection_data_containers.py
  yt/frontends/fits/data_structures.py
  yt/frontends/open_pmd/data_structures.py
  yt/utilities/answer_testing/answer_tests.py
  yt/utilities/lib/cykdtree/plot.py
  yt/visualization/eps_writer.py
Labels: code style, enhancement, infrastructure, yt-4.0

#2667 fix flake8-bugbear B006 (YTEP0037 6/6, part 1)
  setup.cfg
  yt/data_objects/data_containers.py
  yt/data_objects/particle_container.py
  yt/data_objects/selection_data_containers.py
  yt/frontends/fits/data_structures.py
  yt/frontends/open_pmd/data_structures.py
  yt/utilities/answer_testing/answer_tests.py
  yt/utilities/lib/cykdtree/plot.py
  yt/visualization/eps_writer.py
Labels: bug, yt-4.0

#2779 Ignore .kdtree file while detecting format. Fixes #2778
  yt/frontends/gadget/data_structures.py
  yt/frontends/gizmo/data_structures.py
  yt/frontends/owls/data_structures.py
Labels: bug, code frontends

#2645 Support for Gadget HDF5-like datasets without smoothing lengths included
  tests/tests.yaml
  yt/frontends/arepo/fields.py
  yt/frontends/arepo/io.py
  yt/frontends/eagle/fields.py
  yt/frontends/gadget/data_structures.py
  yt/frontends/gadget/fields.py
  yt/frontends/gadget/io.py
  yt/frontends/owls/fields.py
Labels: enhancement

#2743 Adds render option to scene.save to avoid re-rendering
  doc/source/visualizing/Volume_Rendering_Tutorial.ipynb
  doc/source/visualizing/volume_rendering.rst
  yt/visualization/volume_rendering/scene.py
  yt/visualization/volume_rendering/tests/test_save_render.py
  yt/visualization/volume_rendering/volume_rendering.py
Labels: api-consistency, enhancement, viz: volume rendering

#2716 Allow in_conda_env to look for conda-forge
  setupext.py
Labels: bug, infrastructure

#2795 Misc fixes to issues found during docs building
  doc/source/visualizing/callbacks.rst
  yt/visualization/color_maps.py
  yt/visualization/eps_writer.py
  yt/visualization/line_plot.py
Labels: infrastructure

#2789 Slash commands
  .github/workflows/slash-command-dispatch.yml
Labels: code style, infrastructure, new feature

#2777 update pre-commit hooks
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  tests/lint_requirements.txt
Labels: code style, enhancement

#2783 remove poster module
  .coveragerc
  .pep8speaks.yml
  setup.cfg
  yt/data_objects/construction_data_containers.py
  yt/data_objects/selection_data_containers.py
  yt/data_objects/static_output.py
  yt/utilities/minimal_representation.py
  yt/utilities/poster/README
  yt/utilities/poster/__init__.py
  yt/utilities/poster/encode.py
  yt/utilities/poster/streaminghttp.py
Labels: enhancement, proposal

#2724 add support for region selection with numpy-like ellipsis syntax
  setup.cfg
  yt/data_objects/data_containers.py
  yt/data_objects/region_expression.py
  yt/data_objects/tests/test_regions.py
Labels: api-consistency, new feature, yt-4.0
