Repository yt-project/yt, pull requests merged in 2021-02, with the labels that each got.

#3038 exp: remove DatasetSeries.__iter__
  yt/data_objects/time_series.py
Labels: dead code, enhancement

#3056 doc: replace dead travis badge with corresponding GH workflow build status
  README.md
Labels: docs, infrastructure

#3058 doc: add badges for isort, precommit-ci, and minimal supported python
  README.md
Labels: docs, infrastructure

#3060 doc: add short descriptions of main code formatters
  CONTRIBUTING.rst
  pyproject.toml
Labels: code style, docs

#3063 Cleanup flake8 conf
  setup.cfg
  yt/frontends/athena/fields.py
  yt/frontends/athena_pp/fields.py
  yt/frontends/enzo/fields.py
  yt/frontends/flash/fields.py
  yt/utilities/answer_testing/utils.py
  yt/visualization/eps_writer.py
Labels: code style, infrastructure

#3054 ci: install wheel as part of our gh build workflows
  tests/test_prerequirements.txt
Labels: infrastructure

#3068 ci: deactivate a randomly failing answer test
  yt/visualization/volume_rendering/tests/test_vr_orientation.py
Labels: bug, tests: running tests

#3051 maint: replace numpy alias types with corresponding builtin types
  yt/data_objects/construction_data_containers.py
  yt/data_objects/tests/test_particle_trajectories.py
  yt/frontends/adaptahop/io.py
  yt/frontends/art/io.py
  yt/frontends/artio/_artio_caller.pyx
  yt/frontends/athena/data_structures.py
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/boxlib/data_structures.py
  yt/frontends/boxlib/io.py
  yt/frontends/chombo/io.py
  yt/frontends/enzo_p/misc.py
  yt/frontends/open_pmd/data_structures.py
  yt/frontends/open_pmd/fields.py
  yt/frontends/open_pmd/misc.py
  yt/frontends/ramses/hilbert.py
  yt/frontends/stream/tests/test_stream_octree.py
  yt/frontends/ytdata/data_structures.py
  yt/geometry/grid_geometry_handler.py
  yt/geometry/tests/test_particle_octree.py
  yt/utilities/math_utils.py
  yt/utilities/parallel_tools/parallel_analysis_interface.py
  yt/utilities/sdf.py
  yt/visualization/volume_rendering/render_source.py
Labels: enhancement

#3072 [BUGFIX] Support old gcc versions
  setup.py
  setupext.py
Labels: bug

#3073 Update install doc
  doc/source/installing.rst
Labels: docs

#3066 Hotfix docs build
  CONTRIBUTING.rst
  doc/source/cookbook/index.rst
  doc/source/index.rst
  doc/source/reference/api/api.rst
  setup.cfg
Labels: bug, docs, infrastructure

#3079 Remove unused _initialize_index functions.
  yt/frontends/adaptahop/io.py
  yt/frontends/ahf/io.py
  yt/frontends/art/io.py
  yt/frontends/flash/io.py
  yt/frontends/gadget_fof/io.py
  yt/frontends/http_stream/io.py
  yt/frontends/owls_subfind/io.py
  yt/frontends/rockstar/io.py
  yt/frontends/sdf/io.py
  yt/frontends/ytdata/io.py
Labels: dead code

#3080 Update matplotlib canonical link
  doc/source/conf.py
  doc/source/cookbook/custom_colorbar_tickmarks.ipynb
  doc/source/visualizing/plots.rst
  yt/visualization/plot_container.py
  yt/visualization/profile_plotter.py
Labels: infrastructure

#3077 CI: enforce consistent string formatting syntax in logger calls
  .pre-commit-config.yaml
  setup.cfg
  tests/report_failed_answers.py
  yt/data_objects/construction_data_containers.py
  yt/data_objects/selection_objects/ray.py
  yt/data_objects/static_output.py
  yt/frontends/nc4_cm1/data_structures.py
  yt/frontends/ramses/data_structures.py
  yt/frontends/stream/data_structures.py
Labels: code style, infrastructure

#3083 fix a NameError in yt.mods
  yt/mods.py
Labels: bug, dead code, question

#3037 Fix: loading DatasetSeries with broken arguments
  yt/data_objects/tests/test_time_series.py
  yt/data_objects/time_series.py
Labels: api-consistency, bug

#3086 fix another FutureWarning from numpy
  yt/funcs.py
Labels: bug

#3082 fix a FutureWarning from numpy
  doc/source/analyzing/units.rst
  yt/visualization/volume_rendering/render_source.py
Labels: bug

#3094 fix a string formatting error in yt.set_log_level
  yt/utilities/logger.py
Labels: bug

#3091 hotfix: avoid a deprecation warning in enzo frontend (periodicity)
  yt/frontends/enzo/data_structures.py
Labels: bug, code frontends

#3095 fix a visible deprecation warning (periodicity) for halo_catalog
  yt/frontends/halo_catalog/data_structures.py
Labels: bug, code frontends
