Repository yt-project/yt, pull requests merged in 2021-11, with the labels that each got.

#3598 Backport PR #3490 on branch yt-4.0.x (ENH: loosen header matching for Athena vtk files to allow compatibility with single variable 'vtk outputs')
  yt/frontends/athena/data_structures.py
Labels: bug, code frontends

#3599 Backport PR #3496 on branch yt-4.0.x (BUG: fix two bugs in yt.visualization.eps_writer)
  nose_unit.cfg
  tests/tests.yaml
  yt/testing.py
  yt/visualization/eps_writer.py
  yt/visualization/tests/test_eps_writer.py
Labels: bug

#3634 ENH: cleanup verbatim testing function duplicates
  yt/frontends/ytdata/tests/test_outputs.py
  yt/utilities/answer_testing/answer_tests.py
  yt/utilities/answer_testing/testing_utilities.py
Labels: dead code

#3623 TST: sync version requirements for matplotlib across platforms
  setup.cfg
  tests/windows_conda_requirements.txt
Labels: enhancement, tests: running tests

#3607 BUG: override image suffix with matplotlib argument in case of conflict
  yt/visualization/plot_container.py
Labels: bug, viz: 2D, api-consistency

#3489 ENH: improve API consistency for ProjectionPlot VS SlicePlot
  doc/cheatsheet.tex
  doc/source/analyzing/fields.rst
  doc/source/cookbook/complex_plots.rst
  doc/source/cookbook/simple_off_axis_projection.py
  doc/source/reference/api/api.rst
  doc/source/visualizing/callbacks.rst
  doc/source/visualizing/plots.rst
  doc/source/yt4differences.rst
  yt/__init__.py
  yt/fields/tests/test_field_access.py
  yt/visualization/api.py
  yt/visualization/plot_window.py
  yt/visualization/tests/test_plotwindow.py
Labels: bug, enhancement, viz: 2D, api-consistency

#3254 ENH: AdaptaHOP more flexible support
  tests/tests.yaml
  yt/frontends/adaptahop/data_structures.py
  yt/frontends/adaptahop/definitions.py
  yt/frontends/adaptahop/fields.py
  yt/frontends/adaptahop/io.py
  yt/frontends/adaptahop/tests/test_outputs.py
Labels: enhancement, code frontends, refactor

#3615 ENH: Remove duplicate code in boxlib
  yt/frontends/boxlib/data_structures.py
  yt/frontends/boxlib/fields.py
  yt/frontends/boxlib/io.py
  yt/frontends/boxlib/misc.py
  yt/frontends/chombo/data_structures.py
  yt/frontends/chombo/fields.py
  yt/frontends/chombo/io.py
Labels: enhancement, refactor

#3441 ENH: migrate native colormaps out of yt and use cmyt as a dependency (YTEP-0040)
  doc/source/cookbook/colormaps.py
  doc/source/examining/Loading_Generic_Array_Data.ipynb
  doc/source/quickstart/3)_Simple_Visualization.ipynb
  doc/source/reference/configuration.rst
  doc/source/visualizing/colormaps/index.rst
  doc/source/visualizing/volume_rendering.rst
  setup.cfg
  tests/tests.yaml
  yt/config.py
  yt/testing.py
  yt/visualization/_colormap_data.py
  yt/visualization/color_maps.py
  yt/visualization/eps_writer.py
  yt/visualization/image_writer.py
  yt/visualization/tests/test_color_maps.py
  yt/visualization/tests/test_offaxisprojection.py
  yt/visualization/tests/test_particle_plot.py
  yt/visualization/tests/test_plotwindow.py
  yt/visualization/volume_rendering/old_camera.py
  yt/visualization/volume_rendering/render_source.py
  yt/visualization/volume_rendering/transfer_function_helper.py
  yt/visualization/volume_rendering/transfer_functions.py
Labels: enhancement

#3642 DOC: fix a broken example (change of api in the Athena frontend)
  doc/source/visualizing/callbacks.rst
Labels: bug, docs

#3657 BLD: drop wheel building for Python 3.6 and start building for 3.10
  .github/workflows/wheels.yaml
Labels: enhancement

#3661 BUG: fix an off-by-one error in ColorTransferFunction.to_map_colormap method
  yt/visualization/volume_rendering/transfer_functions.py
Labels: bug

#3645 Backport PR #3605 on branch yt-4.0.x (BLD: Fix compilation on FreeBSD)
  yt/utilities/lib/platform_dep.h
  yt/utilities/lib/platform_dep_math.hpp
Labels: bug

#3646 Backport PR #3606 on branch yt-4.0.x (BLD: Fix build on i386)
  yt/utilities/lib/ewahboolarray/boolarray.h
  yt/utilities/lib/ewahboolarray/ewah-inl.h
  yt/utilities/lib/ewahboolarray/ewahutil.h
Labels: bug

#3647 Backport PR #3607 on branch yt-4.0.x (BUG: override image suffix with matplotlib argument in case of conflict)
  yt/visualization/plot_container.py
Labels: bug, viz: 2D, api-consistency

#3648 Backport PR #3618 on branch yt-4.0.x (BUG: fix a bug where 2D plots in spherical geometries would always use code-units in plot axes)
  tests/tests.yaml
  yt/data_objects/static_output.py
  yt/visualization/plot_modifications.py
  yt/visualization/plot_window.py
Labels: bug, viz: 2D, coordinates: non-cartesian

#3649 Backport PR #3630 on branch yt-4.0.x ([gdf] dimensionality doesn't imply which dimension is reduced)
  yt/frontends/gdf/data_structures.py
Labels: bug, code frontends

#3664 MNT: loose exact Python runtime requirement in pre-commit configuration
  .pre-commit-config.yaml
Labels: enhancement, infrastructure

#3643 Backport PR #3465 on branch yt-4.0.x (BUG: fix error message in lookup_on_disk_data)
  yt/sample_data/api.py
Labels: bug, UX

#3662 Backport PR #3661 on branch yt-4.0.x (BUG: fix an off-by-one error in ColorTransferFunction.to_map_colormap method)
  yt/visualization/volume_rendering/transfer_functions.py
Labels: bug

#3665 DOC: add an exhaustive list of deprecations to the yt4differences page
  doc/source/yt4differences.rst
Labels: docs, deprecation, backport-yt-4.0.x

#3668 Backport PR #3665 on branch yt-4.0.x (DOC: add an exhaustive list of deprecations to the yt4differences page)
  doc/source/yt4differences.rst
Labels: docs, deprecation

#3658 BLD: build wheels for 3.10, align workflow file with main branch (yt-4.0.x)
  .github/workflows/wheels.yaml
Labels: enhancement

#3624 ENH: Factorize code in halo containers
  yt/frontends/gadget_fof/data_structures.py
  yt/frontends/halo_catalog/data_structures.py
Labels: enhancement, code frontends, refactor

#3666 ENH: implement hint keyword argument for yt.load to help lifting ambiguities in dataformat
  yt/data_objects/time_series.py
  yt/loaders.py
  yt/tests/test_load_errors.py
  yt/utilities/exceptions.py
  yt/utilities/hierarchy_inspection.py
Labels: enhancement

#3651 Backport symlog norm patches to yt-4.0.x
  yt/funcs.py
  yt/utilities/on_demand_imports.py
  yt/visualization/base_plot_types.py
  yt/visualization/color_maps.py
  yt/visualization/plot_container.py
  yt/visualization/plot_window.py
  yt/visualization/profile_plotter.py
Labels: bug, viz: 2D

#3240 DEPR: deprecation cycle (4.0 -> 4.1)
  doc/source/cookbook/complex_plots.rst
  doc/source/reference/api/api.rst
  yt/__init__.py
  yt/config.py
  yt/data_objects/derived_quantities.py
  yt/data_objects/index_subobjects/octree_subset.py
  yt/data_objects/static_output.py
  yt/data_objects/time_series.py
  yt/fields/field_info_container.py
  yt/fields/local_fields.py
  yt/fields/particle_fields.py
  yt/fields/species_fields.py
  yt/funcs.py
  yt/loaders.py
  yt/utilities/amr_kdtree/amr_kdtree.py
  yt/utilities/answer_testing/framework.py
  yt/utilities/command_line.py
  yt/utilities/configure.py
  yt/utilities/exceptions.py
  yt/utilities/tests/test_config.py
  yt/visualization/color_maps.py
  yt/visualization/eps_writer.py
  yt/visualization/image_writer.py
  yt/visualization/plot_container.py
  yt/visualization/plot_window.py
Labels: backwards incompatible, refactor, deprecation

#3671 BLD: Explicitly cast np.argsort() result to target data type
  yt/geometry/particle_oct_container.pyx
  yt/utilities/lib/geometry_utils.pyx
Labels: bug

#3653 MNT: loosen sympy version pinning in dependencies
  setup.cfg
Labels: enhancement

#3679 Backport PR #3671 on branch yt-4.0.x (BLD: Explicitly cast np.argsort() result to target data type)
  yt/geometry/particle_oct_container.pyx
  yt/utilities/lib/geometry_utils.pyx
Labels: bug

#3680 Backport PR #3653 on branch yt-4.0.x (MNT: loosen sympy version pinning in dependencies)
  setup.cfg
Labels: enhancement

#3688 BUG: Take into account endianness when reading Gadget binary files
  yt/frontends/gadget/io.py
  yt/geometry/particle_oct_container.pyx
Labels: bug

#3689 Backport PR #3688 on branch yt-4.0.x (BUG: Take into account endianness when reading Gadget binary files)
  yt/frontends/gadget/io.py
  yt/geometry/particle_oct_container.pyx
Labels: bug

#3692 BUG: hotfix for a functional breakage introduced in #3546
  yt/visualization/plot_modifications.py
Labels: bug

#3628 BUG: fixes for Hammer-Aitoff projection (r-normal) 2D viz in spherical geometries
  doc/source/visualizing/plots.rst
  tests/tests.yaml
  yt/geometry/coordinates/spherical_coordinates.py
  yt/utilities/lib/pixelization_routines.pyx
  yt/visualization/plot_container.py
  yt/visualization/plot_window.py
Labels: bug, viz: 2D, docs, coordinates: non-cartesian, api-consistency, refactor

#3686 ENH: make plot callbacks with 'factor' argument accept 2-tuples to distinguish x/y resolutions
  yt/visualization/plot_modifications.py
  yt/visualization/tests/test_callbacks.py
Labels: enhancement, viz: 2D, api-consistency

#3693 Backport PR #3628 on branch yt-4.0.x (BUG: fixes for Hammer-Aitoff projection (r-normal) 2D viz in spherical geometries)
  doc/source/visualizing/plots.rst
  tests/tests.yaml
  yt/geometry/coordinates/spherical_coordinates.py
  yt/utilities/lib/pixelization_routines.pyx
  yt/visualization/plot_container.py
  yt/visualization/plot_window.py
Labels: bug, viz: 2D, docs, coordinates: non-cartesian, api-consistency, refactor

#3687 BUG: fix a bug where PlotContainer.save would wrongfully ignore specified field extension
  yt/visualization/_commons.py
  yt/visualization/plot_container.py
  yt/visualization/profile_plotter.py
  yt/visualization/tests/test_commons.py
  yt/visualization/tests/test_save.py
Labels: bug, viz: 2D, api-consistency

#3700 BUG: fix a name error in SphericalCoordinateHandler
  yt/geometry/coordinates/spherical_coordinates.py
Labels: bug, viz: 2D, coordinates: non-cartesian

#3701 Backport PR #3700 on branch yt-4.0.x (BUG: fix a name error in SphericalCoordinateHandler)
  yt/geometry/coordinates/spherical_coordinates.py
Labels: bug, viz: 2D, coordinates: non-cartesian

#3401 ENH: Cythonize Gamer's SRHD fields
  setup.py
  tests/tests.yaml
  yt/frontends/gamer/cfields.pyx
  yt/frontends/gamer/fields.py
Labels: enhancement, performance
