Repository yt-project/yt, pull requests merged in 2021-06, with the labels that each got.

#3280 load_sample: update amrvac sample data files registry
  yt/sample_data_registry.json
Labels: bug, code frontends

#3316 hotfix broken urls for amrvac data samples
  yt/sample_data_registry.json
Labels: bug, infrastructure

#3309 fix load_sample's signature
  yt/loaders.py
Labels: enhancement, yt-4.0

#3326 Make uniq_id a little bit more unique
  yt/data_objects/static_output.py
  yt/frontends/arepo/tests/test_outputs.py
Labels: enhancement

#3328 load_sample: fix a broken load_name (DMonly)
  yt/sample_data_registry.json
Labels: bug

#3329 load_sample: fix a broken load_name (ytdata_test)
  yt/sample_data_registry.json
Labels: bug

#3295 Make symlog choose a better default linthresh
  doc/source/visualizing/plots.rst
  tests/tests.yaml
  yt/visualization/base_plot_types.py
  yt/visualization/plot_container.py
  yt/visualization/plot_window.py
Labels: blocker, bug, yt-4.0

#3330 load_sample: fix a handful of broken load names
  yt/sample_data_registry.json
Labels: bug

#3338 load_sample: fixup broken load_kwargs for athena datasets
  yt/sample_data_registry.json
Labels: bug

#3342 load_sample: fix a mistake in pointers to an AMRVAC dataset
  yt/sample_data_registry.json
Labels: bug

#3236 maint: merge dependency specifications into setup.cfg
  doc/source/developing/testing.rst
  setup.cfg
  tests/cartopy_requirements.txt
  tests/ci_install.sh
  tests/test_minimal_requirements.txt
  tests/test_prerequirements.txt
  tests/test_requirements.txt
  tests/windows_conda_requirements.txt
Labels: infrastructure

#3325 update owls_subfind frontend and add some format flexibility
  tests/tests.yaml
  yt/frontends/gadget_fof/data_structures.py
  yt/frontends/owls_subfind/data_structures.py
  yt/frontends/owls_subfind/fields.py
  yt/frontends/owls_subfind/io.py
  yt/frontends/owls_subfind/tests/test_outputs.py
Labels: blocker, bug, code frontends

#3359 bump answers for local_halos tests
  tests/tests.yaml
Labels: blocker, bug, infrastructure

#3362 hotfix: don't require firefly_api even in full build as it's not available on Pypi any more
  setup.cfg
Labels: blocker, bug, infrastructure

#3354 Updating FAQ for 4
  doc/source/faq/index.rst
Labels: docs, yt-4.0

#3355 Doc review for yt-4.0
  doc/source/about/index.rst
  doc/source/analyzing/fields.rst
  doc/source/cookbook/complex_plots.rst
  doc/source/cookbook/opengl_ipython.py
  doc/source/cookbook/opengl_vr.py
  doc/source/help/index.rst
  doc/source/visualizing/callbacks.rst
  doc/source/visualizing/interactive_data_visualization.rst
  doc/source/visualizing/mapserver.rst
  doc/source/visualizing/plots.rst
Labels: docs, yt-4.0

#3363 Drop yt hub command
  doc/source/reference/command-line.rst
  doc/source/sharing_data.rst
  setup.cfg
  yt/config.py
  yt/utilities/command_line.py
Labels: dead code

#3361 Fix broken command-line options
  yt/config.py
  yt/utilities/answer_testing/framework.py
  yt/utilities/command_line.py
  yt/visualization/mapserver/pannable_map.py
Labels: bug, dead code

#3356 fix: add pyx to documentation build deps
  setup.cfg
Labels: bug, docs, infrastructure

#3340 load_sample: fix for load names matching directory names
  yt/loaders.py
  yt/sample_data_registry.json
Labels: api-consistency, bug

#3351 Change sample dataset name.
  doc/source/reference/api/api.rst
  doc/source/visualizing/plots.rst
Labels: bug, docs

#3349 cleanup Python version checking
  .pre-commit-config.yaml
  yt/__init__.py
  yt/frontends/artio/_artio_caller.pyx
  yt/frontends/artio/data_structures.py
  yt/frontends/gdf/io.py
  yt/startup_tasks.py
Labels: bug, infrastructure, yt-4.0

#3370 Update reference docs for 4.0
  doc/source/conf.py
  doc/source/developing/debugdrive.rst
  doc/source/reference/api/api.rst
  doc/source/reference/code_support.rst
  doc/source/reference/command-line.rst
  doc/source/reference/configuration.rst
  doc/source/reference/python_introduction.rst
  yt/utilities/command_line.py
Labels: bug, docs, yt-4.0

#3372 Update enzo-e code support.
  doc/source/reference/code_support.rst
Labels: docs

#3368 doc: fix some bugs/warnings in documentation build
  doc/source/analyzing/astropy_integrations.rst
  doc/source/analyzing/domain_analysis/index.rst
  doc/source/analyzing/fields.rst
  doc/source/analyzing/saving_data.rst
  doc/source/analyzing/units.rst
  doc/source/conf.py
  doc/source/cookbook/streamlines.py
  doc/source/cookbook/streamlines_isocontour.py
  doc/source/cookbook/surface_plot.py
  doc/source/developing/creating_derived_fields.rst
  doc/source/developing/creating_frontend.rst
  doc/source/examining/loading_data.rst
  doc/source/index.rst
  doc/source/intro/index.rst
  doc/source/reference/api/api.rst
  doc/source/reference/changelog.rst
  doc/source/reference/configuration.rst
  doc/source/reference/demeshening.rst
  doc/source/reference/index.rst
  doc/source/visualizing/callbacks.rst
  doc/source/visualizing/interactive_data_visualization.rst
  doc/source/visualizing/plots.rst
  doc/source/visualizing/streamlines.rst
  doc/source/yt4differences.rst
  setup.cfg
  yt/convenience.py
  yt/data_objects/derived_quantities.py
  yt/frontends/gadget/data_structures.py
  yt/frontends/open_pmd/fields.py
  yt/frontends/open_pmd/misc.py
  yt/funcs.py
  yt/loaders.py
  yt/utilities/lib/cykdtree/plot.py
  yt/visualization/fits_image.py
  yt/visualization/plot_modifications.py
Labels: bug, docs, yt-4.0

#3367 Updating developer guide for 4.0
  CONTRIBUTING.rst
Labels: docs, yt-4.0

#3350 Update install docs
  CONTRIBUTING.rst
  README.md
  doc/source/analyzing/parallel_computation.rst
  doc/source/developing/building_the_docs.rst
  doc/source/faq/index.rst
  doc/source/help/index.rst
  doc/source/installing.rst
  doc/source/intro/index.rst
  doc/source/quickstart/index.rst
  doc/source/visualizing/geographic_projections_and_transforms.rst
  doc/source/visualizing/plots.rst
  doc/source/visualizing/unstructured_mesh_rendering.rst
  doc/source/yt3differences.rst
  setup.cfg
  tests/ci_install.sh
  yt/data_objects/data_containers.py
  yt/funcs.py
  yt/utilities/command_line.py
  yt/utilities/exceptions.py
  yt/utilities/on_demand_imports.py
Labels: docs, yt-4.0

#3373 CI: bump answers for numpy 1.21
  tests/tests.yaml
  yt/visualization/tests/test_plotwindow.py
Labels: blocker, bug, infrastructure

#3375 [bugfix] Fix FITSParticleProjection for all axes
  yt/visualization/fits_image.py
Labels: bug

#3374 [bugfix] generate_smoothing_length expects 64-bit positions
  yt/frontends/gadget/io.py
Labels: bug

#3365 Fill out more yt 4 differences
  doc/source/yt4differences.rst
Labels: docs, yt-4.0

#3383 [bugfix] Forgot to tell the field detection algorithm about the species names
  yt/fields/particle_fields.py
  yt/frontends/gadget/fields.py
Labels: bug

#3378 Future proofing: forbid cython 3.0 until we can properly test against it
  pyproject.toml
  tests/ci_install.sh
  tests/windows_conda_requirements.txt
Labels: infrastructure, yt-4.0

#3198 Add a heuristic for resetting index_order2
  yt/data_objects/static_output.py
  yt/geometry/particle_geometry_handler.py
  yt/geometry/particle_oct_container.pyx
Labels: blocker, bug, demeshening, index: particle, performance, yt-4.0

#3388 Future proofing: set a minimal required wheel version in build system specs to improve compatibility with Python 3.10
  pyproject.toml
Labels: infrastructure, yt-4.0

#3391 Fixing particle trajectories
  yt/data_objects/particle_trajectories.py
  yt/utilities/parallel_tools/parallel_analysis_interface.py
Labels: bug, parallelism

#3377 UX: add suggestions in case of typo in yt.load_sampel
  yt/funcs.py
  yt/loaders.py
  yt/tests/test_load_sample.py
Labels: UX, enhancement

#3393 Docfix
  doc/source/analyzing/fields.rst
  doc/source/visualizing/callbacks.rst
  doc/source/visualizing/colormaps/index.rst
  doc/source/visualizing/manual_plotting.rst
  doc/source/visualizing/plots.rst
  doc/source/visualizing/sketchfab.rst
  doc/source/visualizing/streamlines.rst
  doc/source/visualizing/volume_rendering.rst
Labels: docs, yt-4.0

#3396 CI: deactivate conda update as a workaround to external failure
  .github/workflows/build-test-pytest.yaml
  .github/workflows/build-test.yaml
Labels: bug, infrastructure

#3394 Fixing docs
  doc/source/analyzing/Particle_Trajectories.ipynb
  doc/source/analyzing/domain_analysis/XrayEmissionFields.ipynb
  doc/source/analyzing/filtering.rst
  doc/source/analyzing/generating_processed_data.rst
  doc/source/analyzing/mesh_filter.ipynb
  doc/source/analyzing/objects.rst
  doc/source/analyzing/parallel_computation.rst
  doc/source/analyzing/saving_data.rst
  doc/source/analyzing/time_series_analysis.rst
  doc/source/cookbook/fits_radio_cubes.ipynb
  doc/source/cookbook/yt_gadget_analysis.ipynb
  doc/source/developing/creating_derived_fields.rst
  doc/source/developing/creating_derived_quantities.rst
  doc/source/developing/index.rst
  doc/source/examining/Loading_Generic_Array_Data.ipynb
  doc/source/examining/Loading_Generic_Particle_Data.ipynb
  doc/source/examining/Loading_Spherical_Data.ipynb
  doc/source/examining/loading_data.rst
  doc/source/examining/low_level_inspection.rst
  doc/source/faq/index.rst
  doc/source/index.rst
  doc/source/installing.rst
  doc/source/intro/index.rst
  doc/source/quickstart/4)_Data_Objects_and_Time_Series.ipynb
  doc/source/quickstart/5)_Derived_Fields_and_Profiles.ipynb
  doc/source/reference/changelog.rst
  doc/source/visualizing/plots.rst
  doc/source/visualizing/sketchfab.rst
  doc/source/yt3differences.rst
  doc/source/yt4differences.rst
  yt/data_objects/derived_quantities.py
  yt/utilities/amr_kdtree/amr_kdtree.py
  yt/visualization/plot_modifications.py
  yt/visualization/volume_rendering/lens.py
Labels: docs, yt-4.0
