Repository yt-project/yt, pull requests merged in 2021-07, with the labels that each got.

#3380 Future proofing: treat most warnings as errors in pytest, and fix existing ones
  .github/workflows/rules-checks.yaml
  conftest.py
  setup.cfg
  tests/windows_conda_requirements.txt
  yt/data_objects/construction_data_containers.py
  yt/data_objects/index_subobjects/grid_patch.py
  yt/frontends/art/data_structures.py
  yt/frontends/boxlib/data_structures.py
  yt/frontends/gadget/data_structures.py
  yt/geometry/oct_geometry_handler.py
  yt/tests/test_load_errors.py
  yt/utilities/fortran_utils.py
  yt/utilities/tests/test_cosmology.py
  yt/utilities/tests/test_interpolators.py
  yt/visualization/color_maps.py
  yt/visualization/plot_window.py
  yt/visualization/volume_rendering/lens.py
  yt/visualization/volume_rendering/old_camera.py
Labels: enhancement, infrastructure, yt-4.0

#3390 MAINT: grooming README.md for upcoming PyPI publication
  README.md
Labels: docs, yt-4.0

#3397 CI: revert temporary patch
  .github/workflows/build-test-pytest.yaml
  .github/workflows/build-test.yaml
Labels: bug, infrastructure

#3400 Remove unused imports from private CPython API that break PyPi builds
  yt/geometry/particle_deposit.pyx
Labels: bug

#3385 Future proofing: drop distutils.version (targeted for removal in Python 3.12)
  setup.cfg
  setupext.py
  yt/frontends/open_pmd/data_structures.py
  yt/funcs.py
  yt/utilities/on_demand_imports.py
  yt/visualization/base_plot_types.py
  yt/visualization/plot_window.py
  yt/visualization/profile_plotter.py
Labels: infrastructure

#3398 Merge stable branch into main for 4.0 release prep, add 4.0 changelog entry
  doc/source/reference/changelog.rst
Labels: docs, infrastructure

#3403 Update MANIFEST.in to include *.pxi and conftest.py
  MANIFEST.in
Labels: bug, yt-4.0

#3406 Port wheels build to GHA
  .github/workflows/wheels.yaml
  pyproject.toml
Labels: enhancement, infrastructure, yt-4.0

#3414 Bump version to 4.1 dev
  doc/source/conf.py
  setup.cfg
  setup.py
  yt/__init__.py
Labels: infrastructure

#3412 DOC: cleanup remaining occurences of pylab in favour of matplotlib.pyplot
  doc/source/quickstart/4)_Data_Objects_and_Time_Series.ipynb
  doc/source/quickstart/5)_Derived_Fields_and_Profiles.ipynb
  doc/source/reference/command-line.rst
  doc/source/visualizing/streamlines.rst
  doc/source/visualizing/unstructured_mesh_rendering.rst
  scripts/iyt
  yt/visualization/volume_rendering/tests/test_vr_cameras.py
Labels: docs

#3402 Change the loop order to avoid executing the same test 3 times
  yt/utilities/answer_testing/framework.py
Labels: bug, tests: running tests

#3420 STY: remove meaningless NOQA statement with yesqa
  doc/source/conf.py
  yt/frontends/amrvac/tests/test_outputs.py
  yt/sample_data/api.py
  yt/testing.py
  yt/utilities/grid_data_format/conversion/conversion_athena.py
  yt/utilities/logger.py
  yt/visualization/plot_container.py
Labels: code style, dead code

#3418 DEPR: deprecate iyt
  doc/cheatsheet.tex
  doc/source/reference/command-line.rst
  doc/source/reference/configuration.rst
  scripts/iyt
Labels: dead code, deprecation

#3408 MAINT: remove a unreachable conditional
  yt/data_objects/static_output.py
Labels: dead code

#3387 MAINT: update black configuration
  pyproject.toml
Labels: code style, infrastructure

#3423 Insert empty link to navbar in hope it fixes #3422
  doc/source/conf.py
Labels: docs, enhancement

#3376 Future proofing: add a scheduled job with dev versions of core deps
  .github/workflows/bleeding-edge.yaml
  .github/workflows/build-test-pytest.yaml
  .github/workflows/build-test.yaml
  README.md
  tests/windows_conda_requirements.txt
Labels: infrastructure, proposal, tests: running tests

#3425 Use a fancier repr for labels in Profile/PhasePlots. Fixes #3269
  yt/visualization/profile_plotter.py
Labels: bug, viz: 2D

#3427 Revert "Use a fancier repr for labels in Profile/PhasePlots. Fixes #3269"
  yt/visualization/profile_plotter.py
Labels: bug

#3432 Checking if extrema are all None in PhasePlot; fixes #3431
  yt/data_objects/profiles.py
  yt/data_objects/tests/test_profiles.py
Labels: bug

#3439 Cache _determine_fields for a given dataset
  yt/data_objects/data_containers.py
  yt/data_objects/static_output.py
Labels: enhancement, performance

#3440 FIX: add support for setting up derived fields from lambdas
  yt/fields/derived_field.py
  yt/fields/tests/test_fields.py
Labels: api-consistency, bug

#3413 Updating EWAH from upstream lemire/EWAHBoolArray
  yt/utilities/lib/ewah_bool_array.pxd
  yt/utilities/lib/ewah_bool_wrap.pyx
  yt/utilities/lib/ewahboolarray/boolarray.h
  yt/utilities/lib/ewahboolarray/ewah-inl.h
  yt/utilities/lib/ewahboolarray/ewah.h
  yt/utilities/lib/ewahboolarray/ewahutil.h
  yt/utilities/lib/ewahboolarray/runninglengthword.h
Labels: index: particle, infrastructure

#3445 Fix for 2D AMReX datasets in which 3 values are in the amr.n_cell entry in the job_info file.
  tests/tests.yaml
  yt/frontends/boxlib/data_structures.py
Labels: bug, code frontends

#3447 Backport for 4.0.1 bugfix release
  tests/tests.yaml
  yt/frontends/boxlib/data_structures.py
  yt/utilities/lib/ewah_bool_array.pxd
  yt/utilities/lib/ewah_bool_wrap.pyx
  yt/utilities/lib/ewahboolarray/boolarray.h
  yt/utilities/lib/ewahboolarray/ewah-inl.h
  yt/utilities/lib/ewahboolarray/ewah.h
  yt/utilities/lib/ewahboolarray/ewahutil.h
  yt/utilities/lib/ewahboolarray/runninglengthword.h
Labels: infrastructure

#3455 Make sure we add the Parameters group to hvals if it's present
  yt/frontends/gadget/data_structures.py
Labels: bug, code frontends

#3456 fix combining FITS images
  yt/visualization/fits_image.py
  yt/visualization/tests/test_fits_image.py
Labels: bug

#3435 Re-add Firefly support by updating the api for the new Firefly-vis pypi project
  doc/source/visualizing/_images/firefly_example.png
  doc/source/visualizing/visualizing_particle_datasets_with_firefly.rst
  setup.cfg
  yt/data_objects/data_containers.py
  yt/data_objects/tests/test_firefly.py
  yt/utilities/on_demand_imports.py
Labels: infrastructure, refactor
