Repository yt-project/yt, pull requests merged in 2021-12, with the labels that each got.

#3696 DOC: fix markup errors in spherical projections section
  doc/source/visualizing/plots.rst
Labels: bug, docs

#3698 Backport #3410 + #3687 to yt-4.0.x (image filename validation fixes)
  yt/visualization/_commons.py
  yt/visualization/_mpl_imports.py
  yt/visualization/plot_container.py
  yt/visualization/profile_plotter.py
  yt/visualization/tests/test_commons.py
  yt/visualization/tests/test_save.py
  yt/visualization/volume_rendering/scene.py
Labels: bug, viz: 2D, api-consistency

#3543 MNT: add explicit support for Python 3.10 on UNIX
  .github/workflows/build-test-pytest.yaml
  .pre-commit-config.yaml
  setup.cfg
Labels: tests: running tests, infrastructure, pytest

#3702 Backport PR #3696 on branch yt-4.0.x (DOC: fix markup errors in spherical projections section)
  doc/source/visualizing/plots.rst
Labels: bug, docs

#2505 Read new RAMSES info_rt format (compatible with old)
  yt/frontends/ramses/field_handlers.py
Labels: enhancement, code frontends, domain: astro

#3716 DOC: fix an error in AMRVAC specific documentation
  doc/source/examining/loading_data.rst
Labels: bug, docs

#3717 Backport PR #3716 on branch yt-4.0.x (DOC: fix an error in AMRVAC specific documentation)
  doc/source/examining/loading_data.rst
Labels: bug, docs

#3715 REL: update cibuildwheel, simplify wheel building workflow
  .github/workflows/wheels.yaml
Labels: enhancement, infrastructure

#3703 Backport #3543 to yt-4.0.x (MNT: add explicit support for Python 3.10 on UNIX)
  .github/workflows/build-test-pytest.yaml
  setup.cfg
Labels: enhancement, infrastructure, pytest

#3718 Backport PR #3715 to yt-4.0.x (REL: update cibuildwheel, simplify wheel building workflow)
  .github/workflows/wheels.yaml
Labels: enhancement, infrastructure

#3721 REL: drop overly protective version upper limits for hard dependencies
  setup.cfg
  tests/windows_conda_requirements.txt
Labels: enhancement

#3719 MNT: readd glueviz to [full] env (optional deps) on Python 3.10 following the release of glue-core 1.2.3
  setup.cfg
Labels: enhancement, backport-yt-4.0.x

#3724 Backport PR #3719 on branch yt-4.0.x (MNT: readd glueviz to [full] env (optional deps) on Python 3.10 following the release of glue-core 1.2.3)
  setup.cfg
Labels: enhancement, backport-yt-4.0.x

#3725 Backport PR #3721 (REL: drop overly protective version upper limits for hard dependencies)
  setup.cfg
  tests/windows_conda_requirements.txt
Labels: enhancement

#3723 BUG: fix a regression in SlicePlot and ProjectionPlot APIs
  nose_unit.cfg
  tests/tests.yaml
  yt/visualization/plot_window.py
  yt/visualization/tests/test_normal_plot_api.py
Labels: bug, api-consistency, deprecation

#3720 ENH: add unpin_requirements.py script to version control
  tests/unpin_requirements.py
Labels: enhancement, tests: running tests

#3708 BUG: restore compatibility with latest version of cartopy (0.20)
  conftest.py
  tests/cartopy_requirements.txt
  tests/ci_install.sh
  tests/windows_conda_requirements.txt
  yt/visualization/base_plot_types.py
Labels: bug, backport-yt-4.0.x

#3603 ENH: improve deprecation interface (make 'removal' version optional)
  yt/_maintenance/deprecation.py
Labels: enhancement, deprecation
