Repository yt-project/yt, pull requests merged in 2021-03, with the labels that each got.

#3046 Migration script: warn and do not migrate
  yt/config.py
Labels: enhancement, proposal, yt-4.0

#2878 code deduplication: image filename validation
  yt/funcs.py
  yt/visualization/_commons.py
  yt/visualization/base_plot_types.py
  yt/visualization/image_writer.py
  yt/visualization/plot_container.py
  yt/visualization/profile_plotter.py
  yt/visualization/tests/test_commons.py
  yt/visualization/volume_rendering/scene.py
Labels: bug, refactor

#3110 cleanup: remove dead config option
  doc/source/reference/configuration.rst
  yt/config.py
  yt/utilities/parallel_tools/parallel_analysis_interface.py
Labels: dead code

#3113 cleanup: remove seemingly unused pbar class
  yt/funcs.py
Labels: dead code

#3100 make requests a part of yt.utilities.on_demand_imports
  yt/data_objects/construction_data_containers.py
  yt/utilities/command_line.py
  yt/utilities/on_demand_imports.py
Labels: infrastructure, proposal

#3111 fix for velocity_annotation with unstructured grids
  yt/loaders.py
  yt/testing.py
  yt/visualization/plot_modifications.py
  yt/visualization/tests/test_callbacks.py
Labels: bug, code frontends, coordinates: cartesian

#2851 Expand an exception catching
  .pre-commit-config.yaml
  yt/fields/field_info_container.py
Labels: bug, refactor

#3105 Make config related paths dynamical. Fixes #3104
  yt/config.py
  yt/fields/tests/test_fields_plugins.py
  yt/funcs.py
  yt/utilities/configure.py
  yt/utilities/tests/test_config.py
Labels: bug, tests: running tests

#3121 fix a broken load_name in data sample metadata
  yt/sample_data_registry.json
Labels: bug, infrastructure

#3120 doc: fix hyperlink formatting
  CONTRIBUTING.rst
Labels: bug, docs

#3059 Make energy and momentum field names more accurate and add field deprecation mechanism
  doc/source/analyzing/fields.rst
  doc/source/developing/creating_derived_fields.rst
  doc/source/developing/deprecating_features.rst
  doc/source/yt4differences.rst
  tests/tests.yaml
  yt/data_objects/derived_quantities.py
  yt/data_objects/level_sets/clump_validators.py
  yt/data_objects/static_output.py
  yt/data_objects/tests/test_covering_grid.py
  yt/data_objects/tests/test_profiles.py
  yt/fields/astro_simulations.py
  yt/fields/derived_field.py
  yt/fields/field_aliases.py
  yt/fields/field_info_container.py
  yt/fields/fluid_fields.py
  yt/fields/geometric_fields.py
  yt/fields/magnetic_field.py
  yt/fields/particle_fields.py
  yt/fields/tests/test_magnetic_fields.py
  yt/fields/vector_operations.py
  yt/frontends/art/fields.py
  yt/frontends/artio/fields.py
  yt/frontends/athena/fields.py
  yt/frontends/athena_pp/fields.py
  yt/frontends/boxlib/fields.py
  yt/frontends/chombo/fields.py
  yt/frontends/enzo/fields.py
  yt/frontends/enzo_p/fields.py
  yt/frontends/fits/fields.py
  yt/frontends/flash/fields.py
  yt/frontends/gamer/fields.py
  yt/frontends/gdf/fields.py
  yt/frontends/gizmo/fields.py
  yt/frontends/sph/fields.py
  yt/frontends/stream/fields.py
  yt/utilities/logger.py
Labels: api-consistency, code frontends, deprecation, enhancement, yt-4.0

#3130 [bugfix] Fix recent windows failures on github actions
  yt/utilities/lib/platform_dep.h
Labels: bug

#3127 [bugfix] Various SPH fixes
  yt/frontends/arepo/data_structures.py
  yt/frontends/gadget/io.py
  yt/geometry/particle_oct_container.pyx
Labels: bug, yt-4.0

#3132 Deprecate WeightedVariance in favor of WeightedStandardDeviation
  doc/source/analyzing/objects.rst
  doc/source/cookbook/profile_with_standard_deviation.py
  yt/data_objects/data_containers.py
  yt/data_objects/derived_quantities.py
  yt/data_objects/tests/test_derived_quantities.py
Labels: api-consistency, deprecation, enhancement, yt-4.0

#3123 doc: fix missing `sampling_type` keyword argument in `add_field` examples
  doc/source/developing/creating_derived_fields.rst
  doc/source/reference/configuration.rst
  doc/source/visualizing/sketchfab.rst
Labels: bug, docs, yt-4.0

#3102 Updates to pytest infrastructure [01/NN]
  conftest.py
  nose_unit.cfg
  pyproject.toml
  pytest.ini
  tests/pytest_runner.py
  tests/test_minimal_requirements.txt
  tests/test_requirements.txt
  tests/tests.yaml
  yt/frontends/gdf/tests/conftest.py
  yt/frontends/gdf/tests/test_outputs.py
  yt/frontends/gdf/tests/test_outputs_nose.py
  yt/utilities/answer_testing/testing_utilities.py
Labels: infrastructure

#3137 cleanup: remove turbo colormap (added to matplotlib in version 3.3.0)
  yt/visualization/color_maps.py
Labels: dead code

#3139 cleanup: remove a python2-only conditional
  yt/frontends/artio/data_structures.py
Labels: code frontends, dead code

#3142 cleanup unecessary workaround in setup.py
  setup.py
Labels: dead code

#3141 cleanup a shallow and unnecessary wrapper around builtin open function
  yt/frontends/sdf/data_structures.py
Labels: dead code

#3140 use distutils instead of pkg_resource to parse version in optional deps
  yt/utilities/on_demand_imports.py
Labels: enhancement

#3143 maint: drop compatibility layers for matplotlib 1.5
  setup.py
  tests/test_minimal_requirements.txt
  yt/visualization/base_plot_types.py
  yt/visualization/plot_window.py
  yt/visualization/profile_plotter.py
  yt/visualization/tests/test_plotwindow.py
  yt/visualization/volume_rendering/transfer_function_helper.py
Labels: enhancement

#3144 maint: use matplotlib.pyplot in examples instead of matplotlib.pylab
  doc/source/cookbook/streamlines.py
  doc/source/cookbook/streamlines_isocontour.py
  doc/source/visualizing/streamlines.rst
  yt/data_objects/particle_trajectories.py
  yt/visualization/streamlines.py
Labels: docs, enhancement

#3145 doc: add a custom badge for downstream projects supported by yt
  README.md
Labels: docs

#3150 maint: pin matplotlib maximal supported version
  setup.py
  tests/test_requirements.txt
Labels: bug, tests: running tests

#2107 Adding support for active particles
  yt/frontends/enzo/data_structures.py
  yt/frontends/enzo/fields.py
  yt/frontends/enzo/io.py
Labels: enhancement

#3147 Fix field parameters not working with off axis projections
  yt/fields/tests/test_vector_fields.py
  yt/visualization/volume_rendering/render_source.py
Labels: bug

#3158 Bugfix #3155 + improvement in config handler
  yt/config.py
  yt/utilities/configuration_tree.py
Labels: bug, enhancement

#3157 rephrase comment in README to avoid pinning a specific minimal python version
  README.md
Labels: bug, docs

#3156 fix: typing for Dataset.cosmological_simulation
  yt/fields/field_detector.py
  yt/frontends/athena/data_structures.py
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/boxlib/data_structures.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/fits/data_structures.py
  yt/frontends/flash/data_structures.py
  yt/frontends/gdf/data_structures.py
  yt/frontends/moab/data_structures.py
  yt/frontends/stream/data_structures.py
Labels: bug, code frontends

#3149 cleanup: remove cubehelix colormap
  yt/visualization/color_maps.py
Labels: bug, dead code

#3115 cleanup: simplify get_pbar by removing a vestigial class that's not used anymore
  yt/funcs.py
Labels: dead code, refactor

#3152 Update filtering docs to reflect that particles should not be used with cut regions
  doc/source/analyzing/filtering.rst
  yt/data_objects/selection_objects/cut_region.py
  yt/fields/particle_fields.py
Labels: bug, docs
