Repository yt-project/yt, pull requests merged in 2021-09, with the labels that each got.

#3485 BUG: fix a broken call to warnings.warn
  yt/data_objects/construction_data_containers.py
Labels: bug

#3474 DOC: use absolute links instead of relative path for quickstart guard linking with README.md
  README.md
Labels: bug, docs

#3496 BUG: fix two bugs in yt.visualization.eps_writer
  nose_unit.cfg
  tests/tests.yaml
  yt/testing.py
  yt/visualization/eps_writer.py
  yt/visualization/tests/test_eps_writer.py
Labels: bug

#3501 BUG: fix an outdated h5py idiom in a documentation notebook
  doc/source/examining/Loading_Generic_Array_Data.ipynb
Labels: bug, docs

#3505 MNT: bump minimal required IPython version from 1.0.0 to 2.0.0
  setup.cfg
Labels: bug, blocker, infrastructure

#3515 Very minor update including a close statement in boxlib io
  yt/frontends/boxlib/io.py
Labels: enhancement

#3517 BUG: graciously fallback to a default repr for yt arrays in jupyter notebooks
  yt/data_objects/static_output.py
Labels: bug, UX

#3495 ENH: warn user in case a Dataset subclass is redefined
  nose_unit.cfg
  tests/tests.yaml
  yt/data_objects/static_output.py
  yt/data_objects/tests/test_registration.py
Labels: enhancement, UX

#3524 BUG: Fix re-allocation of octree
  yt/utilities/lib/cyoctree.pyx
Labels: bug, yt core

#3507 MNT: pin flake8 plugins
  .pre-commit-config.yaml
Labels: infrastructure, code style

#3497 ENH: correct error message for requires_backend testing decorator
  yt/testing.py
Labels: bug, enhancement, tests: running tests

#3484 MNT: update requirements for firefly-vis
  setup.cfg
Labels: infrastructure

#3475 ENH: ensure consistent usage of shebangs
  .pre-commit-config.yaml
  clean.sh
  doc/helper_scripts/run_recipes.py
  doc/source/cookbook/vol-annotated.py
  yt/utilities/lodgeit.py
  yt/visualization/tests/test_plotwindow.py
Labels: enhancement, infrastructure

#3465 BUG: fix error message in lookup_on_disk_data
  yt/sample_data/api.py
Labels: bug, UX

#3333 Remove unused RAMSES dataset
  yt/sample_data_registry.json
Labels: bug

#3065 make Scene.save less verbose
  yt/visualization/volume_rendering/scene.py
  yt/visualization/volume_rendering/tests/test_scene.py
Labels: enhancement, tests: running tests

#3532 BUG: fix incorrect default axis labels in 'r' oriented slice plots for spherical data
  yt/geometry/coordinates/spherical_coordinates.py
Labels: bug, viz: 2D, coordinates: non-cartesian
