Repository yt-project/yt, pull requests merged in 2021-01, with the labels that each got.

#3018 [BUGFIX] RAMSES: Fix creation of photon flux
  yt/frontends/ramses/fields.py
  yt/frontends/ramses/tests/test_outputs.py
Labels: bug, code frontends

#3019 [BUGFIX] Fix figure width in HTML output
  yt/visualization/plot_container.py
  yt/visualization/profile_plotter.py
Labels: bug

#2928 More flexible RAMSES loader
  yt/frontends/ramses/data_structures.py
  yt/frontends/ramses/definitions.py
  yt/frontends/ramses/tests/test_outputs.py
Labels: code frontends, domain: astro, enhancement

#3017 [BUGFIX] Fix erroneous warning thrown when loading Ramses dataset
  yt/frontends/ramses/field_handlers.py
Labels: bug, code frontends

#3020 fix: align code base with pre-commit hooks
  conftest.py
  tests/nose_runner.py
  tests/test_install_script.py
Labels: bug, code style, infrastructure

#3016 Fix fragile imports
  .git-blame-ignore-revs
  .pre-commit-config.yaml
  pyproject.toml
  yt/__init__.py
  yt/data_objects/selection_objects/data_selection_objects.py
  yt/data_objects/selection_objects/point.py
  yt/data_objects/selection_objects/ray.py
  yt/data_objects/selection_objects/region.py
  yt/data_objects/selection_objects/spheroids.py
  yt/fields/tests/test_fields_plugins.py
  yt/frontends/amrvac/fields.py
  yt/utilities/grid_data_format/writer.py
Labels: backwards incompatible, code style, infrastructure

#2956 Particle trajectories minor improvements
  yt/data_objects/particle_trajectories.py
Labels: enhancement

#3022 [bugfix] Prevent v1.3.1 of cftime (upstream dep)
  tests/test_requirements.txt
Labels: bug

#3024 Revert cftime pinning
  tests/test_requirements.txt
Labels: infrastructure

#3013 pre-commit ci adoption: docs
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/slash-command-dispatch.yml
  .github/workflows/style-checks.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  tests/lint_requirements.txt
Labels: docs

#2848 hotfix: register "vertex" fields only in unstructured meshes
  yt/fields/field_info_container.py
  yt/fields/tests/test_field_name_container.py
Labels: bug, index: unstructured mesh

#2868 A path forward for the long-standing periodicity-hack
  doc/source/cookbook/hse_field.py
  doc/source/cookbook/render_two_fields.py
  yt/data_objects/static_output.py
  yt/data_objects/tests/test_covering_grid.py
  yt/fields/field_detector.py
  yt/frontends/adaptahop/data_structures.py
  yt/frontends/ahf/data_structures.py
  yt/frontends/amrvac/data_structures.py
  yt/frontends/art/data_structures.py
  yt/frontends/artio/data_structures.py
  yt/frontends/athena/data_structures.py
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/boxlib/data_structures.py
  yt/frontends/chombo/data_structures.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/enzo_p/data_structures.py
  yt/frontends/exodus_ii/data_structures.py
  yt/frontends/fits/data_structures.py
  yt/frontends/flash/data_structures.py
  yt/frontends/gadget/data_structures.py
  yt/frontends/gadget_fof/data_structures.py
  yt/frontends/gamer/data_structures.py
  yt/frontends/gdf/data_structures.py
  yt/frontends/halo_catalog/data_structures.py
  yt/frontends/http_stream/data_structures.py
  yt/frontends/nc4_cm1/data_structures.py
  yt/frontends/open_pmd/data_structures.py
  yt/frontends/owls_subfind/data_structures.py
  yt/frontends/ramses/data_structures.py
  yt/frontends/rockstar/data_structures.py
  yt/frontends/sdf/data_structures.py
  yt/frontends/stream/data_structures.py
  yt/frontends/swift/data_structures.py
  yt/frontends/tipsy/data_structures.py
  yt/frontends/ytdata/data_structures.py
  yt/geometry/_selection_routines/region_selector.pxi
Labels: proposal, refactor

#3027 doc: renaming of the master branch
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/rules-checks.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  README.md
  doc/install_script.sh
  doc/source/about/index.rst
  doc/source/developing/releasing.rst
  doc/source/installing.rst
  doc/source/reference/changelog.rst
  doc/source/visualizing/unstructured_mesh_rendering.rst
  yt/funcs.py
Labels: docs, infrastructure

#3007 maint: remove deprecated stuff
  benchmarks/asv.conf.json
  benchmarks/benchmarks/__init__.py
  benchmarks/benchmarks/benchmarks.py
  benchmarks/benchmarks/data_objects.py
  benchmarks/benchmarks/large_tipsy.py
  benchmarks/benchmarks/small_enzo.py
  benchmarks/benchmarks/small_flash.py
  benchmarks/benchmarks/small_gadget.py
  benchmarks/benchmarks/small_ramses.py
  doc/get_yt.sh
  doc/source/developing/deprecating_features.rst
  doc/source/examining/loading_data.rst
  doc/source/reference/api/api.rst
  yt/__init__.py
  yt/_maintenance/deprecation.py
  yt/data_objects/index_subobjects/octree_subset.py
  yt/data_objects/level_sets/api.py
  yt/data_objects/level_sets/clump_handling.py
  yt/data_objects/profiles.py
  yt/data_objects/selection_objects/cut_region.py
  yt/data_objects/selection_objects/slices.py
  yt/data_objects/static_output.py
  yt/data_objects/time_series.py
  yt/fields/derived_field.py
  yt/fields/field_info_container.py
  yt/fields/particle_fields.py
  yt/fields/species_fields.py
  yt/frontends/athena/data_structures.py
  yt/frontends/athena/tests/test_outputs.py
  yt/frontends/fits/data_structures.py
  yt/frontends/fits/misc.py
  yt/frontends/ramses/fields.py
  yt/frontends/tipsy/data_structures.py
  yt/funcs.py
  yt/loaders.py
  yt/utilities/amr_kdtree/amr_kdtree.py
  yt/utilities/answer_testing/framework.py
  yt/utilities/cosmology.py
  yt/utilities/exceptions.py
  yt/utilities/fits_image.py
  yt/utilities/grid_data_format/writer.py
  yt/utilities/particle_generator.py
  yt/visualization/api.py
  yt/visualization/color_maps.py
  yt/visualization/eps_writer.py
  yt/visualization/fits_image.py
  yt/visualization/fixed_resolution.py
  yt/visualization/image_writer.py
  yt/visualization/plot_container.py
  yt/visualization/plot_window.py
  yt/visualization/volume_rendering/transfer_function_helper.py
Labels: deprecation, infrastructure, yt-4.0

#2658 Make CHUNKSIZE into an index property
  yt/frontends/flash/io.py
  yt/frontends/sdf/io.py
  yt/frontends/tipsy/io.py
  yt/geometry/particle_geometry_handler.py
Labels: bug, index: particle

#3030 switch internal instances of collections.OrderedDict to regular dict
  doc/source/cookbook/simulation_analysis.py
  yt/data_objects/particle_trajectories.py
  yt/data_objects/profiles.py
Labels: refactor

#3034 fix spacing in deprecation messages
  yt/_maintenance/deprecation.py
Labels: bug, deprecation

#3035 Add possibility to silence some warnings
  yt/__init__.py
  yt/_maintenance/deprecation.py
  yt/config.py
  yt/data_objects/index_subobjects/octree_subset.py
  yt/data_objects/static_output.py
  yt/data_objects/time_series.py
  yt/fields/field_info_container.py
  yt/fields/particle_fields.py
  yt/fields/species_fields.py
  yt/loaders.py
  yt/utilities/amr_kdtree/amr_kdtree.py
  yt/utilities/answer_testing/framework.py
  yt/utilities/exceptions.py
  yt/visualization/color_maps.py
  yt/visualization/eps_writer.py
  yt/visualization/image_writer.py
  yt/visualization/plot_container.py
  yt/visualization/plot_window.py
Labels: enhancement, new feature

#3040 Revert "Add possibility to silence some warnings"
  yt/__init__.py
  yt/_maintenance/deprecation.py
  yt/config.py
  yt/data_objects/index_subobjects/octree_subset.py
  yt/data_objects/static_output.py
  yt/data_objects/time_series.py
  yt/fields/field_info_container.py
  yt/fields/particle_fields.py
  yt/fields/species_fields.py
  yt/loaders.py
  yt/utilities/amr_kdtree/amr_kdtree.py
  yt/utilities/answer_testing/framework.py
  yt/utilities/exceptions.py
  yt/visualization/color_maps.py
  yt/visualization/eps_writer.py
  yt/visualization/image_writer.py
  yt/visualization/plot_container.py
  yt/visualization/plot_window.py
Labels: bug

#3041 Set _periodicity to avoid deprecated setter.
  yt/frontends/ytdata/data_structures.py
Labels: bug, deprecation

#3042 Add aliases for ionization and dissociation fields.
  yt/frontends/enzo/fields.py
Labels: enhancement

#3043 Update is_root and only_on_root functions.
  yt/funcs.py
Labels: bug

#3032 docs: apply black format
  .git-blame-ignore-revs
  .pre-commit-config.yaml
  doc/source/analyzing/domain_analysis/clump_finding.rst
  doc/source/analyzing/domain_analysis/cosmology_calculator.rst
  doc/source/analyzing/fields.rst
  doc/source/analyzing/filtering.rst
  doc/source/analyzing/generating_processed_data.rst
  doc/source/analyzing/objects.rst
  doc/source/analyzing/parallel_computation.rst
  doc/source/analyzing/saving_data.rst
  doc/source/analyzing/time_series_analysis.rst
  doc/source/developing/creating_derived_fields.rst
  doc/source/developing/creating_derived_quantities.rst
  doc/source/developing/creating_frontend.rst
  doc/source/developing/external_analysis.rst
  doc/source/developing/testing.rst
  doc/source/examining/loading_data.rst
  doc/source/examining/low_level_inspection.rst
  doc/source/faq/index.rst
  doc/source/reference/configuration.rst
  doc/source/visualizing/callbacks.rst
  doc/source/visualizing/colormaps/index.rst
  doc/source/visualizing/geographic_projections_and_transforms.rst
  doc/source/visualizing/interactive_data_visualization.rst
  doc/source/visualizing/plots.rst
  doc/source/visualizing/sketchfab.rst
  doc/source/visualizing/streamlines.rst
  doc/source/visualizing/unstructured_mesh_rendering.rst
  doc/source/visualizing/visualizing_particle_datasets_with_firefly.rst
  doc/source/yt4differences.rst
  yt/funcs.py
Labels: bug, code style, docs, infrastructure, proposal
