Repository yt-project/yt, pull requests merged in 2021-08, with the labels that each got.

#3348 make CoordinateHandler an abstract class
  yt/geometry/coordinates/coordinate_handler.py
  yt/geometry/coordinates/cylindrical_coordinates.py
  yt/geometry/coordinates/geographic_coordinates.py
  yt/geometry/coordinates/spherical_coordinates.py
Labels: UX, refactor

#3462 DOC: fix two mistakes in installing.rst
  doc/source/installing.rst
Labels: bug, docs

#3468 Add support for global_startindex != 0 to covering_grid
  yt/data_objects/construction_data_containers.py
  yt/data_objects/static_output.py
  yt/frontends/boxlib/data_structures.py
Labels: bug, enhancement, code frontends

#3463 Changed _project_coords to create new array instead of modifying in-place
  nose_unit.cfg
  tests/tests.yaml
  yt/visualization/plot_modifications.py
  yt/visualization/tests/test_line_annotation_unit.py
Labels: bug

#3470 Don't get domain dimensions from cparam file for Boxlib frontend.
  yt/frontends/boxlib/data_structures.py
  yt/frontends/boxlib/definitions.py
Labels: bug, code frontends

#3482 MNT: set upper limit to firefly-vis version in [full] target as a workaround a backward incompatibility breakage
  setup.cfg
Labels: bug, blocker, infrastructure

#3483 MNT: add button to manually run bleeding edge CI job
  .github/workflows/bleeding-edge.yaml
Labels: infrastructure

#3107 parallelize index calculations
  yt/geometry/particle_geometry_handler.py
  yt/utilities/lib/ewah_bool_wrap.pyx
Labels: enhancement, index: particle

#3424 implement AthenaDataset._is_valid
  yt/frontends/athena/data_structures.py
Labels: bug, tests: running tests

#3488 [bugfix] Get order of axes right for FITSParticleProjection
  yt/visualization/fits_image.py
Labels: bug, viz: 2D

#3490 ENH: loosen header matching for Athena vtk files to allow compatibility with single variable 'vtk outputs'
  yt/frontends/athena/data_structures.py
Labels: bug, code frontends

#3480 BUG: fix mpl data path handling for Windows
  yt/visualization/plot_container.py
Labels: bug

#3131 Update Docs for Pytest
  doc/source/conf.py
  doc/source/developing/testing.rst
Labels: docs, pytest
