Repository yt-project/yt, pull requests merged in 2021-05, with the labels that each got.

#3206 Apply `pre-commit` on doc - fix invalid Python in docs
  doc/source/analyzing/generating_processed_data.rst
  doc/source/analyzing/parallel_computation.rst
  doc/source/developing/creating_derived_fields.rst
  doc/source/developing/external_analysis.rst
  doc/source/developing/testing.rst
  doc/source/examining/loading_data.rst
  doc/source/visualizing/callbacks.rst
  doc/source/visualizing/colormaps/index.rst
  doc/source/visualizing/manual_plotting.rst
  doc/source/visualizing/plots.rst
  doc/source/visualizing/sketchfab.rst
  doc/source/visualizing/streamlines.rst
  doc/source/visualizing/unstructured_mesh_rendering.rst
  doc/source/visualizing/volume_rendering.rst
  doc/source/yt4differences.rst
Labels: bug, code style, docs, enhancement

#3232 Filling out the yt4 diffs docs page
  doc/source/analyzing/fields.rst
  doc/source/reference/field_list.rst
  doc/source/yt4differences.rst
Labels: docs

#3257 CI: hotfix failing answer tests
  setup.cfg
  tests/test_requirements.txt
Labels: blocker, bug

#3264 Small doc fixes
  doc/source/analyzing/fields.rst
  doc/source/examining/loading_data.rst
Labels: docs

#3267 Fix docs barticks
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  doc/source/analyzing/domain_analysis/clump_finding.rst
  doc/source/analyzing/domain_analysis/cosmology_calculator.rst
  doc/source/analyzing/domain_analysis/index.rst
  doc/source/analyzing/fields.rst
  doc/source/analyzing/filtering.rst
  doc/source/analyzing/generating_processed_data.rst
  doc/source/analyzing/objects.rst
  doc/source/analyzing/units.rst
  doc/source/cookbook/complex_plots.rst
  doc/source/examining/loading_data.rst
  doc/source/installing.rst
  doc/source/reference/changelog.rst
  doc/source/reference/configuration.rst
  doc/source/visualizing/geographic_projections_and_transforms.rst
  doc/source/visualizing/plots.rst
  doc/source/visualizing/unstructured_mesh_rendering.rst
  doc/source/visualizing/volume_rendering.rst
  doc/source/yt3differences.rst
Labels: docs

#3184 Suggest fixes to typos
  nose_unit.cfg
  tests/tests.yaml
  yt/fields/tests/test_field_access_pytest.py
  yt/funcs.py
  yt/tests/test_funcs.py
  yt/utilities/exceptions.py
Labels: UX, enhancement

#3265 Accounting for AREPO datasets to be correctly identified.
  yt/frontends/arepo/data_structures.py
Labels: bug, code frontends

#3263 Load sample err
  doc/source/yt4differences.rst
  yt/loaders.py
Labels: UX, bug

#3248 Adds current_cycle attribute to EnzoP Dataset object
  yt/frontends/enzo_p/data_structures.py
Labels: code frontends, enhancement

#3243 remove an unused duplicated module
  yt/utilities/answer_testing/answer_tests.py
  yt/utilities/answer_testing/utils.py
Labels: dead code, pytest

#3242 maint: cleanup usage and mentions of deprecated material
  doc/source/analyzing/fields.rst
  doc/source/analyzing/time_series_analysis.rst
  doc/source/cookbook/time_series_profiles.py
  doc/source/visualizing/callbacks.rst
  doc/source/visualizing/plots.rst
  tests/tests.yaml
  yt/utilities/amr_kdtree/amr_kdtree.py
  yt/visualization/plot_window.py
  yt/visualization/tests/test_plotwindow.py
Labels: deprecation, docs

#3225 cleanup pylab-based code (switch to matplotlib.pyplot)
  yt/data_objects/construction_data_containers.py
  yt/geometry/geometry_handler.py
  yt/visualization/streamlines.py
  yt/visualization/volume_rendering/image_handling.py
  yt/visualization/volume_rendering/old_camera.py
  yt/visualization/volume_rendering/transfer_functions.py
Labels: enhancement

#3222 code deduplication, reuse lookup_on_disk_data in load_simulation
  yt/loaders.py
Labels: enhancement

#3275 Set current time off redshift if time attribute missing from data.
  yt/data_objects/static_output.py
  yt/frontends/owls_subfind/data_structures.py
Labels: bug, code frontends

#3273 Converting Enzo-P to Enzo-E
  doc/source/examining/loading_data.rst
  doc/source/reference/changelog.rst
  tests/tests.yaml
  yt/frontends/api.py
  yt/frontends/enzo_e/__init__.py
  yt/frontends/enzo_e/api.py
  yt/frontends/enzo_e/data_structures.py
  yt/frontends/enzo_e/definitions.py
  yt/frontends/enzo_e/fields.py
  yt/frontends/enzo_e/io.py
  yt/frontends/enzo_e/misc.py
  yt/frontends/enzo_e/tests/__init__.py
  yt/frontends/enzo_e/tests/test_misc.py
  yt/frontends/enzo_e/tests/test_outputs.py
  yt/frontends/enzo_p/api.py
Labels: backwards incompatible, code frontends, docs

#3180 fix: don't copy unit registry if it is already the same thing
  yt/data_objects/construction_data_containers.py
Labels: enhancement, performance

#3258 New fields for Arepo and Gadget frontends
  doc/source/examining/loading_data.rst
  tests/tests.yaml
  yt/frontends/arepo/fields.py
  yt/frontends/gadget/definitions.py
  yt/frontends/gadget/fields.py
  yt/frontends/gadget/io.py
  yt/frontends/gadget/tests/test_outputs.py
  yt/frontends/sph/fields.py
  yt/sample_data_registry.json
  yt/utilities/answer_testing/framework.py
Labels: code frontends, new feature

#3272 Implement CIC deposition for ParticleProjectionPlot, add FITSParticleProjection, fix bugs
  doc/source/visualizing/FITSImageData.ipynb
  doc/source/visualizing/plots.rst
  tests/tests.yaml
  yt/__init__.py
  yt/data_objects/profiles.py
  yt/utilities/lib/image_utilities.pyx
  yt/utilities/lib/particle_mesh_operations.pyx
  yt/visualization/api.py
  yt/visualization/fits_image.py
  yt/visualization/fixed_resolution.py
  yt/visualization/particle_plots.py
  yt/visualization/tests/test_fits_image.py
  yt/visualization/tests/test_particle_plot.py
Labels: bug, enhancement

#3277 load_sample: add a clear error message for datasets missing website registration
  yt/loaders.py
Labels: UX, bug

#3290 Remove warning labels on Enzo-E frontend.
  doc/source/examining/loading_data.rst
  yt/frontends/enzo_e/data_structures.py
Labels: code frontends, dead code

#3284 Updating cookbook recipes and notebooks to reflect yt4 changes
  doc/source/analyzing/domain_analysis/XrayEmissionFields.ipynb
  doc/source/cookbook/annotate_timestamp_and_scale.py
  doc/source/cookbook/annotations.py
  doc/source/cookbook/average_value.py
  doc/source/cookbook/changing_label_formats.py
  doc/source/cookbook/colormaps.py
  doc/source/cookbook/contours_on_slice.py
  doc/source/cookbook/custom_colorbar_tickmarks.ipynb
  doc/source/cookbook/derived_field.py
  doc/source/cookbook/downsampling_amr.py
  doc/source/cookbook/fits_radio_cubes.ipynb
  doc/source/cookbook/fits_xray_images.ipynb
  doc/source/cookbook/matplotlib-animation.py
  doc/source/cookbook/multi_plot_3x2_FRB.py
  doc/source/cookbook/multi_width_image.py
  doc/source/cookbook/multiplot_2x2.py
  doc/source/cookbook/multiplot_2x2_coordaxes_slice.py
  doc/source/cookbook/multiplot_2x2_time_series.py
  doc/source/cookbook/multiplot_export_to_mpl.py
  doc/source/cookbook/multiplot_phaseplot.py
  doc/source/cookbook/opengl_ipython.py
  doc/source/cookbook/overplot_grids.py
  doc/source/cookbook/overplot_particles.py
  doc/source/cookbook/radial_profile_styles.py
  doc/source/cookbook/simple_contour_in_slice.py
  doc/source/cookbook/simple_pdf.py
  doc/source/cookbook/simple_projection.py
  doc/source/cookbook/simple_slice.py
  doc/source/cookbook/simple_slice_matplotlib_example.py
  doc/source/cookbook/simple_slice_with_multiple_fields.py
  doc/source/cookbook/streamlines.py
  doc/source/cookbook/tipsy_and_yt.ipynb
  doc/source/cookbook/velocity_vectors_on_slice.py
  doc/source/cookbook/yt_gadget_owls_analysis.ipynb
  doc/source/cookbook/zoomin_frames.py
  doc/source/examining/loading_data.rst
  doc/source/visualizing/TransferFunctionHelper_Tutorial.ipynb
  doc/source/visualizing/Volume_Rendering_Tutorial.ipynb
  doc/source/yt4differences.rst
  yt/frontends/fits/misc.py
Labels: docs, yt-4.0

#3298 Pin proj to 7.x per SciTools/cartopy#1140
  tests/ci_install.sh
Labels: bug, infrastructure

#3291 Make Arepo units play nice with unit_base
  yt/frontends/arepo/data_structures.py
Labels: bug, code frontends, yt-4.0

#3289 Restore auto creation of save dirs in PlotContainer.save
  nose_unit.cfg
  tests/tests.yaml
  yt/visualization/plot_container.py
  yt/visualization/tests/test_save.py
Labels: bug

#3288 Refactoring "default" species fields
  doc/source/analyzing/fields.rst
  doc/source/cookbook/time_series.py
  yt/data_objects/static_output.py
  yt/fields/fluid_fields.py
  yt/fields/species_fields.py
  yt/fields/tests/test_species_fields.py
  yt/fields/tests/test_xray_fields.py
  yt/frontends/_skeleton/data_structures.py
  yt/frontends/amrvac/data_structures.py
  yt/frontends/arepo/data_structures.py
  yt/frontends/art/data_structures.py
  yt/frontends/artio/data_structures.py
  yt/frontends/athena/data_structures.py
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/boxlib/data_structures.py
  yt/frontends/chombo/data_structures.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/enzo_e/data_structures.py
  yt/frontends/flash/data_structures.py
  yt/frontends/gadget/data_structures.py
  yt/frontends/gamer/data_structures.py
  yt/frontends/gdf/data_structures.py
  yt/frontends/ramses/data_structures.py
  yt/frontends/ramses/fields.py
  yt/frontends/sph/data_structures.py
  yt/frontends/stream/data_structures.py
  yt/frontends/swift/data_structures.py
  yt/frontends/tipsy/data_structures.py
  yt/loaders.py
  yt/testing.py
  yt/utilities/chemical_formulas.py
  yt/utilities/tests/test_chemical_formulas.py
Labels: backwards incompatible, code frontends, domain: astro, enhancement, refactor, yt-4.0

#3293 Write demeshening description. Fixes #2629.
  doc/source/examining/loading_data.rst
  doc/source/reference/_images/yt3_p0010_proj_density_None_x_z002.png
  doc/source/reference/_images/yt4_p0010_proj_density_None_x_z002.png
  doc/source/reference/demeshening.rst
Labels: demeshening, docs, yt-4.0

#3306 Update quickstart
  doc/source/quickstart/3)_Simple_Visualization.ipynb
  doc/source/quickstart/4)_Data_Objects_and_Time_Series.ipynb
  doc/source/quickstart/5)_Derived_Fields_and_Profiles.ipynb
Labels: bug, docs, yt-4.0

#3033 Special relativistic fields for GAMER
  doc/source/examining/loading_data.rst
  tests/tests.yaml
  yt/fields/astro_fields.py
  yt/frontends/gamer/data_structures.py
  yt/frontends/gamer/fields.py
  yt/frontends/gamer/tests/test_outputs.py
  yt/sample_data_registry.json
Labels: blocker, code frontends, enhancement

#3294 test: revert PR 3068. Reactivate a randomly failing answer test
  yt/visualization/volume_rendering/tests/test_vr_orientation.py
Labels: bug, tests: running tests, yt-4.0

#3305 Document particle visualization workarounds
  doc/source/analyzing/fields.rst
  doc/source/examining/loading_data.rst
  doc/source/reference/api/api.rst
  doc/source/visualizing/plots.rst
Labels: blocker, docs, yt-4.0

#3262 multiple fixes for load_sample
  doc/source/quickstart/3)_Simple_Visualization.ipynb
  yt/loaders.py
  yt/sample_data/api.py
  yt/sample_data_registry.json
  yt/tests/test_load_sample.py
Labels: blocker, bug, yt-4.0

#3302 Adding notes about particle deposit fields.
  doc/source/analyzing/fields.rst
  doc/source/analyzing/objects.rst
Labels: blocker, docs, yt-4.0

#3274 Support for enzop vlct
  yt/frontends/enzo_e/fields.py
  yt/frontends/enzo_e/io.py
  yt/frontends/enzo_e/tests/test_outputs.py
  yt/sample_data_registry.json
Labels: code frontends, enhancement

#3310 Update docstrings to be consistent with function signature
  yt/frontends/ramses/field_handlers.py
  yt/frontends/ramses/hilbert.py
  yt/funcs.py
  yt/loaders.py
  yt/utilities/lib/octree_raytracing.py
  yt/utilities/parallel_tools/parallel_analysis_interface.py
  yt/visualization/color_maps.py
  yt/visualization/fits_image.py
  yt/visualization/fixed_resolution.py
  yt/visualization/line_plot.py
  yt/visualization/plot_window.py
  yt/visualization/profile_plotter.py
  yt/visualization/streamlines.py
  yt/visualization/volume_rendering/camera.py
  yt/visualization/volume_rendering/camera_path.py
  yt/visualization/volume_rendering/old_camera.py
  yt/visualization/volume_rendering/render_source.py
  yt/visualization/volume_rendering/scene.py
  yt/visualization/volume_rendering/transfer_function_helper.py
Labels: api-consistency, bug, docs, yt-4.0
