Repository yt-project/yt, pull requests merged in 2021-04, with the labels that each got.

#3124 making ParticleContainers pickleable
  yt/data_objects/data_containers.py
  yt/data_objects/index_subobjects/particle_container.py
  yt/data_objects/static_output.py
  yt/data_objects/tests/test_pickling.py
  yt/geometry/particle_geometry_handler.py
Labels: bug, enhancement, index: particle

#3148 add pandas to yt.utilities.on_demand_imports
  yt/data_objects/data_containers.py
  yt/data_objects/profiles.py
  yt/utilities/on_demand_imports.py
Labels: api-consistency, enhancement

#3138 cleanup: remove yt.funcs.get_requests, use yt.utilities.on_demand_imports
  yt/frontends/http_stream/data_structures.py
  yt/frontends/http_stream/io.py
  yt/frontends/sdf/data_structures.py
  yt/funcs.py
Labels: dead code

#3160 [bugfix] Fix units of potential
  yt/frontends/ramses/field_handlers.py
  yt/frontends/ramses/fields.py
  yt/frontends/ramses/tests/test_outputs.py
Labels: bug, code frontends

#3134 remove false api docstrings in frontends
  yt/frontends/_skeleton/__init__.py
  yt/frontends/ahf/__init__.py
  yt/frontends/art/__init__.py
  yt/frontends/artio/__init__.py
  yt/frontends/boxlib/__init__.py
  yt/frontends/exodus_ii/__init__.py
  yt/frontends/flash/__init__.py
  yt/frontends/gamer/__init__.py
  yt/frontends/nc4_cm1/__init__.py
  yt/frontends/open_pmd/__init__.py
  yt/frontends/ramses/__init__.py
  yt/frontends/sph/__init__.py
Labels: code frontends, dead code, question

#1931 Per field config
  doc/source/reference/configuration.rst
  yt/funcs.py
  yt/visualization/eps_writer.py
  yt/visualization/plot_container.py
  yt/visualization/plot_window.py
  yt/visualization/profile_plotter.py
  yt/visualization/tests/test_callbacks.py
  yt/visualization/tests/test_plotwindow.py
Labels: enhancement, proposal, yt-4.0

#3163 remove mccabe from linting specs (already a direct dependency of flake8)
  .pre-commit-config.yaml
Labels: dead code, infrastructure

#3154 rewrite load tests with the pytest framework
  nose_unit.cfg
  tests/tests.yaml
  yt/tests/test_load_errors.py
Labels: infrastructure, pytest, refactor, tests: running tests

#3159 add a pytest-compatible version of requires_module
  yt/testing.py
Labels: infrastructure, pytest, refactor

#3161 [bugfix] Fix log plots when using matplotilb 3.3.x if there are zeros in the plot
  yt/visualization/plot_window.py
Labels: bug

#3168 update API docs for missing/moved classes
  doc/source/reference/api/api.rst
Labels: docs

#3169 fix a broken import statement in requires_module_pytest
  yt/testing.py
Labels: bug, pytest, tests: running tests

#3171 [bugfix] Fix issues with FITS images
  yt/visualization/fits_image.py
  yt/visualization/tests/test_fits_image.py
Labels: bug

#3061 exp: remove unused module pmods
  yt/pmods.py
Labels: dead code

#3166 [bugfix] Fix field calculation for octrees
  yt/fields/vector_operations.py
Labels: bug

#2728 [bugfix] ensure correct axis units when unit_system=code
  yt/data_objects/static_output.py
  yt/units/unit_systems.py
  yt/visualization/plot_modifications.py
  yt/visualization/plot_window.py
  yt/visualization/tests/test_plot_modifications.py
Labels: bug

#3173 Fix some numpy deprecation warnings
  yt/data_objects/construction_data_containers.py
  yt/data_objects/tests/test_points.py
  yt/frontends/exodus_ii/data_structures.py
  yt/frontends/tipsy/io.py
  yt/geometry/_selection_routines/data_collection_selector.pxi
  yt/testing.py
  yt/utilities/answer_testing/framework.py
  yt/utilities/particle_generator.py
  yt/utilities/sdf.py
  yt/visualization/eps_writer.py
Labels: bug

#3176 Hotfix image filename validation
  nose_unit.cfg
  tests/tests.yaml
  yt/visualization/_commons.py
  yt/visualization/tests/test_commons.py
Labels: api-consistency, bug

#3175 supporting MPL 3.4 : stop registering colormaps from cmocean
  doc/source/visualizing/colormaps/index.rst
  yt/visualization/color_maps.py
Labels: backwards incompatible, bug

#3182 hotfix: remove fragile assert statement in a massive test
  yt/tests/test_load_sample.py
Labels: bug, pytest, tests: running tests

#3181 Fix and clean strings
  conftest.py
  setupext.py
  tests/report_failed_answers.py
  yt/analysis_modules/spectral_integrator/api.py
  yt/data_objects/construction_data_containers.py
  yt/data_objects/data_containers.py
  yt/data_objects/profiles.py
  yt/data_objects/selection_objects/data_selection_objects.py
  yt/data_objects/static_output.py
  yt/data_objects/tests/test_disks.py
  yt/data_objects/tests/test_image_array.py
  yt/fields/derived_field.py
  yt/fields/xray_emission_fields.py
  yt/frontends/art/io.py
  yt/frontends/boxlib/data_structures.py
  yt/frontends/enzo/simulation_handling.py
  yt/frontends/enzo_p/tests/test_misc.py
  yt/frontends/moab/data_structures.py
  yt/frontends/open_pmd/data_structures.py
  yt/frontends/owls/fields.py
  yt/frontends/ramses/field_handlers.py
  yt/geometry/coordinates/cartesian_coordinates.py
  yt/utilities/command_line.py
  yt/utilities/exceptions.py
  yt/utilities/file_handler.py
  yt/utilities/lib/cykdtree/tests/__init__.py
  yt/utilities/lodgeit.py
  yt/visualization/fits_image.py
  yt/visualization/plot_modifications.py
  yt/visualization/plot_window.py
  yt/visualization/profile_plotter.py
  yt/visualization/tests/test_image_writer.py
  yt/visualization/volume_rendering/render_source.py
Labels: bug, code style, enhancement

#3187 Allow `brew` to update to fix hdf5 installation issues
  tests/ci_install.sh
Labels: blocker, bug, infrastructure

#3196 Fix `print_stats` function for RAMSES datasets.
  yt/frontends/ramses/data_structures.py
  yt/frontends/ramses/tests/test_outputs.py
Labels: bug, code frontends

#3195 hotfix: yt.load_sample + yt_data_dir unset
  yt/loaders.py
Labels: bug

#3203 fix: correct more-itertools package name
  setup.py
  tests/test_minimal_requirements.txt
  tests/test_requirements.txt
Labels: bug, infrastructure

#3116 Update pbars for off-by-one
  yt/data_objects/level_sets/contour_finder.py
  yt/data_objects/particle_trajectories.py
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/enzo_p/data_structures.py
  yt/geometry/particle_geometry_handler.py
  yt/geometry/particle_oct_container.pyx
  yt/utilities/answer_testing/framework.py
  yt/utilities/particle_generator.py
  yt/visualization/streamlines.py
Labels: bug

#3212 fix a bug where set_background_color wouldn't work with colormaps from third party libs
  yt/visualization/plot_container.py
Labels: bug

#3215 fix: add temperature to known fields list for AMRVAC
  yt/frontends/amrvac/fields.py
Labels: bug, code frontends

#3214 add a visible deprecation warning for unprefixed cmocean maps
  yt/visualization/plot_container.py
Labels: infrastructure

#3207 Adding note in docs about cmocean cmap changes.
  doc/source/yt4differences.rst
Labels: docs, yt-4.0

#3193 Use io._vector_fields to get a field shape. Fixes #3191
  yt/fields/field_detector.py
  yt/frontends/gadget/io.py
Labels: refactor

#2400 [yt-4.0] new depth-first octree
  .gitignore
  doc/source/yt4differences.rst
  yt/data_objects/construction_data_containers.py
  yt/data_objects/tests/test_octree.py
  yt/frontends/sph/data_structures.py
  yt/utilities/lib/cyoctree.pyx
Labels: demeshening, new feature, yt-4.0

#3217 implement a more useful __repr__ for the base Dataset class
  yt/data_objects/static_output.py
  yt/frontends/art/data_structures.py
  yt/frontends/athena/data_structures.py
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/enzo_p/data_structures.py
  yt/frontends/gadget/data_structures.py
  yt/frontends/gadget_fof/data_structures.py
  yt/frontends/gdf/data_structures.py
  yt/frontends/halo_catalog/data_structures.py
  yt/frontends/http_stream/data_structures.py
  yt/frontends/moab/data_structures.py
  yt/frontends/open_pmd/data_structures.py
  yt/frontends/ramses/data_structures.py
  yt/frontends/tipsy/data_structures.py
Labels: enhancement

#3219 remove a log warning that cannot be acted upon
  yt/fields/fluid_fields.py
Labels: enhancement

#3204 Upading cut_region docs and use tuples everywhere - fixes #3201
  doc/source/analyzing/filtering.rst
  yt/data_objects/selection_objects/cut_region.py
  yt/data_objects/selection_objects/data_selection_objects.py
  yt/data_objects/tests/test_clone.py
  yt/data_objects/tests/test_covering_grid.py
  yt/data_objects/tests/test_extract_regions.py
  yt/frontends/adaptahop/data_structures.py
  yt/geometry/oct_geometry_handler.py
  yt/visualization/tests/test_offaxisprojection.py
Labels: code style, docs

#3224 cleanup some deprecated field names
  doc/source/cookbook/customized_phase_plot.py
  doc/source/cookbook/customized_profile_plot.py
  yt/data_objects/tests/test_spheres.py
  yt/fields/field_aliases.py
Labels: api-consistency, enhancement

#2967 Throw an error if field accesses is ambiguous.
  nose_unit.cfg
  tests/tests.yaml
  yt/_maintenance/deprecation.py
  yt/data_objects/static_output.py
  yt/fields/field_info_container.py
  yt/fields/tests/test_ambiguous_fields.py
Labels: api-consistency, backwards incompatible, bug, yt-4.0

#3205 DOC: Misc numpydoc syntax fixing.
  yt/_maintenance/deprecation.py
  yt/data_objects/construction_data_containers.py
  yt/data_objects/data_containers.py
  yt/data_objects/image_array.py
  yt/data_objects/particle_filters.py
  yt/data_objects/profiles.py
  yt/data_objects/selection_objects/data_selection_objects.py
  yt/data_objects/static_output.py
  yt/data_objects/time_series.py
  yt/fields/field_info_container.py
Labels: docs, enhancement

#3221 fix a deprecation warning where unyt_array instances would be constructed from 'ragged' arrays
  yt/data_objects/derived_quantities.py
Labels: bug

#3234 Fix gizmo frontend
  yt/frontends/gizmo/data_structures.py
  yt/frontends/gizmo/fields.py
Labels: bug, code frontends, yt-4.0

#3078 Migrate metadata from setup.py to setup.cfg
  .pre-commit-config.yaml
  setup.cfg
  setup.py
  setupext.py
Labels: enhancement, infrastructure

#3183 ci: deactivate pre-commit-ci autofixing
  .pre-commit-config.yaml
  CONTRIBUTING.rst
Labels: infrastructure

#3233 [bugfix] Allow the magnetic field unit to be set from unit_base in all Gadget-based frontends
  doc/source/examining/loading_data.rst
  yt/frontends/gadget/data_structures.py
  yt/frontends/gizmo/data_structures.py
Labels: bug, code frontends, yt-4.0
