Repository yt-project/yt, pull requests merged in 2022-05, with the labels that each got.

#3891 REL: upgrade cuilbuildwheel (2.3.0 -> 2.4.0)
  .github/workflows/wheels.yaml
Labels: enhancement, infrastructure

#3640 ENH: swap_axis kwarg for PlotWindow
  doc/source/visualizing/plots.rst
  tests/tests.yaml
  yt/utilities/answer_testing/framework.py
  yt/visualization/_commons.py
  yt/visualization/base_plot_types.py
  yt/visualization/plot_modifications.py
  yt/visualization/plot_window.py
  yt/visualization/tests/test_callbacks.py
  yt/visualization/tests/test_commons.py
  yt/visualization/tests/test_plotwindow.py
Labels: enhancement, viz: 2D, new feature, deprecation

#3912 BUG: fix an upcoming incompatibility with matplotlib 3.6
  yt/visualization/color_maps.py
Labels: bug

#3898 BUG: fix an UnboundLocalError
  .tours/particle-indexing.tour
  yt/geometry/particle_geometry_handler.py
Labels: bug

#3925 BLD: fix a build error on Windows
  tests/ci_install.sh
  yt/utilities/lib/geometry_utils.pyx
  yt/utilities/lib/platform_dep.h
Labels: blocker, infrastructure

#3920 RFC: improve formatting consistency in YTException error messages
  yt/utilities/exceptions.py
Labels: enhancement, refactor

#3919 BUG: fixup FieldInfoContainer.add_field
  yt/data_objects/static_output.py
  yt/fields/field_info_container.py
  yt/fields/local_fields.py
Labels: bug, enhancement

#3918 MNT: cleanup unused workarounds for unsupported version of MPL
  yt/visualization/volume_rendering/transfer_function_helper.py
Labels: viz: volume rendering, dead code

#3913 REL: backports for yt 4.0.4
  .github/workflows/wheels.yaml
  doc/source/conf.py
  setup.cfg
  setup.py
  tests/ci_install.sh
  yt/__init__.py
  yt/frontends/gadget/data_structures.py
  yt/geometry/particle_geometry_handler.py
  yt/utilities/lib/geometry_utils.pyx
  yt/utilities/lib/platform_dep.h
  yt/visualization/color_maps.py
Labels: bug, infrastructure

#3346 Allow to set units from config file
  doc/source/analyzing/fields.rst
  doc/source/reference/configuration.rst
  doc/source/yt4differences.rst
  yt/fields/field_info_container.py
Labels: enhancement, new feature

#3763 ENH: add a yt.version_info named tuple to ease version comparison downstream
  nose_unit.cfg
  setup.cfg
  setup.py
  tests/tests.yaml
  yt/__init__.py
  yt/_version.py
  yt/tests/test_version.py
Labels: enhancement

#3626 RFC: decouple yt.config from initialization
  yt/__init__.py
  yt/config.py
  yt/data_objects/data_containers.py
  yt/data_objects/index_subobjects/grid_patch.py
  yt/data_objects/static_output.py
  yt/fields/tests/test_fields_plugins.py
  yt/frontends/ramses/definitions.py
  yt/funcs.py
  yt/mods.py
  yt/sample_data/api.py
  yt/utilities/command_line.py
  yt/utilities/configure.py
  yt/utilities/logger.py
  yt/utilities/parallel_tools/parallel_analysis_interface.py
  yt/utilities/tests/test_config.py
  yt/visualization/volume_rendering/render_source.py
Labels: refactor

#3926 updating link to re-licensing blog post
  CONTRIBUTING.rst
Labels: bug, docs

#3929 Drop a comment that was treated as a part of key=value
  setup.cfg
Labels: bug

#3907 RFC: simplify test skipper decorators
  yt/data_objects/tests/test_glue.py
  yt/fields/tests/test_sph_fields.py
  yt/frontends/ytdata/tests/test_old_outputs.py
  yt/testing.py
  yt/tests/test_testing.py
  yt/utilities/answer_testing/framework.py
Labels: infrastructure, refactor, pytest

#3931 TST: fix a broken pytest fixture
  yt/visualization/tests/test_save.py
Labels: bug, tests: running tests

#3934 BUG: fix internal warning bleeding
  yt/data_objects/static_output.py
  yt/fields/field_info_container.py
  yt/fields/local_fields.py
Labels: bug

#3935 RFC: encapsulate try blocks from on demand imports
  nose_unit.cfg
  tests/tests.yaml
  yt/testing.py
  yt/utilities/on_demand_imports.py
  yt/utilities/tests/test_on_demand_imports.py
Labels: refactor

#3914 ENH: Update Enzo-E particle mass/density distinction
  yt/frontends/enzo_e/data_structures.py
  yt/frontends/enzo_e/fields.py
  yt/frontends/enzo_e/io.py
  yt/frontends/enzo_e/misc.py
Labels: enhancement, code frontends

#3946 DOC: Fix typo in Gadget notebook
  doc/source/cookbook/yt_gadget_analysis.ipynb
Labels: bug, docs

#3939 RFC: lift ambiguity on a custom implementation of cached_property
  yt/geometry/geometry_handler.py
  yt/visualization/volume_rendering/old_camera.py
Labels: refactor

#3940 ENH: Adds "Min" Method to ProjectionPlot
  doc/source/cookbook/image_resolution.py
  doc/source/cookbook/simple_plots.rst
  doc/source/cookbook/simple_projection_methods.py
  yt/data_objects/construction_data_containers.py
  yt/data_objects/data_containers.py
  yt/data_objects/tests/test_numpy_ops.py
  yt/data_objects/tests/test_projection.py
  yt/frontends/gadget_fof/io.py
  yt/utilities/lib/quad_tree.pyx
  yt/utilities/tests/test_minimal_representation.py
  yt/visualization/plot_window.py
  yt/visualization/tests/test_plotwindow.py
  yt/visualization/volume_rendering/transfer_functions.py
Labels: new feature, deprecation
