Repository yt-project/yt, pull requests merged in 2022-09, with the labels that each got.

#4087 DOC: update Python compatibility table
  .github/workflows/build-test.yaml
  doc/source/installing.rst
Labels: docs

#4104 TST: fix ref count error in a flaky test
  yt/visualization/tests/test_callbacks.py
Labels: bug, tests: running tests

#3638 ENH: Chimera Frontend
  tests/tests.yaml
  yt/frontends/api.py
  yt/frontends/chimera/__init__.py
  yt/frontends/chimera/api.py
  yt/frontends/chimera/data_structures.py
  yt/frontends/chimera/definitions.py
  yt/frontends/chimera/fields.py
  yt/frontends/chimera/io.py
  yt/frontends/chimera/misc.py
  yt/frontends/chimera/tests/test_outputs.py
  yt/sample_data_registry.json
Labels: code frontends, new feature

#4063 Adds `data_source` argument to covering grid
  doc/source/examining/low_level_inspection.rst
  yt/data_objects/construction_data_containers.py
  yt/data_objects/tests/test_covering_grid.py
Labels: enhancement, new feature

#4112 For Boxlib frontend, allow reading of 1D particle data
  yt/frontends/boxlib/io.py
Labels: bug, code frontends

#4107 DEPR: fix a couple broken deprecations
  yt/frontends/ramses/io.py
  yt/visualization/fixed_resolution.py
Labels: bug, deprecation, release critical

#4117 TST: enable colored logs for pytest colored in GHA CI
  .github/workflows/bleeding-edge.yaml
  .github/workflows/build-test.yaml
Labels: enhancement, tests: running tests

#4116 ENH: avoid subclassing builtin dict
  yt/fields/field_info_container.py
  yt/frontends/stream/data_structures.py
  yt/funcs.py
  yt/utilities/operator_registry.py
  yt/utilities/sdf.py
Labels: enhancement

#4115 TST: test against cartopy 0.21
  conftest.py
  tests/ci_install.sh
  tests/windows_conda_requirements.txt
Labels: enhancement, tests: running tests

#4108 DOC: fix multiple warnings in docs build
  doc/source/developing/testing.rst
  doc/source/examining/loading_data.rst
  doc/source/reference/changelog.rst
  doc/source/visualizing/callbacks.rst
  doc/source/visualizing/plots.rst
Labels: bug, docs, release critical

#4057 RFC: cleanup dead attribute Dataset.file_style
  yt/data_objects/static_output.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/enzo_e/data_structures.py
  yt/frontends/sph/data_structures.py
Labels: dead code

#3989 ENH: Projections of a field's standard deviation
  doc/source/analyzing/objects.rst
  doc/source/cookbook/simple_plots.rst
  doc/source/cookbook/simple_projection_stddev.py
  doc/source/visualizing/plots.rst
  yt/data_objects/construction_data_containers.py
  yt/data_objects/data_containers.py
  yt/data_objects/tests/test_projection.py
  yt/fields/vector_operations.py
  yt/funcs.py
  yt/geometry/coordinates/cartesian_coordinates.py
  yt/geometry/coordinates/tests/test_sph_pixelization.py
  yt/utilities/math_utils.py
  yt/visualization/fits_image.py
  yt/visualization/fixed_resolution.py
  yt/visualization/plot_container.py
  yt/visualization/plot_window.py
  yt/visualization/tests/test_fits_image.py
  yt/visualization/tests/test_offaxisprojection.py
  yt/visualization/volume_rendering/off_axis_projection.py
Labels: enhancement, new feature

#4119 ENH: allow passing a dataset as a data source to ParticlePhasePlot
  yt/visualization/particle_plots.py
Labels: enhancement, viz: 2D, api-consistency

#4120 add Arepo stellar photometric fields
  yt/frontends/arepo/fields.py
  yt/frontends/gadget/io.py
Labels: code frontends, new feature

#4127 BUG: fix issues with `requires_ds` + pytest
  yt/frontends/cf_radial/data_structures.py
  yt/frontends/cf_radial/tests/test_outputs.py
  yt/frontends/fits/data_structures.py
  yt/frontends/fits/tests/test_outputs.py
  yt/utilities/answer_testing/framework.py
Labels: bug, code frontends, tests: running tests, pytest

#4125 ENH: stop using deprecated np.int
  yt/frontends/athena/data_structures.py
  yt/frontends/athena_pp/data_structures.py
Labels: enhancement

#4124 DOC: update instructions and redirections for installing cartopy
  doc/source/visualizing/geographic_projections_and_transforms.rst
  tests/ci_install.sh
  yt/utilities/on_demand_imports.py
Labels: enhancement, docs

#4123 TST: don't fail GHA tests fast
  .github/workflows/build-test.yaml
Labels: enhancement, tests: running tests

#4131 BLD: forbid netcdf4 1.6.1
  setup.cfg
Labels: bug, blocker, tests: running tests

#4139 TYP: upgrade mypy, handle newly detected problems
  setup.cfg
  yt/frontends/gadget_fof/fields.py
  yt/visualization/plot_window.py
Labels: enhancement, tests: running tests, infrastructure

#3663 ENH: Adding Cholla Frontend
  doc/source/reference/code_support.rst
  pyproject.toml
  tests/tests.yaml
  yt/frontends/api.py
  yt/frontends/cholla/__init__.py
  yt/frontends/cholla/api.py
  yt/frontends/cholla/data_structures.py
  yt/frontends/cholla/definitions.py
  yt/frontends/cholla/fields.py
  yt/frontends/cholla/io.py
  yt/frontends/cholla/misc.py
  yt/frontends/cholla/tests/test_outputs.py
  yt/sample_data_registry.json
Labels: code frontends, new feature

#4121 ENH: public API `render` methods to `PlotContainer` and `FixedResolutionBuffer`
  doc/source/visualizing/geographic_projections_and_transforms.rst
  yt/utilities/answer_testing/answer_tests.py
  yt/utilities/answer_testing/framework.py
  yt/visualization/fixed_resolution.py
  yt/visualization/plot_container.py
  yt/visualization/plot_window.py
  yt/visualization/tests/test_filters.py
Labels: enhancement, docs

#3421 ENH: Allow stream frontends to accept callables
  doc/source/examining/Loading_Data_via_Functions.ipynb
  doc/source/examining/index.rst
  doc/source/examining/loading_data.rst
  doc/source/examining/loading_via_functions.rst
  yt/__init__.py
  yt/frontends/stream/definitions.py
  yt/frontends/stream/io.py
  yt/frontends/stream/tests/test_callable_grids.py
  yt/loaders.py
Labels: enhancement, code frontends

#4141 BLD: fix broken constraint on netcdf4 requirement
  setup.cfg
Labels: bug, infrastructure, release critical

#4145 BUG: Use any() on numpy array in flash blockless check
  yt/frontends/flash/io.py
Labels: bug, code frontends, release critical

#4009 DOC: update 'fields' doc page for yt 4.1
  doc/source/analyzing/fields.rst
  yt/data_objects/data_containers.py
Labels: docs, release critical
