Repository yt-project/yt, pull requests merged in 2022-01, with the labels that each got.

#3733 MNT: mitigate CI instabilities
  conftest.py
  tests/ci_install.sh
  yt/visualization/tests/test_normal_plot_api.py
Labels: bug, blocker, tests: running tests

#3739 BUG: fix a bug in masking invalid values in line integral convolution callback
  yt/visualization/plot_modifications.py
Labels: bug, viz: 2D

#3737 BUG: fix a regression in (AxisAligned)SlicePlot's API
  yt/visualization/plot_window.py
  yt/visualization/tests/test_normal_plot_api.py
Labels: bug, api-consistency

#3443 ENH: Directly open compressed files
  doc/source/examining/loading_data.rst
  nose_unit.cfg
  setup.cfg
  tests/ci_install.sh
  tests/tests.yaml
  yt/__init__.py
  yt/loaders.py
  yt/tests/test_load_archive.py
  yt/utilities/exceptions.py
  yt/utilities/on_demand_imports.py
Labels: enhancement, new feature

#3749 BUG: ratarmount is broken on MacOS + Python 3.10, making this optional dep linux-only in test envs
  setup.cfg
Labels: bug

#3526 ENH: Particle reader cleanup
  yt/_typing.py
  yt/data_objects/static_output.py
  yt/frontends/adaptahop/io.py
  yt/frontends/ahf/io.py
  yt/frontends/art/io.py
  yt/frontends/artio/io.py
  yt/frontends/boxlib/io.py
  yt/frontends/enzo/io.py
  yt/frontends/enzo_e/io.py
  yt/frontends/fits/io.py
  yt/frontends/flash/io.py
  yt/frontends/gadget/data_structures.py
  yt/frontends/gadget/io.py
  yt/frontends/gadget_fof/io.py
  yt/frontends/gamer/io.py
  yt/frontends/gdf/io.py
  yt/frontends/halo_catalog/io.py
  yt/frontends/http_stream/io.py
  yt/frontends/owls_subfind/io.py
  yt/frontends/ramses/io.py
  yt/frontends/rockstar/io.py
  yt/frontends/sdf/io.py
  yt/frontends/sph/io.py
  yt/frontends/stream/io.py
  yt/frontends/swift/data_structures.py
  yt/frontends/swift/io.py
  yt/frontends/tipsy/io.py
  yt/frontends/ytdata/io.py
  yt/utilities/io_handler.py
Labels: index: particle, api-consistency, refactor

#3706 MNT: Add explicit support for Python 3.10 on windows
  .github/workflows/build-test-pytest.yaml
  yt/testing.py
Labels: enhancement, infrastructure, pytest

#2847 Fix some issues with stream frontend non-cartesian particles
  nose_unit.cfg
  tests/tests.yaml
  yt/frontends/stream/definitions.py
  yt/frontends/stream/io.py
  yt/frontends/stream/tests/test_stream_particles.py
Labels: bug, coordinates: non-cartesian, index: particle

#3755 BUG: fix a typesetting bug with fractionnal units in colorbar labels for volume rendering
  yt/fields/derived_field.py
Labels: bug, viz: volume rendering

#3567 DEPR: derpecate HaloCatalogCallback, let it migrate to yt_astro_analysis
  doc/source/cookbook/halo_plotting.py
  doc/source/reference/api/api.rst
  doc/source/visualizing/callbacks.rst
  yt/visualization/plot_modifications.py
Labels: dead code, deprecation

#3760 TST: add a constraint to avoid latest glue-core version in CI
  setup.cfg
Labels: bug, blocker, tests: running tests

#3767 REL: manual backports to yt-4.0.x for stability
  conftest.py
  setup.cfg
  tests/cartopy_requirements.txt
  tests/ci_install.sh
  tests/windows_conda_requirements.txt
  yt/utilities/answer_testing/framework.py
  yt/visualization/base_plot_types.py
Labels: bug, tests: running tests
