Repository yt-project/yt, pull requests merged in 2022-11, with the labels that each got.

#4196 MNT: Remove useless variables in Cython code
  yt/frontends/artio/_artio_caller.pyx
  yt/frontends/gamer/cfields.pyx
  yt/frontends/ramses/io_utils.pyx
  yt/geometry/oct_container.pyx
  yt/geometry/oct_visitors.pyx
  yt/geometry/particle_deposit.pyx
  yt/geometry/particle_oct_container.pyx
  yt/geometry/particle_smooth.pyx
  yt/utilities/lib/_octree_raytracing.pyx
  yt/utilities/lib/allocation_container.pyx
  yt/utilities/lib/autogenerated_element_samplers.pyx
  yt/utilities/lib/bounding_volume_hierarchy.pyx
  yt/utilities/lib/cykdtree/kdtree.pyx
  yt/utilities/lib/cyoctree.pyx
  yt/utilities/lib/distance_queue.pyx
  yt/utilities/lib/element_mappings.pyx
  yt/utilities/lib/embree_mesh/mesh_construction.pyx
  yt/utilities/lib/embree_mesh/mesh_samplers.pyx
  yt/utilities/lib/fixed_interpolator.cpp
  yt/utilities/lib/fnv_hash.pyx
  yt/utilities/lib/fortran_reader.pyx
  yt/utilities/lib/geometry_utils.pyx
  yt/utilities/lib/line_integral_convolution.pyx
  yt/utilities/lib/misc_utilities.pyx
  yt/utilities/lib/origami_tags.c
  yt/utilities/lib/particle_kdtree_tools.pyx
  yt/utilities/lib/particle_mesh_operations.pyx
  yt/utilities/lib/pixelization_routines.pyx
  yt/utilities/voropp.pyx
Labels: dead code

#4178 MNT: cleanup a pair of useless comments
  yt/frontends/amrvac/data_structures.py
Labels: dead code

#4195 MNT: cleanup unused import statements in Cython files
  .pre-commit-config.yaml
  doc/source/analyzing/_static/axes_calculator.pyx
  yt/frontends/artio/_artio_caller.pyx
  yt/geometry/fake_octree.pyx
  yt/geometry/grid_visitors.pyx
  yt/geometry/oct_container.pyx
  yt/geometry/oct_visitors.pyx
  yt/geometry/particle_deposit.pyx
  yt/geometry/particle_oct_container.pyx
  yt/geometry/particle_smooth.pyx
  yt/geometry/selection_routines.pyx
  yt/utilities/cython_fortran_utils.pyx
  yt/utilities/lib/_octree_raytracing.pyx
  yt/utilities/lib/basic_octree.pyx
  yt/utilities/lib/bitarray.pyx
  yt/utilities/lib/bounding_volume_hierarchy.pyx
  yt/utilities/lib/contour_finding.pyx
  yt/utilities/lib/cykdtree/kdtree.pyx
  yt/utilities/lib/cykdtree/utils.pyx
  yt/utilities/lib/embree_mesh/mesh_construction.pyx
  yt/utilities/lib/embree_mesh/mesh_intersection.pyx
  yt/utilities/lib/embree_mesh/mesh_samplers.pyx
  yt/utilities/lib/embree_mesh/mesh_traversal.pyx
  yt/utilities/lib/ewah_bool_wrap.pyx
  yt/utilities/lib/fortran_reader.pyx
  yt/utilities/lib/geometry_utils.pyx
  yt/utilities/lib/grid_traversal.pyx
  yt/utilities/lib/image_samplers.pyx
  yt/utilities/lib/image_utilities.pyx
  yt/utilities/lib/interpolators.pyx
  yt/utilities/lib/marching_cubes.pyx
  yt/utilities/lib/mesh_utilities.pyx
  yt/utilities/lib/misc_utilities.pyx
  yt/utilities/lib/particle_kdtree_tools.pyx
  yt/utilities/lib/particle_mesh_operations.pyx
  yt/utilities/lib/partitioned_grid.pyx
  yt/utilities/lib/pixelization_routines.pyx
  yt/utilities/lib/quad_tree.pyx
  yt/utilities/voropp.pyx
Labels: dead code

#4181 DOC: cleanup calls to private methods _setup_plots in doctests
  yt/visualization/plot_window.py
  yt/visualization/tests/test_set_zlim.py
Labels: enhancement, docs

#4199 Backport PR #4191 on branch yt-4.1.x (BLD: add missing __init__.py files in Cholla and Chimera test folders)
  yt/frontends/chimera/tests/__init__.py
  yt/frontends/cholla/tests/__init__.py
Labels: tests: running tests, infrastructure, release critical

#4176 BUG: make a MPL failure non-fatal for set_norm with old version of MPL
  yt/visualization/base_plot_types.py
Labels: bug, viz: 2D

#4200 BUG: fix a missing type declaration in Cython file
  yt/utilities/lib/points_in_volume.pyx
Labels: bug, performance

#4146 RFC: upgrade Cython 'language level' to Python 3
  setupext.py
  yt/geometry/_selection_routines/selector_object.pxi
  yt/geometry/fake_octree.pyx
  yt/geometry/grid_container.pxd
  yt/geometry/oct_container.pxd
  yt/geometry/oct_container.pyx
  yt/geometry/oct_visitors.pxd
  yt/geometry/oct_visitors.pyx
  yt/geometry/particle_deposit.pyx
  yt/geometry/particle_oct_container.pyx
  yt/geometry/particle_smooth.pxd
  yt/geometry/particle_smooth.pyx
  yt/geometry/selection_routines.pxd
  yt/geometry/selection_routines.pyx
  yt/utilities/lib/cykdtree/kdtree.pyx
  yt/utilities/lib/fortran_reader.pyx
  yt/utilities/lib/grid_traversal.pyx
  yt/utilities/lib/image_samplers.pyx
  yt/utilities/lib/lenses.pxd
  yt/utilities/lib/marching_cubes.pyx
  yt/utilities/lib/mesh_triangulation.pyx
  yt/utilities/lib/misc_utilities.pyx
  yt/utilities/lib/pixelization_routines.pyx
  yt/utilities/lib/primitives.pxd
Labels: refactor

#4201 Backport PR #4176 on branch yt-4.1.x (BUG: make a MPL failure non-fatal for set_norm with old version of MPL)
  yt/visualization/base_plot_types.py
Labels: bug, viz: 2D

#4206 FIX: Add libm to build for some cython files
  yt/frontends/artio/_artio_caller.pyx
  yt/utilities/lib/cosmology_time.pyx
  yt/utilities/lib/origami.pyx
Labels: infrastructure

#4207 Backport PR #4206 on branch yt-4.1.x (FIX: Add libm to build for some cython files)
  yt/frontends/artio/_artio_caller.pyx
  yt/utilities/lib/cosmology_time.pyx
  yt/utilities/lib/origami.pyx
Labels: infrastructure

#4211 [bugfix] H nuclei are being double-counted in the Arepo frontend
  yt/frontends/arepo/fields.py
  yt/frontends/arepo/tests/test_outputs.py
Labels: bug, code frontends

#4212 Backport PR #4211 on branch yt-4.1.x ([bugfix] H nuclei are being double-counted in the Arepo frontend)
  yt/frontends/arepo/fields.py
  yt/frontends/arepo/tests/test_outputs.py
Labels: bug, code frontends

#4214 MNT: temporarily switch off codetour-watch workflow
  .github/workflows/codetour-check.yaml
Labels: blocker, infrastructure

#4217 Backport PR #4214 on branch yt-4.1.x (MNT: temporarily switch off codetour-watch workflow)
  .github/workflows/codetour-check.yaml
Labels: blocker, infrastructure

#4198 Automatically find EWAH files with increased index_order2
  .tours/particle-indexing.tour
  yt/geometry/particle_geometry_handler.py
Labels: bug

#4218 Backport PR #4198 on branch yt-4.1.x (Automatically find EWAH files with increased index_order2)
  .tours/particle-indexing.tour
  yt/geometry/particle_geometry_handler.py
Labels: bug

#4216 BUG: fix compatibility between eps_writer and yt 4.1
  yt/visualization/eps_writer.py
Labels: bug, viz: 2D

#4219 Backport PR #4216 on branch yt-4.1.x (BUG: fix compatibility between eps_writer and yt 4.1)
  yt/visualization/eps_writer.py
Labels: bug, viz: 2D

#4221 CVE-2007-4559 Patch
  yt/loaders.py
Labels: bug

#4223 Backport PR #4221 on branch yt-4.1.x (CVE-2007-4559 Patch)
  yt/loaders.py
Labels: bug

#4220 REL: bump version to 4.1.2
  doc/source/conf.py
  setup.cfg
  yt/_version.py
Labels: infrastructure

#4210 RFC: simplify/clarify inheritance hierarchy for yt.data_objects.unions.Union
  yt/data_objects/particle_unions.py
  yt/data_objects/static_output.py
  yt/data_objects/unions.py
  yt/frontends/art/data_structures.py
  yt/frontends/artio/data_structures.py
  yt/frontends/stream/data_structures.py
  yt/frontends/ytdata/data_structures.py
Labels: refactor, deprecation
