Repository yt-project/yt, pull requests merged in 2022-02, with the labels that each got.

#3765 REL: Update version to 4.0.2
  doc/source/conf.py
  setup.cfg
  setup.py
  yt/__init__.py
Labels: enhancement

#3770 Pin jupyter_client. Fixes #3768
  doc/source/developing/deprecating_features.rst
  setup.cfg
Labels: docs

#3751 TST: don't update homebrew on MacOS CI (revert #3187)
  tests/ci_install.sh
Labels: enhancement, tests: running tests

#3780 Format error string
  yt/fields/field_info_container.py
Labels: bug

#3779 ENH: cleanup legacy Python, now noop, __new__ method
  yt/frontends/enzo/data_structures.py
Labels: dead code

#3783 TST: fix a deprecation warning from scipy 1.8
  yt/visualization/volume_rendering/tests/test_off_axis_SPH.py
Labels: bug, blocker, tests: running tests

#3788 Fix bug in bitmap index for particle datasets
  yt/geometry/particle_oct_container.pyx
Labels: bug, demeshening, index: particle

#3790 Backport PR #3788 on branch yt-4.0.x (Fix bug in bitmap index for particle datasets)
  yt/geometry/particle_oct_container.pyx
Labels: bug, demeshening, index: particle

#3792 DOC: don't pin a specific yt version in a badge that appears on PyPI
  README.md
Labels: bug, docs

#3796 BUG: fix a broken decorator in testing framework
  yt/testing.py
Labels: bug, tests: running tests

#3795 BUG: fix a bug in pixelize_cylinder where buffer shape was read backwards
  yt/utilities/lib/pixelization_routines.pyx
Labels: bug, viz: 2D, coordinates: non-cartesian

#3797 Backport PR #3796 on branch yt-4.0.x (BUG: fix a broken decorator in testing framework)
  yt/testing.py
Labels: bug, tests: running tests

#3798 Backport PR #3795 on branch yt-4.0.x (BUG: fix a bug in pixelize_cylinder where buffer shape was read backwards)
  yt/utilities/lib/pixelization_routines.pyx
Labels: bug, viz: 2D, coordinates: non-cartesian

#3754 BUG: add missing MPL version check to a temporary hack introduced in #3161
  yt/visualization/plot_window.py
Labels: bug, viz: 2D

#3799 Backport PR #3754 on branch yt-4.0.x (BUG: add missing MPL version check to a temporary hack introduced in #3161)
  yt/visualization/plot_window.py
Labels: bug, viz: 2D

#3801 BUG: fix error messages in RAMSESDataset validation
  yt/frontends/ramses/data_structures.py
  yt/frontends/ramses/definitions.py
Labels: bug, code frontends, UX

#3807 Backport PR #3801 on branch yt-4.0.x (BUG: fix error messages in RAMSESDataset validation)
  yt/frontends/ramses/data_structures.py
  yt/frontends/ramses/definitions.py
Labels: bug, code frontends, UX

#3778 DEPR: add missing (since/removal) info to a deprecation warning
  yt/data_objects/image_array.py
Labels: enhancement, deprecation

#3773 DEPR: deprecate yt.testing.run_nose and wrap it in the yt namespace
  yt/__init__.py
  yt/testing.py
Labels: bug, deprecation

#3762 TYP: add py.typed marker file to improve downstream type-checking
  MANIFEST.in
  pyproject.toml
  yt/py.typed
Labels: enhancement

#3758 REL: automate wheels publication to PyPI
  .github/workflows/wheels.yaml
  .pre-commit-config.yaml
Labels: enhancement, infrastructure

#3757 ENH: cleanup frbfilter registration
  yt/visualization/fixed_resolution.py
  yt/visualization/fixed_resolution_filters.py
Labels: enhancement

#2567 first cut at showing multiple transfer functions on VR
  doc/source/cookbook/complex_plots.rst
  doc/source/cookbook/render_two_fields_tf.py
  yt/visualization/volume_rendering/scene.py
  yt/visualization/volume_rendering/transfer_functions.py
Labels: viz: volume rendering, new feature

#3808 Backport PR #3778 on branch yt-4.0.x (DEPR: add missing (since/removal) info to a deprecation warning)
  yt/data_objects/image_array.py
Labels: enhancement, deprecation

#3805 Fix electromagnetic unit conversions (second try)
  .gitignore
  doc/source/developing/creating_frontend.rst
  doc/source/examining/Loading_Generic_Array_Data.ipynb
  tests/tests.yaml
  yt/data_objects/static_output.py
  yt/fields/fluid_fields.py
  yt/fields/tests/test_magnetic_fields.py
  yt/frontends/_skeleton/data_structures.py
  yt/frontends/athena_pp/tests/test_outputs.py
  yt/frontends/boxlib/tests/test_outputs.py
  yt/frontends/flash/tests/test_outputs.py
  yt/frontends/stream/data_structures.py
  yt/frontends/ytdata/data_structures.py
  yt/units/tests/test_magnetic_code_units.py
  yt/visualization/fits_image.py
Labels: bug, units

#3789 Manual backports to yt-4.0.x (blockers and bugfixes)
  .github/workflows/wheels.yaml
  .gitignore
  .pre-commit-config.yaml
  doc/source/developing/creating_frontend.rst
  doc/source/developing/deprecating_features.rst
  doc/source/examining/Loading_Generic_Array_Data.ipynb
  setup.cfg
  tests/tests.yaml
  yt/data_objects/static_output.py
  yt/fields/derived_field.py
  yt/fields/field_info_container.py
  yt/fields/fluid_fields.py
  yt/fields/tests/test_ambiguous_fields.py
  yt/fields/tests/test_magnetic_fields.py
  yt/frontends/_skeleton/data_structures.py
  yt/frontends/athena_pp/tests/test_outputs.py
  yt/frontends/boxlib/tests/test_outputs.py
  yt/frontends/flash/tests/test_outputs.py
  yt/frontends/ramses/data_structures.py
  yt/frontends/stream/data_structures.py
  yt/frontends/ytdata/data_structures.py
  yt/units/tests/test_magnetic_code_units.py
  yt/utilities/lib/pixelization_routines.pyx
  yt/visualization/fits_image.py
  yt/visualization/plot_modifications.py
  yt/visualization/volume_rendering/tests/test_off_axis_SPH.py
Labels: bug, tests: running tests

#3810 BUG: fix an edge case in enzo frontend where dark matter-only dataset would fail to load
  yt/frontends/enzo/fields.py
Labels: bug, code frontends

#3803 BUG: fixup POSIX-only path handling that can easily be made cross-platform
  yt/frontends/art/data_structures.py
  yt/frontends/boxlib/data_structures.py
  yt/frontends/boxlib/io.py
  yt/frontends/owls/fields.py
  yt/utilities/grid_data_format/conversion/conversion_athena.py
Labels: bug

#3814 Backport PR #3793 on branch yt-4.0.x (BUG: fix heuristic to switch from log scale to symlog scale)
  tests/tests.yaml
  yt/geometry/coordinates/coordinate_handler.py
  yt/visualization/base_plot_types.py
  yt/visualization/line_plot.py
  yt/visualization/plot_window.py
Labels: bug, viz: 2D
