Repository yt-project/yt, pull requests merged in 2022-06, with the labels that each got.

#3955 BUG: gracefully recover in case of invalid TOML file
  yt/utilities/configure.py
Labels: bug

#3943 ENH: make PlotCallback an abstract class
  yt/visualization/plot_modifications.py
Labels: enhancement

#2416 ENH: Stop preallocating particles
  yt/data_objects/index_subobjects/grid_patch.py
  yt/frontends/gadget/io.py
  yt/frontends/http_stream/io.py
  yt/frontends/sph/io.py
  yt/frontends/stream/io.py
  yt/frontends/tipsy/io.py
  yt/geometry/particle_deposit.pyx
  yt/utilities/io_handler.py
  yt/utilities/lib/fp_utils.pxd
  yt/utilities/lib/pixelization_routines.pyx
Labels: enhancement, performance, demeshening

#3936 RFC: deduplicate __repr__ method for AMRGridPatch subclasses
  yt/data_objects/index_subobjects/grid_patch.py
  yt/frontends/_skeleton/data_structures.py
  yt/frontends/amrvac/data_structures.py
  yt/frontends/athena/data_structures.py
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/boxlib/data_structures.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/fits/data_structures.py
  yt/frontends/flash/data_structures.py
  yt/frontends/gamer/data_structures.py
  yt/frontends/nc4_cm1/data_structures.py
  yt/frontends/stream/data_structures.py
  yt/frontends/ytdata/data_structures.py
Labels: refactor

#3921 ENH: improve error messages when add_field receives a malformed function argument
  nose_unit.cfg
  tests/tests.yaml
  yt/data_objects/selection_objects/data_selection_objects.py
  yt/data_objects/tests/test_add_field.py
  yt/fields/derived_field.py
  yt/fields/field_detector.py
  yt/fields/field_info_container.py
  yt/fields/tests/test_fields.py
  yt/frontends/amrvac/fields.py
  yt/frontends/ramses/tests/test_outputs.py
  yt/visualization/volume_rendering/off_axis_projection.py
  yt/visualization/volume_rendering/old_camera.py
Labels: enhancement, api-consistency, UX

#3951 MNT: housekeeping
  conftest.py
  pyproject.toml
  setup.cfg
  setupext.py
Labels: dead code

#3965 DOC: fix a couple errors in docs builds
  doc/helper_scripts/show_fields.py
  doc/source/visualizing/callbacks.rst
Labels: bug, docs, blocker, infrastructure

#3964 BUG: explicitly install setuptools in check-manifest test env
  .github/workflows/wheels.yaml
Labels: bug, blocker, infrastructure, release critical

#3963 BUG: cleanup swap/flip docs
  doc/source/visualizing/plots.rst
Labels: bug, viz: 2D, release critical

#3962 BUG: fix automated field unit detection for profiles
  yt/data_objects/selection_objects/data_selection_objects.py
Labels: bug, docs, release critical

#3973 Broadcast missing attribute
  yt/frontends/enzo_e/data_structures.py
Labels: bug, code frontends

#3957 RFC: refactor plot callbacks registration
  yt/visualization/fixed_resolution.py
  yt/visualization/fixed_resolution_filters.py
  yt/visualization/plot_container.py
  yt/visualization/plot_modifications.py
  yt/visualization/plot_window.py
  yt/visualization/tests/test_callbacks.py
Labels: enhancement, refactor, deprecation, UX

#3942 DEPR: fix a broken deprecation warning (missing stacklevel)
  yt/data_objects/construction_data_containers.py
Labels: bug, deprecation

#3938 MNT: remove 2 unused internal functions
  yt/visualization/color_maps.py
Labels: dead code

#3984 [BUG] volume rendering: sigma_clip normalization
  yt/data_objects/image_array.py
  yt/data_objects/tests/test_image_array.py
  yt/visualization/volume_rendering/scene.py
  yt/visualization/volume_rendering/tests/test_save_render.py
Labels: bug, viz: volume rendering

#3990 [TST] pyart deps
  setup.cfg
Labels: bug, code frontends, tests: running tests

#3988 [BUG] adjust CFRadial's _is_valid
  conftest.py
  yt/frontends/cf_radial/data_structures.py
Labels: bug, code frontends
