Repository yt-project/yt, pull requests merged in 2022-08, with the labels that each got.

#4042 BUG: Fix flux calculation on surface when there is no fluxing_field
  yt/data_objects/construction_data_containers.py
  yt/data_objects/tests/test_fluxes.py
Labels: bug

#4038 ENH: improve clarity of error messages for OffAxisSlicePlot with curvilinear geometries
  yt/visualization/plot_window.py
Labels: enhancement, coordinates: non-cartesian, UX

#4041 Preliminary support for tensor fields
  yt/fields/astro_fields.py
  yt/fields/tensor_fields.py
  yt/frontends/gamer/fields.py
  yt/frontends/gamer/tests/test_outputs.py
Labels: enhancement

#4029 ENH: only compute field suggestions if YTFieldNotFound isn't caught
  yt/utilities/exceptions.py
Labels: enhancement, performance, index: grid

#4025 ENH: reduce import time by avoiding top-level expensive imports
  conftest.py
  setup.cfg
  yt/funcs.py
  yt/sample_data/api.py
  yt/utilities/png_writer.py
  yt/visualization/_commons.py
  yt/visualization/_mpl_imports.py
  yt/visualization/color_maps.py
  yt/visualization/plot_window.py
  yt/visualization/profile_plotter.py
Labels: enhancement, performance

#4022 DOC: pin scipy in docs build to fix filters page
  doc/source/analyzing/fields.rst
  setup.cfg
Labels: bug, docs, release critical

#4028 ENH: only validate user-defined field functions (save inspection overhead)
  yt/data_objects/static_output.py
  yt/data_objects/tests/test_add_field.py
  yt/fields/field_functions.py
  yt/fields/field_info_container.py
  yt/fields/local_fields.py
Labels: enhancement, performance

#4021 BUG: fix multiple issues with magnetic field derived fields definitions
  yt/fields/derived_field.py
  yt/fields/field_info_container.py
  yt/fields/magnetic_field.py
  yt/fields/vector_operations.py
Labels: bug, coordinates: non-cartesian

#4019 MNT: cleanup dead branch in doc helper script
  doc/helper_scripts/run_recipes.py
Labels: dead code

#4049 add parameters to StreamHandler and loaders
  yt/frontends/stream/data_structures.py
  yt/frontends/stream/tests/test_outputs.py
  yt/loaders.py
Labels: enhancement, new feature

#4033 Add more field options to the Gadget frontend
  yt/fields/particle_fields.py
  yt/frontends/arepo/fields.py
  yt/frontends/gadget/fields.py
  yt/frontends/sph/fields.py
Labels: enhancement, code frontends

#2998 ENH: Enable variable cell widths for grid datasets
  doc/source/examining/loading_data.rst
  tests/tests.yaml
  yt/data_objects/construction_data_containers.py
  yt/data_objects/index_subobjects/grid_patch.py
  yt/data_objects/index_subobjects/stretched_grid.py
  yt/data_objects/static_output.py
  yt/frontends/artio/data_structures.py
  yt/frontends/nc4_cm1/data_structures.py
  yt/frontends/stream/data_structures.py
  yt/frontends/stream/tests/test_stream_stretched.py
  yt/geometry/_selection_routines/data_collection_selector.pxi
  yt/geometry/_selection_routines/grid_selector.pxi
  yt/geometry/_selection_routines/ortho_ray_selector.pxi
  yt/geometry/_selection_routines/ray_selector.pxi
  yt/geometry/_selection_routines/region_selector.pxi
  yt/geometry/_selection_routines/selector_object.pxi
  yt/geometry/_selection_routines/slice_selector.pxi
  yt/geometry/geometry_handler.py
  yt/geometry/grid_geometry_handler.py
  yt/geometry/oct_geometry_handler.py
  yt/geometry/selection_routines.pxd
  yt/geometry/tests/test_grid_index.py
  yt/loaders.py
  yt/testing.py
  yt/utilities/amr_kdtree/amr_kdtree.py
  yt/utilities/lib/misc_utilities.pyx
  yt/utilities/lib/quad_tree.pyx
Labels: new feature, generalised orthogonal grids

#4050 BUG: Fix intersections between SPH particles and regions when the boundary is periodic
  yt/data_objects/tests/test_sph_data_objects.py
  yt/geometry/_selection_routines/region_selector.pxi
Labels: bug

#4055 cleanup a dead comment
  yt/frontends/stream/data_structures.py
Labels: dead code

#4056 Adding a projection correctness test for stretched
  yt/frontends/stream/tests/test_stream_stretched.py
Labels: enhancement, tests: new tests needed

#4062 pre-commit autoupdate
  .pre-commit-config.yaml
Labels: infrastructure

#4040 BUG: setting GeoAxes extent
  yt/geometry/coordinates/geographic_coordinates.py
  yt/visualization/base_plot_types.py
  yt/visualization/tests/test_geo_projections.py
Labels: bug, viz: 2D, coordinates: geographic

#4065 REL: manual backports + prep release 4.0.5
  doc/source/conf.py
  doc/source/visualizing/callbacks.rst
  pyproject.toml
  setup.cfg
  yt/__init__.py
  yt/data_objects/construction_data_containers.py
  yt/data_objects/image_array.py
  yt/data_objects/tests/test_fluxes.py
  yt/data_objects/tests/test_image_array.py
  yt/data_objects/tests/test_sph_data_objects.py
  yt/frontends/enzo_e/data_structures.py
  yt/funcs.py
  yt/geometry/_selection_routines/region_selector.pxi
  yt/geometry/coordinates/geographic_coordinates.py
  yt/utilities/lib/image_samplers.pyx
  yt/visualization/base_plot_types.py
  yt/visualization/plot_container.py
  yt/visualization/tests/test_geo_projections.py
  yt/visualization/volume_rendering/scene.py
  yt/visualization/volume_rendering/tests/test_save_render.py
Labels: infrastructure

#4075 BUG: Off-axis projections of filtered gas particles are not scaled correctly
  yt/visualization/volume_rendering/off_axis_projection.py
Labels: bug

#4074 BUG: fix a couple broken lines in lodgeit.py
  yt/utilities/lodgeit.py
Labels: bug

#4071 ENH: perf improvements by skipping unnecessary symbolic unit computations
  yt/data_objects/index_subobjects/grid_patch.py
  yt/geometry/geometry_handler.py
Labels: enhancement, performance

#3928 MNT: revert a patch that was written in support to a now unsupported use case
  yt/fields/field_info_container.py
  yt/geometry/grid_geometry_handler.py
  yt/loaders.py
Labels: dead code

#3930 ENH: upgrade cached_properties, uniformize Dataset.unique_identifier
  yt/data_objects/index_subobjects/octree_subset.py
  yt/data_objects/region_expression.py
  yt/data_objects/static_output.py
  yt/fields/field_type_container.py
  yt/frontends/_skeleton/data_structures.py
  yt/frontends/adaptahop/data_structures.py
  yt/frontends/amrvac/data_structures.py
  yt/frontends/athena/data_structures.py
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/boxlib/data_structures.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/enzo_e/data_structures.py
  yt/frontends/exodus_ii/data_structures.py
  yt/frontends/fits/data_structures.py
  yt/frontends/flash/io.py
  yt/frontends/gadget/data_structures.py
  yt/frontends/gadget/io.py
  yt/frontends/gadget_fof/data_structures.py
  yt/frontends/gdf/data_structures.py
  yt/frontends/halo_catalog/data_structures.py
  yt/frontends/http_stream/data_structures.py
  yt/frontends/moab/data_structures.py
  yt/frontends/nc4_cm1/data_structures.py
  yt/frontends/open_pmd/data_structures.py
  yt/frontends/sdf/data_structures.py
  yt/frontends/stream/data_structures.py
  yt/frontends/swift/data_structures.py
  yt/frontends/ytdata/data_structures.py
Labels: enhancement, code frontends, refactor

#3817 ENH: add support for VelocityCallback and MagFieldCallBack in spherical coordinates
  yt/fields/vector_operations.py
  yt/frontends/stream/fields.py
  yt/visualization/plot_modifications.py
  yt/visualization/plot_window.py
  yt/visualization/tests/test_callbacks.py
Labels: enhancement, viz: 2D, coordinates: non-cartesian

#4079 ENH: Optimized radius calculation.
  yt/fields/field_functions.py
Labels: enhancement, performance

#4081 Revert #3615
  yt/frontends/boxlib/data_structures.py
  yt/frontends/boxlib/fields.py
  yt/frontends/boxlib/io.py
  yt/frontends/boxlib/misc.py
  yt/frontends/chombo/data_structures.py
  yt/frontends/chombo/fields.py
  yt/frontends/chombo/io.py
Labels: bug, release critical

#4076 BLD: build wheels for CPython 3.11
  .github/workflows/build-test.yaml
  .github/workflows/wheels.yaml
  .pre-commit-config.yaml
  setup.cfg
  tests/ci_install.sh
  yt/_maintenance/__init__.py
  yt/analysis_modules/sunyaev_zeldovich/__init__.py
  yt/utilities/lib/platform_dep.h
Labels: infrastructure

#4080 DOC: document plot callbacks extensibility
  doc/source/visualizing/callbacks.rst
Labels: enhancement, docs

#3970 DEPR: Turn ambiguous fields warnings into errors
  yt/data_objects/static_output.py
  yt/fields/tests/test_ambiguous_fields.py
Labels: docs, backwards incompatible, api-consistency, deprecation, release critical

#4070 `GAMER` frontend modification for incorporating lookback time in cosmological simulation
  yt/frontends/gamer/data_structures.py
Labels: bug, code frontends

#4090 Re-adding scipy optimize to on-demand imports
  yt/utilities/on_demand_imports.py
Labels: bug, release critical

#4089 BUG: avoid using deprecated matplotlib.cm API
  doc/source/visualizing/colormaps/cmap_images.py
  yt/visualization/color_maps.py
  yt/visualization/eps_writer.py
  yt/visualization/plot_container.py
  yt/visualization/tests/test_splat.py
  yt/visualization/volume_rendering/image_handling.py
  yt/visualization/volume_rendering/transfer_functions.py
Labels: bug, release critical

#4092 BUG: avoid using deprecated matplotlib.cm API in volume rendering (round 2)
  yt/visualization/_handlers.py
Labels: bug, release critical

#4094 BUG: fix crash in image normalization for RGBA image arrays
  yt/visualization/_handlers.py
Labels: bug, blocker, release critical

#4091 Make sure positions are in code_length in get_radius function.
  yt/fields/field_functions.py
Labels: bug, release critical

#3986 Updating the linthresh guessing
  doc/source/visualizing/plots.rst
  tests/tests.yaml
  yt/visualization/_handlers.py
  yt/visualization/tests/test_plotwindow.py
Labels: enhancement, viz: 2D, release critical

#4097 ENH: Store the Enzo-E version number in parameters attribute of EnzoEDataset
  yt/frontends/enzo_e/data_structures.py
  yt/frontends/enzo_e/io.py
Labels: enhancement, code frontends

#4098 Correcting deceptive typo in error message.
  yt/visualization/base_plot_types.py
Labels: bug, UX

#4099 ENH: Improved Enzo-E frontend's determination of fluid properties
  yt/frontends/enzo_e/data_structures.py
  yt/frontends/enzo_e/fields.py
  yt/frontends/enzo_e/misc.py
Labels: enhancement, code frontends
