Repository yt-project/yt, pull requests merged in 2022-04, with the labels that each got.

#3882 TST: workaround upstream instabilities
  .pre-commit-config.yaml
  conftest.py
Labels: bug, blocker, tests: running tests

#3883 Backport PR #3347 on branch yt-4.0.x (BUG: fix missing data sample registration and loading non-tarballs)
  yt/loaders.py
  yt/sample_data_registry.json
Labels: bug, api-consistency

#3811 BUG: bring back support to group folder structure in RAMSES
  nose_unit.cfg
  tests/tests.yaml
  yt/frontends/ramses/data_structures.py
  yt/frontends/ramses/definitions.py
  yt/frontends/ramses/tests/test_file_sanitizer.py
Labels: bug, code frontends

#3886 Manual backport #3811 to yt-4.0.x (BUG: bring back support to group folder structure in RAMSES)
  nose_unit.cfg
  tests/tests.yaml
  yt/frontends/ramses/data_structures.py
  yt/frontends/ramses/definitions.py
  yt/frontends/ramses/tests/test_file_sanitizer.py
Labels: bug, code frontends

#3881 Manual backport #3816 to yt-4.0.x (BUG: fix an issue where missing files would be indexed without verification)
  yt/frontends/gadget/data_structures.py
  yt/geometry/particle_geometry_handler.py
Labels: bug

#3878 Manual backport #3863 to yt-4.0.x (BUG: fix a bug where PlotWindow origin parameter wasn't handled correctly in non-cartesian geometries)
  yt/data_objects/selection_objects/data_selection_objects.py
  yt/visualization/particle_plots.py
  yt/visualization/plot_window.py
Labels: bug, viz: 2D, coordinates: non-cartesian

#3893 Backport PR #3888 on branch yt-4.0.x (BUG: fix a bug where setting zmin/zmax on a 2D plot with symlog norm would cause an undesired change in linthresh)
  yt/visualization/base_plot_types.py
  yt/visualization/tests/test_plotwindow.py
Labels: bug, viz: 2D

#3818 BUG: don't colorize pixels that are not completely within the data domain in pixelize_cylinder routine
  tests/tests.yaml
  yt/utilities/lib/pixelization_routines.pyx
Labels: bug, viz: 2D, coordinates: non-cartesian

#3896 Backport PR #3818 on branch yt-4.0.x (BUG: don't colorize pixels that are not completely within the data domain in pixelize_cylinder routine)
  tests/tests.yaml
  yt/utilities/lib/pixelization_routines.pyx
Labels: bug, viz: 2D, coordinates: non-cartesian

#3894 Backport PR #3683: BUG: Track blockless particles
  yt/frontends/flash/data_structures.py
  yt/frontends/flash/io.py
  yt/frontends/flash/tests/test_outputs.py
  yt/sample_data_registry.json
Labels: bug, code frontends

#3897 Updating version to 4.0.3
  doc/source/conf.py
  setup.cfg
  setup.py
  yt/__init__.py
Labels: infrastructure

#3899 BUG: fix compatibility with gadget 2 files using '*.gad.*' template
  yt/frontends/gadget/data_structures.py
Labels: bug, code frontends
