Repository yt-project/yt, pull requests merged in 2022-07, with the labels that each got.

#3997 BUG: fix a ResourceWarning (file is never closed)
  yt/funcs.py
Labels: bug

#3948 ENH: allow name-only field keys when all candidates are aliases
  yt/data_objects/construction_data_containers.py
  yt/data_objects/data_containers.py
  yt/data_objects/derived_quantities.py
  yt/data_objects/static_output.py
  yt/fields/derived_field.py
  yt/fields/field_info_container.py
  yt/fields/tests/test_ambiguous_fields.py
  yt/frontends/fits/data_structures.py
  yt/visualization/volume_rendering/off_axis_projection.py
Labels: enhancement, deprecation, release critical

#3998 ENH: Update to fields used in Enzo answer testing
  yt/frontends/enzo/answer_testing_support.py
  yt/utilities/cosmology.py
Labels: enhancement, code frontends

#4003 BUG: fix a regression where @yt.derived_field decorator would crash
  yt/data_objects/construction_data_containers.py
  yt/data_objects/tests/test_add_field.py
  yt/fields/field_info_container.py
  yt/fields/local_fields.py
Labels: bug, release critical

#4004 BUG: Use format string 'd' not 'i' in grids
  yt/data_objects/index_subobjects/grid_patch.py
Labels: bug, backport-yt-4.0.x

#4002 BUG: fix toroidal/poloidal magnetic fields registration for geometries where they are not implemented
  yt/fields/magnetic_field.py
Labels: bug, enhancement, coordinates: non-cartesian, release critical

#4005 BUG: Make sure Boxlib DLE/DRE are correct index
  tests/tests.yaml
  yt/frontends/boxlib/data_structures.py
Labels: bug, code frontends

#4007 TST: test against unyt dev version
  .github/workflows/bleeding-edge.yaml
Labels: tests: running tests, infrastructure

#3999 DOC: fixup deprecated API in docs
  doc/cheatsheet.tex
  doc/source/analyzing/filtering.rst
  doc/source/cookbook/annotations.py
  doc/source/cookbook/simple_contour_in_slice.py
  doc/source/examining/loading_data.rst
  doc/source/reference/api/api.rst
  doc/source/visualizing/callbacks.rst
  doc/source/visualizing/plots.rst
  yt/visualization/plot_modifications.py
Labels: bug, docs, api-consistency, deprecation, release critical

#3996 BUG: fix late-binding errors in closures
  .pre-commit-config.yaml
  yt/data_objects/tests/test_particle_trajectories.py
  yt/data_objects/time_series.py
  yt/frontends/exodus_ii/tests/test_outputs.py
  yt/frontends/gadget/fields.py
  yt/frontends/ramses/fields.py
  yt/frontends/ramses/io.py
  yt/frontends/tipsy/io.py
  yt/visualization/volume_rendering/tests/test_vr_orientation.py
Labels: bug, code frontends

#4011 BUG: fix for composite volume rendering with octree sources
  yt/utilities/lib/image_samplers.pyx
Labels: bug, viz: volume rendering

#4017 BUG: fix a typo in warning message
  yt/visualization/plot_container.py
Labels: bug

#3386 BUG: Turn off periodicity for particle datasets when a bounding box is explicitly set
  doc/source/examining/loading_data.rst
  tests/tests.yaml
  yt/data_objects/static_output.py
  yt/frontends/arepo/tests/test_outputs.py
  yt/frontends/sdf/data_structures.py
Labels: bug

#4032 MNT: remove upper bound for supported Python version
  setup.cfg
Labels: infrastructure

#4036 DOC: add notes that only certain data types have support for off-axis operation
  doc/source/cookbook/simple_plots.rst
  doc/source/visualizing/plots.rst
  yt/utilities/exceptions.py
Labels: docs, UX
