Repository yt-project/yt, pull requests merged in 2022-03, with the labels that each got.

#3812 Allow for different normalizations of magnetic fields in CGS
  doc/source/examining/loading_data.rst
  yt/fields/magnetic_field.py
  yt/frontends/athena/data_structures.py
  yt/frontends/athena/tests/test_outputs.py
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/athena_pp/tests/test_outputs.py
Labels: enhancement, code frontends, units

#3821 MNT: remove an unused and broken helper function
  yt/geometry/coordinates/spherical_coordinates.py
Labels: dead code

#3822 ENH: add support for varying colors in quiver annotations
  doc/source/visualizing/callbacks.rst
  yt/visualization/plot_modifications.py
Labels: bug, enhancement, viz: 2D, backwards incompatible

#3831 MNT: migrate from toml to tomli + tomli_w
  setup.cfg
  yt/config.py
Labels: enhancement

#3833 Manual backport #3831 to yt-4.0.x (MNT: migrate from toml to tomli + tomli_w)
  setup.cfg
  yt/config.py
Labels: enhancement

#3835 TST: add constraint to forbid sympy 1.10.0 in tests
  setup.cfg
Labels: bug, blocker, tests: running tests, infrastructure

#3842 Manual backport #3835 to yt-4.0.x (TST: add constraint to forbid sympy 1.10.0 in tests)
  setup.cfg
Labels: bug, blocker, tests: running tests, infrastructure

#3841 Add missing ionized species
  yt/frontends/ramses/io.py
Labels: bug, code frontends

#3843 Backport PR #3841 on branch yt-4.0.x (Add missing ionized species)
  yt/frontends/ramses/io.py
Labels: bug, code frontends

#3820 BUG: fix plot bounds for slices in cylindrical coordinates
  yt/geometry/coordinates/coordinate_handler.py
  yt/geometry/coordinates/cylindrical_coordinates.py
  yt/geometry/coordinates/spherical_coordinates.py
  yt/visualization/plot_window.py
Labels: bug, viz: 2D, coordinates: non-cartesian

#3847 remove unneeded logs using private API
  doc/source/cookbook/render_two_fields_tf.py
Labels: bug, docs

#3860 Pin jinja2 for docs build
  setup.cfg
Labels: docs

#3865 Backport PR #3860 on branch yt-4.0.x (Pin jinja2 for docs build)
  .pre-commit-config.yaml
  setup.cfg
Labels: docs

#3864 Fix definition of particle age/times
  yt/frontends/ramses/fields.py
  yt/frontends/ramses/io.py
Labels: bug, code frontends

#3866 Backport PR #3864 on branch yt-4.0.x (Fix definition of particle age/times)
  yt/frontends/ramses/fields.py
  yt/frontends/ramses/io.py
Labels: bug, code frontends

#3844 Manual backport #3820 to yt-4.0.x (BUG: fix plot bounds for slices in cylindrical coordinates)
  yt/geometry/coordinates/coordinate_handler.py
  yt/geometry/coordinates/cylindrical_coordinates.py
  yt/geometry/coordinates/spherical_coordinates.py
  yt/visualization/plot_window.py
Labels: bug, viz: 2D, coordinates: non-cartesian

#3870 BUG: fix a regression where calling annotate_timestamp on a plot from a dataset with code units would crash
  yt/visualization/plot_modifications.py
  yt/visualization/tests/test_callbacks.py
Labels: bug, viz: 2D, units

#3832 MNT: remove pyyaml and IPython from install_requires as they are both de facto optional dependencies
  setup.cfg
Labels: enhancement

#3813 DOC: update contribution guidelines
  CONTRIBUTING.rst
Labels: docs

#3871 Backport PR #3870 on branch yt-4.0.x (BUG: fix a regression where calling annotate_timestamp on a plot from a dataset with code units would crash)
  yt/visualization/plot_modifications.py
  yt/visualization/tests/test_callbacks.py
Labels: bug, viz: 2D, units

#3873 Backport PR #3859 on branch yt-4.0.x (BUG: fix a bug where automatically computed symlog linear threshold would sometimes cause a crash in matplotlib)
  tests/tests.yaml
  yt/visualization/base_plot_types.py
Labels: bug, viz: 2D

#3874 OWLS Electron number density field should return a value
  yt/frontends/owls/fields.py
Labels: bug, code frontends

#3875 Backport PR #3874 on branch yt-4.0.x (OWLS Electron number density field should return a value)
  yt/frontends/owls/fields.py
Labels: bug, code frontends

#3868 BUG: Use cm_per_mpc instead of 3.08e24 #3867
  yt/frontends/ramses/data_structures.py
  yt/frontends/ramses/tests/test_outputs.py
Labels: bug, code frontends

#3863 BUG: fix a bug where PlotWindow origin parameter wasn't handled correctly in non-cartesian geometries
  yt/data_objects/selection_objects/data_selection_objects.py
  yt/visualization/particle_plots.py
  yt/visualization/plot_window.py
Labels: bug, viz: 2D, coordinates: non-cartesian

#3877 Backport PR #3868 on branch yt-4.0.x (BUG: Use cm_per_mpc instead of 3.08e24 #3867)
  yt/frontends/ramses/data_structures.py
  yt/frontends/ramses/tests/test_outputs.py
Labels: bug, code frontends

#3856 BUG: fix buffer masking in cartesian geometry
  conftest.py
  tests/tests.yaml
  yt/geometry/coordinates/cartesian_coordinates.py
  yt/geometry/coordinates/cylindrical_coordinates.py
  yt/geometry/coordinates/geographic_coordinates.py
  yt/utilities/lib/pixelization_routines.pyx
  yt/visualization/tests/test_offaxisprojection.py
Labels: bug, viz: 2D, coordinates: cartesian

#3879 Backport PR #3856 on branch yt-4.0.x (BUG: fix buffer masking in cartesian geometry)
  conftest.py
  tests/tests.yaml
  yt/geometry/coordinates/cartesian_coordinates.py
  yt/geometry/coordinates/cylindrical_coordinates.py
  yt/geometry/coordinates/geographic_coordinates.py
  yt/utilities/lib/pixelization_routines.pyx
  yt/visualization/tests/test_offaxisprojection.py
Labels: bug, viz: 2D, coordinates: cartesian

#3880 BUG: fix particle indexing code tour
  .tours/particle-indexing.tour
Labels: bug, infrastructure
