Repository yt-project/yt, pull requests merged in 2023-08, with the labels that each got.

#4575 BLD: switch to Cython>=3.0,<3.1
  pyproject.toml
  yt/frontends/gamer/cfields.pyx
  yt/geometry/particle_deposit.pxd
  yt/utilities/lib/autogenerated_element_samplers.pxd
  yt/utilities/lib/autogenerated_element_samplers.pyx
  yt/utilities/lib/bitarray.pxd
  yt/utilities/lib/bounding_volume_hierarchy.pxd
  yt/utilities/lib/bounding_volume_hierarchy.pyx
  yt/utilities/lib/element_mappings.pxd
  yt/utilities/lib/element_mappings.pyx
  yt/utilities/lib/fixed_interpolator.pxd
  yt/utilities/lib/image_samplers.pxd
  yt/utilities/lib/lenses.pyx
  yt/utilities/lib/pixelization_routines.pyx
  yt/utilities/lib/primitives.pxd
  yt/utilities/lib/primitives.pyx
  yt/utilities/lib/vec3_ops.pxd
  yt/utilities/mesh_code_generation.py
Labels: dependencies, build

#4607 BLD: forbid deprecated numpy C API
  setupext.py
Labels: enhancement, build

#4620 BLD: fix wheels workflow (sync build requirements with pyproject.toml)
  .github/workflows/wheels.yaml
  pyproject.toml
Labels: bug, release critical, build

#4583 BLD: explicitly specify build-backend
  pyproject.toml
Labels: enhancement, build

#4621 TST: simplify cartopy integration testing (using cartopy 0.22)
  .github/workflows/build-test.yaml
  conftest.py
  pyproject.toml
  tests/ci_install.sh
  tests/windows_conda_requirements.txt
  yt/geometry/tests/test_geometries.py
Labels: enhancement, tests: running tests

#4631 BUG: fix an UnboundLocalError in PhasePlot._setup_plots
  yt/visualization/profile_plotter.py
Labels: bug

#4632 Backport PR #4631 on branch yt-4.2.x (BUG: fix an UnboundLocalError in PhasePlot._setup_plots)
  yt/visualization/profile_plotter.py
Labels: bug, viz: 2D

#4625 BLD: add wheels for CPython 3.12
  .github/workflows/wheels.yaml
  pyproject.toml
Labels: enhancement, build

#4634 MNT: drop unmaintained install script
  MANIFEST.in
  doc/install_script.sh
  docker/fedora_script/Dockerfile
  docker/sid_script/Dockerfile
  tests/test_install_script.py
Labels: dead code, build

#4637 BLD: migrate from oldest-supported-numpy to NPY_TARGET_VERSION (Python >= 3.9)
  pyproject.toml
  setupext.py
Labels: enhancement, build

#4638 BUG: fix a crash with certain combinations of kwargs for adding dimensionless derived fields to datasets
  yt/data_objects/selection_objects/data_selection_objects.py
  yt/data_objects/tests/test_add_field.py
Labels: bug, units, api-consistency

#4645 Backport PR #4638 on branch yt-4.2.x (BUG: fix a crash with certain combinations of kwargs for adding dimensionless derived fields to datasets)
  yt/data_objects/selection_objects/data_selection_objects.py
  yt/data_objects/tests/test_add_field.py
Labels: bug, units, api-consistency

#4644 BUG: fix error message when trying to use a feature that requires cartopy while it's missing
  yt/utilities/on_demand_imports.py
Labels: bug, UX

#4647 Backport PR #4644 on branch yt-4.2.x (BUG: fix error message when trying to use a feature that requires cartopy while it's missing)
  yt/utilities/on_demand_imports.py
Labels: bug, UX

#4649 MNT: All nogil into noexcept nogil
  yt/frontends/artio/_artio_caller.pyx
  yt/geometry/_selection_routines/selector_object.pxi
  yt/geometry/oct_container.pxd
  yt/geometry/oct_container.pyx
  yt/geometry/oct_visitors.pxd
  yt/geometry/particle_deposit.pxd
  yt/geometry/selection_routines.pxd
  yt/geometry/selection_routines.pyx
  yt/utilities/lib/bounding_volume_hierarchy.pxd
  yt/utilities/lib/bounding_volume_hierarchy.pyx
  yt/utilities/lib/cykdtree/kdtree.pxd
  yt/utilities/lib/cyoctree.pyx
  yt/utilities/lib/distance_queue.pyx
  yt/utilities/lib/embree_mesh/mesh_intersection.pxd
  yt/utilities/lib/embree_mesh/mesh_intersection.pyx
  yt/utilities/lib/embree_mesh/mesh_samplers.pxd
  yt/utilities/lib/embree_mesh/mesh_samplers.pyx
  yt/utilities/lib/field_interpolation_tables.pxd
  yt/utilities/lib/fnv_hash.pxd
  yt/utilities/lib/fnv_hash.pyx
  yt/utilities/lib/geometry_utils.pyx
  yt/utilities/lib/image_samplers.pyx
  yt/utilities/lib/lenses.pxd
  yt/utilities/lib/mesh_triangulation.pyx
Labels: bug, performance

#4640 ENH: Only call find_spec sometimes
  yt/data_objects/static_output.py
Labels: enhancement, performance

#4629 TYP: fix type-checking incompatibilities with matplotlib 3.8
  yt/visualization/_handlers.py
  yt/visualization/base_plot_types.py
  yt/visualization/volume_rendering/scene.py
Labels: enhancement

#4650 Backport PR #4640 on branch yt-4.2.x (ENH: Only call find_spec sometimes)
  yt/data_objects/static_output.py
Labels: enhancement, performance

#4648 REL: bump version to 4.2.2
  doc/source/conf.py
  pyproject.toml
  yt/_version.py
Labels: infrastructure
