Repository yt-project/yt, pull requests merged in 2023-03, with the labels that each got.

#4354 Minor updates to answer tests infra
  yt/utilities/answer_testing/answer_tests.py
  yt/visualization/fixed_resolution.py
Labels: bug, tests: running tests, pytest

#4357 BLD: fix a future incompatibility with Cython 3.0
  yt/utilities/lib/primitives.pxd
  yt/utilities/lib/primitives.pyx
  yt/utilities/lib/vec3_ops.pxd
Labels: refactor

#4348 MNT: Dedup of mailmap aliases
  .mailmap
Labels: infrastructure

#4361 BUG: handle deprecation warning from numpy 1.25 (np.product is deprecated in favour of np.prod)
  doc/source/cookbook/power_spectrum_example.py
  yt/data_objects/tests/test_covering_grid.py
  yt/frontends/boxlib/io.py
  yt/utilities/decompose.py
  yt/utilities/tests/test_particle_generator.py
Labels: bug

#4364 BLD: drop unjustified upper bounds to optional dependencies
  pyproject.toml
Labels: enhancement, dependencies

#4344 TST: don't install nose on python >= 3.10
  conftest.py
  pyproject.toml
Labels: enhancement, tests: running tests, dependencies

#4358 TST: accelerate type-checking workflow
  .github/workflows/type-checking.yaml
Labels: tests: running tests, dead code

#4359 RFC: uniformize cython.floating usage
  yt/geometry/_selection_routines/selector_object.pxi
  yt/geometry/particle_oct_container.pyx
  yt/geometry/selection_routines.pyx
  yt/utilities/lib/contour_finding.pyx
  yt/utilities/lib/geometry_utils.pyx
  yt/utilities/lib/primitives.pxd
  yt/utilities/lib/primitives.pyx
  yt/utilities/lib/vec3_ops.pxd
Labels: refactor

#4365 BLD: fix compilation errors with Cython 3.0.0b1 (pow return type)
  .github/workflows/wheels.yaml
  pyproject.toml
  yt/frontends/ramses/io_utils.pyx
  yt/utilities/lib/basic_octree.pyx
  yt/utilities/lib/geometry_utils.pyx
Labels: refactor

#4373 BLD: add missing noexcept qualifier (Cython 3 compat)
  yt/geometry/oct_container.pyx
Labels: refactor

#4374 TST: test (bleeding-edge) with Cython 3.0
  .github/workflows/bleeding-edge.yaml
  setup.py
  yt/utilities/lib/cykdtree/kdtree.pyx
  yt/utilities/lib/cykdtree/utils.pyx
Labels: tests: running tests, infrastructure

#4375 RFC: handle a deprecation warning from Cython (The keyword 'nogil' should appear at the end of the function signature line.)
  yt/geometry/particle_deposit.pxd
  yt/geometry/particle_deposit.pyx
  yt/utilities/lib/bounded_priority_queue.pxd
  yt/utilities/lib/bounded_priority_queue.pyx
  yt/utilities/lib/image_samplers.pxd
  yt/utilities/lib/lenses.pyx
  yt/utilities/lib/particle_kdtree_tools.pxd
  yt/utilities/lib/particle_kdtree_tools.pyx
Labels: refactor

#4378 BUG: Fix typo in vector operations and enable plot modifications for spherical geometry
  yt/fields/vector_operations.py
  yt/visualization/plot_modifications.py
  yt/visualization/tests/test_callbacks.py
Labels: bug, viz: 2D, coordinates: non-cartesian

#4380 BLD: do not require pyparsing
  pyproject.toml
  yt/visualization/plot_window.py
Labels: enhancement

#4388 Fix field access in ytdata docs.
  doc/source/analyzing/saving_data.rst
Labels: bug, docs

#4385 BUG: Fix example in docs and missing displacement for unstructured mesh
  yt/frontends/exodus_ii/data_structures.py
Labels: bug, code frontends

#4386 PERF: add explicit noexcept qualifiers to fp_utils functions
  yt/utilities/lib/fp_utils.pxd
Labels: bug, performance

#4389 Avoiding issue for CHOLLA LightRay datasets
  yt/frontends/cholla/data_structures.py
Labels: bug, code frontends

#4363 ENH: add basename for loaders
  doc/source/examining/Loading_Generic_Array_Data.ipynb
  yt/loaders.py
Labels: enhancement, docs

#4390 PERF: add explicit noexcept qualifiers to resolve perf regressions (Cython 3)
  yt/frontends/artio/_artio_caller.pyx
  yt/geometry/_selection_routines/always_selector.pxi
  yt/geometry/_selection_routines/boolean_selectors.pxi
  yt/geometry/_selection_routines/compose_selector.pxi
  yt/geometry/_selection_routines/cut_region_selector.pxi
  yt/geometry/_selection_routines/cutting_plane_selector.pxi
  yt/geometry/_selection_routines/disk_selector.pxi
  yt/geometry/_selection_routines/ellipsoid_selector.pxi
  yt/geometry/_selection_routines/grid_selector.pxi
  yt/geometry/_selection_routines/indexed_octree_subset_selector.pxi
  yt/geometry/_selection_routines/octree_subset_selector.pxi
  yt/geometry/_selection_routines/ortho_ray_selector.pxi
  yt/geometry/_selection_routines/point_selector.pxi
  yt/geometry/_selection_routines/ray_selector.pxi
  yt/geometry/_selection_routines/region_selector.pxi
  yt/geometry/_selection_routines/selector_object.pxi
  yt/geometry/_selection_routines/slice_selector.pxi
  yt/geometry/_selection_routines/sphere_selector.pxi
  yt/geometry/selection_routines.pxd
  yt/utilities/lib/field_interpolation_tables.pxd
  yt/utilities/lib/image_samplers.pxd
  yt/utilities/lib/image_samplers.pyx
Labels: bug, performance

#4392 PERF: add explicit noexcept qualifiers to resolve perf regressions in volume rendering (Cython 3)
  yt/geometry/_selection_routines/ray_selector.pxi
  yt/utilities/lib/grid_traversal.pxd
  yt/utilities/lib/grid_traversal.pyx
Labels: bug, viz: volume rendering, performance

#4376 RFC: eliminate some unused deprecated Cython macros
  yt/geometry/particle_oct_container.pyx
  yt/utilities/lib/_octree_raytracing.pyx
  yt/utilities/lib/amr_kdtools.pyx
  yt/utilities/lib/grid_traversal.pyx
Labels: dead code
