Repository yt-project/yt, pull requests merged in 2023-11, with the labels that each got.

#4696 Allow names for the SPH particle type other than "io" in the stream frontend
  doc/source/examining/Loading_Generic_Particle_Data.ipynb
  yt/frontends/stream/data_structures.py
  yt/frontends/stream/tests/test_stream_particles.py
Labels: enhancement

#4719 ENH: fix notebook links
  doc/source/analyzing/Particle_Trajectories.ipynb
  doc/source/analyzing/astropy_integrations.rst
  doc/source/analyzing/domain_analysis/XrayEmissionFields.ipynb
  doc/source/analyzing/domain_analysis/index.rst
  doc/source/analyzing/domain_analysis/xray_emission_fields.rst
  doc/source/analyzing/filtering.rst
  doc/source/analyzing/index.rst
  doc/source/analyzing/mesh_filter.ipynb
  doc/source/analyzing/particle_filter.ipynb
  doc/source/analyzing/particle_trajectories.rst
  doc/source/cookbook/fits_radio_cubes.ipynb
  doc/source/cookbook/fits_xray_images.ipynb
  doc/source/cookbook/index.rst
  doc/source/cookbook/tipsy_and_yt.ipynb
  doc/source/cookbook/yt_gadget_analysis.ipynb
  doc/source/cookbook/yt_gadget_owls_analysis.ipynb
  doc/source/examining/Loading_Data_via_Functions.ipynb
  doc/source/examining/Loading_Generic_Array_Data.ipynb
  doc/source/examining/Loading_Generic_Particle_Data.ipynb
  doc/source/examining/generic_array_data.rst
  doc/source/examining/generic_particle_data.rst
  doc/source/examining/index.rst
  doc/source/examining/loading_data.rst
  doc/source/examining/loading_via_functions.rst
  doc/source/examining/low_level_inspection.rst
  doc/source/examining/spherical_data.rst
  doc/source/quickstart/data_inspection.rst
  doc/source/quickstart/data_objects_and_time_series.rst
  doc/source/quickstart/derived_fields_and_profiles.rst
  doc/source/quickstart/index.rst
  doc/source/quickstart/introduction.rst
  doc/source/quickstart/simple_visualization.rst
  doc/source/quickstart/volume_rendering.rst
  doc/source/reference/code_support.rst
  doc/source/visualizing/FITSImageData.ipynb
  doc/source/visualizing/TransferFunctionHelper_Tutorial.ipynb
  doc/source/visualizing/Volume_Rendering_Tutorial.ipynb
  doc/source/visualizing/geographic_projections_and_transforms.rst
  doc/source/visualizing/index.rst
  doc/source/visualizing/streamlines.rst
  doc/source/visualizing/transfer_function_helper.rst
  doc/source/visualizing/volume_rendering.rst
  doc/source/visualizing/volume_rendering_tutorial.rst
  doc/source/visualizing/writing_fits_images.rst
Labels: bug, docs

#4725 BUG: handle deprecation warnings from numpy 2.0.0dev0 (np.row_stack -> np.vstack and np.in1d -> np.isin)
  yt/data_objects/particle_trajectories.py
  yt/frontends/adaptahop/data_structures.py
  yt/visualization/plot_modifications.py
Labels: bug

#4723 Backport PR #4722 on branch yt-4.3.x (TST: fix an incompatibility with unyt 3.0 (amu_cgs doesn't exist as a physical constant anymore))
  yt/fields/species_fields.py
  yt/fields/tests/test_species_fields.py
  yt/frontends/arepo/fields.py
Labels: bug, tests: running tests

#4707 add override_bins to data_container.profile
  yt/data_objects/data_containers.py
  yt/data_objects/profiles.py
Labels: enhancement

#4726 Backport PR #4725 on branch yt-4.3.x (BUG: handle deprecation warnings from numpy 2.0.0dev0 (np.row_stack -> np.vstack and np.in1d -> np.isin))
  yt/data_objects/particle_trajectories.py
  yt/frontends/adaptahop/data_structures.py
  yt/visualization/plot_modifications.py
Labels: bug

#4729 Backport PR #4719 on branch yt-4.3.x (ENH: fix notebook links)
  doc/source/analyzing/Particle_Trajectories.ipynb
  doc/source/analyzing/astropy_integrations.rst
  doc/source/analyzing/domain_analysis/XrayEmissionFields.ipynb
  doc/source/analyzing/domain_analysis/index.rst
  doc/source/analyzing/domain_analysis/xray_emission_fields.rst
  doc/source/analyzing/filtering.rst
  doc/source/analyzing/index.rst
  doc/source/analyzing/mesh_filter.ipynb
  doc/source/analyzing/particle_filter.ipynb
  doc/source/analyzing/particle_trajectories.rst
  doc/source/cookbook/fits_radio_cubes.ipynb
  doc/source/cookbook/fits_xray_images.ipynb
  doc/source/cookbook/index.rst
  doc/source/cookbook/tipsy_and_yt.ipynb
  doc/source/cookbook/yt_gadget_analysis.ipynb
  doc/source/cookbook/yt_gadget_owls_analysis.ipynb
  doc/source/examining/Loading_Data_via_Functions.ipynb
  doc/source/examining/Loading_Generic_Array_Data.ipynb
  doc/source/examining/Loading_Generic_Particle_Data.ipynb
  doc/source/examining/generic_array_data.rst
  doc/source/examining/generic_particle_data.rst
  doc/source/examining/index.rst
  doc/source/examining/loading_data.rst
  doc/source/examining/loading_via_functions.rst
  doc/source/examining/low_level_inspection.rst
  doc/source/examining/spherical_data.rst
  doc/source/quickstart/data_inspection.rst
  doc/source/quickstart/data_objects_and_time_series.rst
  doc/source/quickstart/derived_fields_and_profiles.rst
  doc/source/quickstart/index.rst
  doc/source/quickstart/introduction.rst
  doc/source/quickstart/simple_visualization.rst
  doc/source/quickstart/volume_rendering.rst
  doc/source/reference/code_support.rst
  doc/source/visualizing/FITSImageData.ipynb
  doc/source/visualizing/TransferFunctionHelper_Tutorial.ipynb
  doc/source/visualizing/Volume_Rendering_Tutorial.ipynb
  doc/source/visualizing/geographic_projections_and_transforms.rst
  doc/source/visualizing/index.rst
  doc/source/visualizing/streamlines.rst
  doc/source/visualizing/transfer_function_helper.rst
  doc/source/visualizing/volume_rendering.rst
  doc/source/visualizing/volume_rendering_tutorial.rst
  doc/source/visualizing/writing_fits_images.rst
Labels: bug, docs

#4727 Backport PR #4724 on branch yt-4.3.x (DEP: fix remaining incompatibilities and declare compatibility with unyt 3.0)
  pyproject.toml
  yt/testing.py
Labels: enhancement, dependencies

#4728 MNT: fix auto-reports for bleeding edge CI
  .github/workflows/bleeding-edge.yaml
Labels: bug, tests: running tests, infrastructure

#4720 Ramses-speedup
  yt/frontends/ramses/field_handlers.py
  yt/frontends/ramses/io_utils.pyx
  yt/geometry/oct_container.pxd
  yt/geometry/oct_container.pyx
  yt/utilities/cython_fortran_utils.pxd
  yt/utilities/cython_fortran_utils.pyx
Labels: enhancement, code frontends, performance

#4731 MNT: opt-in ruff's builtin support for jupyter notebooks
  .pre-commit-config.yaml
  pyproject.toml
Labels: infrastructure, code style

#4733 RFC: refactor usage of numpy.random legacy API
  doc/source/examining/Loading_Generic_Particle_Data.ipynb
  pyproject.toml
  yt/fields/field_detector.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/gadget/testing.py
  yt/testing.py
  yt/utilities/particle_generator.py
  yt/visualization/fixed_resolution_filters.py
  yt/visualization/volume_rendering/camera_path.py
Labels: code style, refactor

#4743 use axis_order kwarg in geo nb
  doc/source/cookbook/geographic_xforms_and_projections.ipynb
Labels: bug, docs

#4744 Backport PR #4743 on branch yt-4.3.x (use axis_order kwarg in geo nb)
  doc/source/cookbook/geographic_xforms_and_projections.ipynb
Labels: bug, docs

#4746 BUG: avoid a noisy self-triggered warning about libconf being a hard dependency to load any enzo data
  yt/frontends/enzo/data_structures.py
Labels: bug, code frontends, UX

#4747 Backport PR #4746 on branch yt-4.3.x (BUG: avoid a noisy self-triggered warning about libconf being a hard dependency to load any enzo data)
  yt/frontends/enzo/data_structures.py
Labels: bug, code frontends, UX

#4745 BUG: avoid a deprecation warning in yt.load_sample on Python 3.12
  .github/workflows/build-test.yaml
  yt/loaders.py
Labels: bug, tests: running tests, infrastructure

#4751 Backport PR #4745 on branch yt-4.3.x (BUG: avoid a deprecation warning in yt.load_sample on Python 3.12)
  .github/workflows/build-test.yaml
  yt/loaders.py
Labels: bug, tests: running tests, infrastructure
