Repository yt-project/yt, pull requests merged in 2023-07, with the labels that each got.

#4553 enh: store basic software info in png metadata
  yt/funcs.py
  yt/utilities/png_writer.py
  yt/visualization/base_plot_types.py
  yt/visualization/tests/test_save.py
Labels: enhancement, viz: 2D

#4539 PERF: delay frontends initialization until yt.load is actually called
  yt/__init__.py
  yt/data_objects/tests/test_registration.py
  yt/frontends/__init__.py
  yt/frontends/api.py
  yt/loaders.py
Labels: enhancement, performance

#4564 DOC: hotfix doc builds
  yt/frontends/__init__.py
Labels: bug, docs

#4562 Athena++ stretched grids support
  doc/source/examining/loading_data.rst
  tests/tests.yaml
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/athena_pp/io.py
  yt/frontends/athena_pp/tests/test_outputs.py
Labels: bug, enhancement, code frontends

#4566 update annotate_contours docs to avoid deprecated API
  doc/source/visualizing/callbacks.rst
Labels: docs

#4567 Backport PR #4566 on branch yt-4.2.x (update annotate_contours docs to avoid deprecated API)
  doc/source/visualizing/callbacks.rst
Labels: docs

#4570 Fix fake_dataset periodicity attribute in FieldDetector
  yt/fields/field_detector.py
Labels: bug

#4571 Backport PR #4570 on branch yt-4.2.x (Fix fake_dataset periodicity attribute in FieldDetector)
  yt/fields/field_detector.py
Labels: bug

#4517 PERF: delay rarely used imports (netcdf4, importlib, multiprocessing, tarfile, tomllib, tomli_w)
  yt/funcs.py
  yt/loaders.py
  yt/sample_data/api.py
  yt/tests/test_external_frontends.py
  yt/utilities/command_line.py
  yt/utilities/configure.py
  yt/utilities/on_demand_imports.py
  yt/utilities/parameter_file_storage.py
  yt/visualization/_commons.py
  yt/visualization/plot_container.py
Labels: enhancement, performance

#4572 ENH: species handling for the stream frontend
  doc/source/examining/Loading_Generic_Array_Data.ipynb
  doc/source/examining/Loading_Spherical_Data.ipynb
  yt/frontends/stream/fields.py
  yt/frontends/stream/tests/test_stream_species.py
Labels: enhancement

#4573 DEP: set upper limit to runtime numpy
  pyproject.toml
Labels: enhancement, dependencies

#4576 Backport PR #4573 on branch yt-4.2.x (DEP: set upper limit to runtime numpy)
  pyproject.toml
Labels: enhancement, dependencies

#4578 Backport PR #4577 on branch yt-4.2.x (TST: fix fortran IO test for big-endian architectures)
  yt/utilities/tests/test_cython_fortran_utils.py
Labels: bug, tests: running tests

#4560 TST: switch future-dependencies tests from daily to weekly frequency, add auto-reporting in case of failure
  .github/workflows/bleeding-edge.yaml
Labels: enhancement, tests: running tests, infrastructure

#4585 BUG: avoid deprecated numpy API in flash frontend (implicit conversion of 1-sized arrays to scalar types is deprecated in numpy 1.25)
  yt/frontends/flash/data_structures.py
Labels: bug, code frontends

#4556 option to include min/max limits on the color field for export_sketchfab
  yt/data_objects/construction_data_containers.py
Labels: enhancement

#4582 DOC: fix string interpolation (units double-printing) in particle_filter cookbook recipe
  doc/source/cookbook/particle_filter.py
Labels: bug, docs

#4587 Backport PR #4585 on branch yt-4.2.x (BUG: avoid deprecated numpy API in flash frontend (implicit conversion of 1-sized arrays to scalar types is deprecated in numpy 1.25))
  yt/frontends/flash/data_structures.py
Labels: bug, code frontends

#4588 Backport PR #4582 on branch yt-4.2.x (DOC: fix string interpolation (units double-printing) in particle_filter cookbook recipe)
  doc/source/cookbook/particle_filter.py
Labels: bug, docs

#4586 BUG: avoid divide-by-zero runtime warning from np.log10 in AMRKDTree.get_brick_data
  yt/utilities/amr_kdtree/amr_kdtree.py
Labels: bug

#4589 Backport PR #4586 on branch yt-4.2.x (BUG: avoid divide-by-zero runtime warning from np.log10 in AMRKDTree.get_brick_data)
  yt/utilities/amr_kdtree/amr_kdtree.py
Labels: bug

#4579 ytdata: check for `all_data` in particle selection
  yt/frontends/ytdata/io.py
Labels: performance, index: particle, refactor

#4592 Docs fixes
  doc/source/cookbook/fits_xray_images.ipynb
  doc/source/examining/Loading_Generic_Particle_Data.ipynb
Labels: bug, docs

#4594 Backport PR #4592 on branch yt-4.2.x (Docs fixes)
  doc/source/cookbook/fits_xray_images.ipynb
  doc/source/examining/Loading_Generic_Particle_Data.ipynb
Labels: bug, docs

#4595 ytdata io: use data_file.start and .end index range
  yt/frontends/ytdata/io.py
Labels: bug, index: particle

#4547 BUG: Fix initialization of max level in load_octree
  yt/frontends/stream/data_structures.py
  yt/frontends/stream/tests/test_stream_octree.py
  yt/geometry/oct_container.pxd
  yt/geometry/oct_container.pyx
  yt/geometry/oct_visitors.pxd
  yt/geometry/oct_visitors.pyx
  yt/geometry/particle_oct_container.pyx
Labels: bug, index: octree

#4598 Backport PR #4547 on branch yt-4.2.x (BUG: Fix initialization of max level in load_octree)
  yt/frontends/stream/data_structures.py
  yt/frontends/stream/tests/test_stream_octree.py
  yt/geometry/oct_container.pxd
  yt/geometry/oct_container.pyx
  yt/geometry/oct_visitors.pxd
  yt/geometry/oct_visitors.pyx
  yt/geometry/particle_oct_container.pyx
Labels: bug, index: octree

#4580 TST: run cookbook recipes in a deterministic order
  doc/source/cookbook/tests/test_cookbook.py
Labels: enhancement, tests: running tests, dead code

#4601 BUG: fix string interpolation (units double-printing) in GridIndex
  yt/frontends/ramses/data_structures.py
  yt/geometry/grid_geometry_handler.py
Labels: bug

#4602 Backport PR #4601 on branch yt-4.2.x (BUG: fix string interpolation (units double-printing) in GridIndex)
  yt/frontends/ramses/data_structures.py
  yt/geometry/grid_geometry_handler.py
Labels: bug

#4600 TST: cleanup unused test code
  doc/source/cookbook/tests/test_cookbook.py
Labels: tests: running tests, dead code

#4470 BUG: Update GIZMO frontend to handle newer GIZMO versions
  yt/frontends/gizmo/data_structures.py
  yt/frontends/gizmo/tests/test_outputs.py
  yt/sample_data_registry.json
Labels: bug

#4597 reduce code duplication in IOHandler _read_particle_coords and _read_particle_fields
  yt/frontends/adaptahop/io.py
  yt/frontends/ahf/io.py
  yt/frontends/gadget_fof/io.py
  yt/frontends/halo_catalog/io.py
  yt/frontends/http_stream/io.py
  yt/frontends/owls_subfind/io.py
  yt/frontends/rockstar/io.py
  yt/frontends/sdf/io.py
  yt/frontends/stream/io.py
  yt/frontends/tipsy/io.py
  yt/frontends/ytdata/io.py
  yt/utilities/io_handler.py
Labels: index: particle, refactor

#4609 BLD: Sort input file list
  setup.py
Labels: enhancement, infrastructure

#4599 DOC: update documentation on off-axis projections for non-SPH particle data
  doc/source/visualizing/plots.rst
Labels: bug, docs

#4610 Backport PR #4609 on branch yt-4.2.x (BLD: Sort input file list)
  setup.py
Labels: enhancement, infrastructure

#4612 Backport PR #4604 on branch yt-4.2.x (BUG: skip out-of-bounds particles in ngp deposition)
  yt/utilities/lib/image_utilities.pyx
Labels: bug, viz: 2D, index: particle

#4613 Backport PR #4599 on branch yt-4.2.x (DOC: update documentation on off-axis projections for non-SPH particle data)
  doc/source/visualizing/plots.rst
Labels: bug, docs

#4605 Updates to the _parse_parameter_file function following PR 4470
  yt/frontends/gadget/data_structures.py
Labels: code frontends, refactor

#4424 [ENH] support for sinks in csv format for RAMSES frontend
  yt/frontends/ramses/fields.py
  yt/frontends/ramses/io.py
  yt/frontends/ramses/particle_handlers.py
  yt/utilities/on_demand_imports.py
Labels: enhancement, code frontends
