Repository yt-project/yt, pull requests merged in 2023-06, with the labels that each got.

#4465 BUG: Turn range into a list for keyframes
  yt/visualization/volume_rendering/camera_path.py
Labels: bug, viz: volume rendering

#4466 Backport PR #4465 on branch yt-4.2.x (BUG: Turn range into a list for keyframes)
  yt/visualization/volume_rendering/camera_path.py
Labels: bug, viz: volume rendering

#4472 BUG: fix overflows in ParticleBitmap hashing
  yt/geometry/particle_oct_container.pyx
Labels: bug, index: particle

#4473 Backport PR #4472 on branch yt-4.2.x (BUG: fix overflows in ParticleBitmap hashing)
  yt/geometry/particle_oct_container.pyx
Labels: bug, index: particle

#4469 DEPR: remove default value for stacklevel in issue_deprecation_warning, fix missing arguments in call sites
  doc/source/developing/deprecating_features.rst
  yt/_maintenance/deprecation.py
  yt/data_objects/data_containers.py
  yt/data_objects/particle_unions.py
  yt/data_objects/static_output.py
  yt/fields/derived_field.py
  yt/fields/field_info_container.py
  yt/frontends/ramses/io.py
  yt/funcs.py
  yt/geometry/geometry_handler.py
  yt/loaders.py
  yt/testing.py
  yt/visualization/fixed_resolution.py
  yt/visualization/fixed_resolution_filters.py
  yt/visualization/particle_plots.py
  yt/visualization/plot_container.py
  yt/visualization/plot_modifications.py
  yt/visualization/plot_window.py
Labels: enhancement, deprecation

#4479 BUG: fix a confusing warning emitted when a dimensionless derived field is registered with implicit units
  yt/data_objects/selection_objects/data_selection_objects.py
Labels: bug, UX

#4477 allow user to set the thickness of the coordinate lines in VR
  yt/visualization/volume_rendering/render_source.py
  yt/visualization/volume_rendering/scene.py
Labels: enhancement, viz: volume rendering

#4456 TST: time saving optimisations in CI
  .github/workflows/bleeding-edge.yaml
  .github/workflows/build-test.yaml
Labels: enhancement, tests: running tests, infrastructure

#4463 BUG: fix a bug where setting boolean parameters from the command line would break at runtime validation
  yt/utilities/configure.py
Labels: bug

#4482 BUG: Fix off-axis particle projections with a weight field
  yt/visualization/fixed_resolution.py
  yt/visualization/tests/test_particle_plot.py
Labels: bug

#4484 Backport PR #4482 on branch yt-4.2.x (BUG: Fix off-axis particle projections with a weight field)
  yt/visualization/fixed_resolution.py
  yt/visualization/tests/test_particle_plot.py
Labels: bug

#4485 BUG: unlock annotate_timestamp callback for polar and spherical geometries
  yt/visualization/plot_modifications.py
  yt/visualization/tests/test_callbacks.py
Labels: bug, viz: 2D

#4464 Move netcdf4 forced import from netcdf4_imports to h5py_imports
  yt/utilities/on_demand_imports.py
Labels: enhancement

#4486 Backport PR #4485 on branch yt-4.2.x (BUG: unlock annotate_timestamp callback for polar and spherical geometries)
  yt/visualization/plot_modifications.py
  yt/visualization/tests/test_callbacks.py
Labels: bug, viz: 2D

#4487 Backport PR #4475 on branch yt-4.2.x (ENH: avoid implicitly dropping default parameters in plot annotation methods)
  yt/visualization/_mpl_imports.py
  yt/visualization/plot_modifications.py
Labels: bug, enhancement, viz: 2D, api-consistency, UX

#4490 BUG: fix confusing formatting in log message when allocating <10k particles
  yt/geometry/particle_geometry_handler.py
Labels: bug, UX

#4491 BUG: fix a bug where ProfilePlot and PhasePlot would be improperly validated at initialization
  yt/visualization/profile_plotter.py
Labels: bug, viz: 2D

#4492 BUG: fix a bug where calling plot.render() would have no effect depending on internal state
  yt/visualization/plot_container.py
Labels: bug, viz: 2D, api-consistency

#4455 ENH: add support for passing field keys for colors and linewidth in streamline plot annotations
  doc/source/visualizing/callbacks.rst
  yt/visualization/plot_modifications.py
  yt/visualization/tests/test_callbacks.py
Labels: enhancement, viz: 2D, api-consistency, deprecation

#4493 Backport PR #4490 on branch yt-4.2.x (BUG: fix confusing formatting in log message when allocating <10k particles)
  yt/geometry/particle_geometry_handler.py
Labels: bug, UX

#4494 Backport PR #4491 on branch yt-4.2.x (BUG: fix a bug where ProfilePlot and PhasePlot would be improperly validated at initialization)
  yt/visualization/profile_plotter.py
Labels: bug, viz: 2D

#4495 Backport PR #4492 on branch yt-4.2.x (BUG: fix a bug where calling plot.render() would have no effect depending on internal state)
  yt/visualization/plot_container.py
Labels: bug, viz: 2D, api-consistency

#4498 BUG: fix internal divide-by-zero warnings
  conftest.py
  yt/data_objects/profiles.py
  yt/data_objects/static_output.py
Labels: bug, enhancement, tests: running tests

#4504 Backport PR #4498 on branch yt-4.2.x (BUG: fix internal divide-by-zero warnings)
  conftest.py
  yt/data_objects/profiles.py
  yt/data_objects/static_output.py
Labels: bug, enhancement, tests: running tests

#4505 BUG: fix an issue where NormalPlot.sanitize_normal_vector would raise an error when receiving a numpy integer
  yt/visualization/plot_window.py
Labels: bug

#4508 nest the pytest import in yt.testing
  yt/testing.py
Labels: enhancement, pytest

#4503 BUG: fix noisy warnings when setting custom norm for fields with set_log=False
  yt/visualization/_handlers.py
  yt/visualization/plot_window.py
Labels: bug, viz: 2D, UX

#4506 Backport PR #4505 on branch yt-4.2.x (BUG: fix an issue where NormalPlot.sanitize_normal_vector would raise an error when receiving a numpy integer)
  yt/visualization/plot_window.py
Labels: bug

#4510 Backport PR #4503 on branch yt-4.2.x (BUG: fix noisy warnings when setting custom norm for fields with set_log=False)
  yt/visualization/_handlers.py
  yt/visualization/plot_window.py
Labels: bug, viz: 2D, UX

#4513 BUG: Fix cm1 chunk reader
  yt/frontends/nc4_cm1/io.py
Labels: bug, code frontends

#4514 Backport PR #4513 on branch yt-4.2.x (BUG: Fix cm1 chunk reader)
  yt/frontends/nc4_cm1/io.py
Labels: bug, code frontends

#4511 REL: bump version to 4.2.1
  doc/source/conf.py
  pyproject.toml
  yt/_version.py
Labels: infrastructure

#4501 ENH: cleanup empty cache directory after a successful call to load_sample
  yt/loaders.py
  yt/sample_data/api.py
  yt/tests/test_load_sample.py
Labels: enhancement

#4516 TST: filter numpy 1.25 deprecation warnings triggered by other deps
  conftest.py
Labels: bug, blocker, tests: running tests

#4521 DEP: drop support for matplotlib<3.5
  conftest.py
  pyproject.toml
  tests/windows_conda_requirements.txt
  yt/funcs.py
  yt/visualization/_commons.py
  yt/visualization/_handlers.py
  yt/visualization/base_plot_types.py
  yt/visualization/color_maps.py
  yt/visualization/profile_plotter.py
  yt/visualization/tests/test_image_comp_2D_plots.py
  yt/visualization/tests/test_splat.py
  yt/visualization/volume_rendering/image_handling.py
  yt/visualization/volume_rendering/transfer_functions.py
Labels: dead code, dependencies

#4519 DEPR: use builtin DeprecationWarnings
  yt/_maintenance/deprecation.py
  yt/tests/test_load_errors.py
  yt/visualization/tests/test_set_zlim.py
Labels: enhancement, deprecation, UX

#4414 gadget hdf: reduce size 1 header arrays to scalar
  nose_ignores.txt
  tests/tests.yaml
  yt/frontends/gadget/data_structures.py
  yt/frontends/gadget/tests/test_gadget_pytest.py
Labels: enhancement, code frontends

#4527 Add QuadrilinearFieldInterpolator
  yt/fields/derived_field.py
  yt/utilities/lib/interpolators.pyx
  yt/utilities/linear_interpolators.py
  yt/utilities/tests/test_interpolators.py
Labels: enhancement

#4531 Backport PR #4516 on branch yt-4.2.x (TST: filter numpy 1.25 deprecation warnings triggered by other deps)
  conftest.py
Labels: bug, blocker, tests: running tests

#4533 BUG: fix a regression preventing loading of fits datasets
  yt/frontends/fits/data_structures.py
Labels: bug, code frontends

#4509 improve docs for FieldValidator objects
  yt/fields/derived_field.py
Labels: docs, refactor

#4523 BLD: stop building wheels for Windows 32
  .github/workflows/wheels.yaml
Labels: infrastructure

#4546 Backport PR #4544 on branch yt-4.2.x (BUG: Fix docstring for load octree)
  yt/loaders.py
Labels: bug, docs

#4543 TST: simplify install script on windows
  tests/ci_install.sh
Labels: tests: running tests, refactor

#4550 Backport PR #4549 on branch yt-4.2.x (BUG: fix marker plot annotation)
  yt/visualization/plot_modifications.py
Labels: bug, viz: 2D

#4551 RFC: avoid double-copies of cmyt colormaps
  yt/visualization/color_maps.py
Labels: refactor

#4536 BUG: fix a regression preventing loading of pyne/moab datasets
  yt/frontends/moab/data_structures.py
Labels: bug, code frontends

#4555 Backport PR #4536 on branch yt-4.2.x (BUG: fix a regression preventing loading of pyne/moab datasets)
  yt/frontends/moab/data_structures.py
Labels: bug, code frontends
