Repository yt-project/yt, pull requests merged in 2023-04, with the labels that each got.

#4397 ENH: allow hint keyword for yt.load to select superclasses
  yt/loaders.py
  yt/tests/test_load_errors.py
  yt/utilities/hierarchy_inspection.py
Labels: enhancement

#4387 ENH: Add millimeter to smallest units
  yt/data_objects/static_output.py
  yt/visualization/tests/test_fits_image.py
Labels: bug, viz: 2D

#4404 BUG: make sure find_lowest_subclasses doesn't add extra classes
  yt/utilities/hierarchy_inspection.py
  yt/utilities/tests/test_hierarchy_inspection.py
Labels: bug

#4409 DOC: fix docs builds
  doc/source/analyzing/filtering.rst
  doc/source/developing/building_the_docs.rst
  pyproject.toml
  yt/data_objects/static_output.py
Labels: bug, docs, dependencies

#4411 RFC: rewrite find_lowest_subclasses to better match its intent
  yt/utilities/hierarchy_inspection.py
  yt/utilities/tests/test_hierarchy_inspection.py
Labels: refactor

#4407 a few doc fixes from Sphinx `make linkcheck`
  CONTRIBUTING.rst
  doc/source/developing/extensions.rst
  doc/source/examining/loading_data.rst
  doc/source/visualizing/colormaps/index.rst
  doc/source/visualizing/geographic_projections_and_transforms.rst
  doc/source/visualizing/unstructured_mesh_rendering.rst
Labels: bug, docs

#4377 DOC: fix typos
  yt/_maintenance/backports.py
  yt/_maintenance/deprecation.py
  yt/data_objects/static_output.py
  yt/data_objects/tests/test_registration.py
  yt/fields/local_fields.py
  yt/frontends/artio/artio_headers/LICENSE
  yt/frontends/cf_radial/data_structures.py
  yt/frontends/chimera/data_structures.py
  yt/frontends/enzo_e/data_structures.py
  yt/frontends/ramses/data_structures.py
  yt/frontends/stream/data_structures.py
  yt/geometry/coordinates/spherical_coordinates.py
  yt/geometry/coordinates/tests/test_sanitize_center.py
  yt/loaders.py
  yt/units/_numpy_wrapper_functions.py
  yt/utilities/logger.py
  yt/utilities/on_demand_imports.py
  yt/utilities/tests/test_config.py
  yt/utilities/tests/test_on_demand_imports.py
  yt/visualization/_handlers.py
  yt/visualization/base_plot_types.py
  yt/visualization/color_maps.py
  yt/visualization/fixed_resolution.py
  yt/visualization/plot_window.py
  yt/visualization/tests/test_plotwindow.py
  yt/visualization/tests/test_save.py
Labels: docs

#4422 DEPR: avoid deprecated implicit casting of single element arrays to scalar types
  yt/frontends/ramses/tests/test_hilbert.py
  yt/loaders.py
  yt/visualization/volume_rendering/transfer_functions.py
Labels: bug

#4419 Small Arepo/Gadget enhancements
  tests/tests.yaml
  yt/frontends/arepo/data_structures.py
  yt/frontends/arepo/fields.py
  yt/frontends/sph/fields.py
Labels: bug, enhancement, code frontends

#4423 some spelling fixes
  doc/source/analyzing/fields.rst
  doc/source/developing/creating_frontend.rst
  doc/source/developing/testing.rst
  doc/source/examining/loading_data.rst
  doc/source/installing.rst
  doc/source/visualizing/geographic_projections_and_transforms.rst
  doc/source/yt4differences.rst
Labels: docs
