Repository yt-project/yt, pull requests merged in 2023-12, with the labels that each got.

#4732 ENH: allow cell_widths and nproc > 1 for load_uniform_grid
  doc/source/examining/loading_data.rst
  yt/frontends/athena/data_structures.py
  yt/frontends/fits/data_structures.py
  yt/frontends/stream/misc.py
  yt/frontends/stream/tests/test_stream_stretched.py
  yt/loaders.py
  yt/utilities/decompose.py
  yt/utilities/tests/test_decompose.py
Labels: enhancement, index: grid

#4753 UX: add info about supported simulation types in YTSimulationNotIdentified
  yt/utilities/exceptions.py
Labels: enhancement, UX

#4756 Backport PR #4753 on branch yt-4.3.x (UX: add info about supported simulation types in YTSimulationNotIdentified)
  yt/utilities/exceptions.py
Labels: enhancement, UX

#4734 Read AMR domains lazily
  yt/data_objects/index_subobjects/octree_subset.py
  yt/frontends/art/data_structures.py
  yt/frontends/artio/data_structures.py
  yt/frontends/ramses/data_structures.py
  yt/frontends/ramses/field_handlers.py
  yt/frontends/ramses/hilbert.py
  yt/frontends/ramses/io.py
  yt/frontends/ramses/particle_handlers.py
  yt/frontends/ramses/tests/test_hilbert.py
  yt/frontends/ramses/tests/test_outputs.py
  yt/frontends/stream/data_structures.py
  yt/geometry/geometry_handler.py
  yt/geometry/selection_routines.pyx
Labels: enhancement, code frontends

#4739 Support for cosmic ray fields in GAMER
  yt/frontends/gamer/cfields.pyx
  yt/frontends/gamer/data_structures.py
  yt/frontends/gamer/fields.py
  yt/frontends/gamer/tests/test_outputs.py
Labels: new feature

#4759 TST: update xarray integration test to use non-deprecated API
  yt/data_objects/tests/test_covering_grid.py
Labels: bug, tests: running tests

#4760 Backport PR #4759 on branch yt-4.3.x (TST: update xarray integration test to use non-deprecated API)
  yt/data_objects/tests/test_covering_grid.py
Labels: bug, tests: running tests

#4764 BUGFIX: Enzo testing framework - ignore units for ShockTube tests
  yt/frontends/enzo/answer_testing_support.py
Labels: bug

#4767 Backport PR #4764 on branch yt-4.3.x (BUGFIX: Enzo testing framework - ignore units for ShockTube tests)
  yt/frontends/enzo/answer_testing_support.py
Labels: bug

#4768 Switch to field tuples for default fields in particle_trajectories
  nose_ignores.txt
  tests/tests.yaml
  yt/data_objects/particle_trajectories.py
  yt/data_objects/tests/test_particle_trajectories.py
  yt/data_objects/tests/test_particle_trajectories_pytest.py
Labels: bug, index: particle

#4769 Backport PR #4768 on branch yt-4.3.x (Switch to field tuples for default fields in particle_trajectories)
  nose_ignores.txt
  tests/tests.yaml
  yt/data_objects/particle_trajectories.py
  yt/data_objects/tests/test_particle_trajectories.py
  yt/data_objects/tests/test_particle_trajectories_pytest.py
Labels: bug, index: particle
