Repository yt-project/yt, pull requests merged in 2023-01, with the labels that each got.

#4281 BUG: fix a regression in yt.load where '/Users/robcleme' and '~' path weren't expanded
  yt/loaders.py
Labels: bug

#4290 CI: silence `set-output` warning
  .github/workflows/bleeding-edge.yaml
  .github/workflows/build-test.yaml
  .github/workflows/type-checking.yaml
  .github/workflows/wheels.yaml
Labels: infrastructure

#4285 ENH: automatically load external frontends in load()
  doc/source/developing/extensions.rst
  nose_unit.cfg
  tests/tests.yaml
  yt/frontends/sdf/data_structures.py
  yt/loaders.py
  yt/tests/test_external_frontends.py
Labels: enhancement

#4297 BUG: fix domain edges padding in reduced dimensions (FLASH)
  yt/frontends/flash/data_structures.py
Labels: bug, code frontends

#4292 ENH: migrate from pkg_resources to importlib.resources on Python 3.9+
  setupext.py
  yt/funcs.py
  yt/sample_data/api.py
  yt/utilities/command_line.py
Labels: enhancement

#4298 REL: Manual backports for 4.1.4
  .github/workflows/bleeding-edge.yaml
  .github/workflows/build-test.yaml
  .github/workflows/type-checking.yaml
  .github/workflows/wheels.yaml
  doc/source/cookbook/multiplot_2x2.py
  doc/source/cookbook/multiplot_2x2_coordaxes_slice.py
  doc/source/cookbook/multiplot_2x2_time_series.py
  doc/source/cookbook/multiplot_phaseplot.py
  yt/frontends/flash/data_structures.py
  yt/frontends/sdf/data_structures.py
  yt/loaders.py
  yt/visualization/base_plot_types.py
  yt/visualization/tests/test_plotwindow.py
Labels: bug

#4308 REL: Bump version numbers to 4.1.4
  doc/source/conf.py
  setup.cfg
  yt/_version.py
Labels: infrastructure

#4309 DOC: update a comment in SkeletonDataset to follow changes in Dataset.geometry type
  yt/frontends/_skeleton/data_structures.py
Labels: bug

#4307 ENH: Allow to store multiple bitmap indices in the ewah-sidecar
  tests/tests.yaml
  yt/frontends/arepo/tests/test_outputs.py
  yt/frontends/gadget/tests/test_outputs.py
  yt/geometry/particle_geometry_handler.py
  yt/geometry/particle_oct_container.pyx
  yt/geometry/tests/test_particle_octree.py
Labels: enhancement, index: particle

#4310 TST: bump CI from Python 3.10 to 3.11
  .github/workflows/build-test.yaml
Labels: infrastructure

#4311 TST: a couple improvements for ci_install.sh
  tests/ci_install.sh
Labels: enhancement, infrastructure, dead code

#4314 fix docs typo in load_hdf5_file description
  doc/source/examining/loading_data.rst
Labels: docs

#4312 Drop CodeTour GHA
  .github/workflows/codetour-check.yaml
Labels: infrastructure

#4319 MNT: drop useless workflow
  .github/workflows/rules-checks.yaml
Labels: dead code
