Repository yt-project/yt, pull requests merged in 2023-10, with the labels that each got.

#4624 TST: stop using conda on Windows CI
  .github/workflows/build-test.yaml
Labels: enhancement, tests: running tests

#3806 DOC: update "how to release" docs
  MANIFEST.in
  doc/source/developing/deprecating_features.rst
  doc/source/developing/releasing.rst
  scripts/pr_backport.py
Labels: docs, infrastructure

#4688 BUG: Don't access `data_source[field]` to get units
  yt/visualization/plot_container.py
Labels: bug, performance

#4693 BUG: fix load_sample with no arguments
  yt/loaders.py
  yt/tests/test_load_sample.py
Labels: bug

#4684 DOC: update support table for yt 4.3
  doc/source/installing.rst
Labels: enhancement, docs

#4694 REL: prep release 4.3.0
  doc/source/conf.py
  pyproject.toml
  yt/_version.py
Labels: infrastructure, dependencies

#4703 BUG: fix broken urllib imports
  yt/funcs.py
  yt/utilities/answer_testing/framework.py
  yt/utilities/command_line.py
Labels: bug

#4695 MNT: bump dev version (4.3->4.4)
  doc/source/conf.py
  pyproject.toml
  yt/_version.py
Labels: infrastructure

#4699 BUG: make annotate_sphere and annotate_arrow safe when run after plot invalidation
  yt/visualization/plot_modifications.py
  yt/visualization/tests/test_callbacks.py
Labels: bug

#4705 Backport PR #4699 on branch yt-4.3.x (BUG: make annotate_sphere and annotate_arrow safe when run after plot invalidation)
  yt/visualization/plot_modifications.py
  yt/visualization/tests/test_callbacks.py
Labels: bug, viz: 2D

#4708 [BUGFIX] The f90nml package is *optional* to load RAMSES
  yt/frontends/ramses/data_structures.py
Labels: bug, code frontends

#4709 Backport PR #4708 on branch yt-4.3.x ([BUGFIX] The f90nml package is *optional* to load RAMSES)
  yt/frontends/ramses/data_structures.py
Labels: bug, code frontends

#4686 minor bugfix in cholla frontend
  yt/frontends/cholla/data_structures.py
Labels: bug, code frontends
