Repository yt-project/yt, pull requests merged in 2023-05, with the labels that each got.

#4426 BUG: More robust detection and checking of EWAH files
  nose_ignores.txt
  tests/tests.yaml
  yt/data_objects/static_output.py
  yt/frontends/flash/data_structures.py
  yt/frontends/halo_catalog/data_structures.py
  yt/frontends/ytdata/data_structures.py
  yt/geometry/particle_geometry_handler.py
  yt/geometry/particle_oct_container.pyx
  yt/geometry/tests/test_ewah_write_load.py
  yt/geometry/tests/test_particle_octree.py
Labels: bug

#4429 BUG: fix confusing error message when yt fails to locate data
  yt/sample_data/api.py
Labels: bug, UX

#4130 RAMSES: Read rt file descriptor
  yt/frontends/ramses/field_handlers.py
  yt/frontends/ramses/fields.py
  yt/frontends/ramses/io.py
Labels: enhancement, code frontends

#4435 RFC: simplify base CoordinateHandler implementation (cached properties)
  yt/geometry/coordinates/coordinate_handler.py
  yt/utilities/minimal_representation.py
Labels: refactor

#4438 [BUG] Raise exception when a file does not exist
  nose_ignores.txt
  tests/tests.yaml
  yt/utilities/cython_fortran_utils.pyx
  yt/utilities/tests/test_cython_fortran_utils.py
Labels: bug

#4431 [BUG] Allow smoothing of derived SPH fields onto covering grids
  yt/data_objects/construction_data_containers.py
  yt/data_objects/tests/test_sph_data_objects.py
  yt/fields/field_info_container.py
Labels: bug

#4442 Bump answers for failing tests due to SymPy 1.12
  tests/tests.yaml
Labels: bug

#4443 BUG: fix a bug in Dataset.print_stats() where length units would be printed twice
  yt/frontends/ramses/data_structures.py
  yt/geometry/grid_geometry_handler.py
Labels: bug

#2711 BLD: Split EWAH bool array code
  .gitignore
  pyproject.toml
  setup.py
  setupext.py
  yt/geometry/particle_geometry_handler.py
  yt/geometry/particle_oct_container.pyx
  yt/utilities/lib/ewah_bool_array.pxd
  yt/utilities/lib/ewah_bool_wrap.pxd
  yt/utilities/lib/ewah_bool_wrap.pyx
  yt/utilities/lib/ewahboolarray/LICENSE
  yt/utilities/lib/ewahboolarray/README
  yt/utilities/lib/ewahboolarray/boolarray.h
  yt/utilities/lib/ewahboolarray/ewah-inl.h
  yt/utilities/lib/ewahboolarray/ewah.h
  yt/utilities/lib/ewahboolarray/ewahutil.h
  yt/utilities/lib/ewahboolarray/runninglengthword.h
Labels: infrastructure, refactor

#4445 TST: add ewah-bool-utils to build time dependencies in wheels and tests workflows
  .github/workflows/bleeding-edge.yaml
  .github/workflows/wheels.yaml
Labels: bug, tests: running tests

#4446 Whitelist the SPH star_formation_rate field
  yt/fields/particle_fields.py
Labels: enhancement

#4439 DEPR: deprecate unnecessary functions in the yt.testing namespace, update docs
  doc/source/analyzing/filtering.rst
  doc/source/reference/api/api.rst
  yt/data_objects/tests/test_chunking.py
  yt/data_objects/tests/test_sph_data_objects.py
  yt/frontends/cholla/tests/test_outputs.py
  yt/frontends/chombo/tests/test_outputs.py
  yt/frontends/enzo/tests/test_outputs.py
  yt/frontends/enzo_e/tests/test_outputs.py
  yt/frontends/exodus_ii/tests/test_outputs.py
  yt/frontends/fits/tests/test_outputs.py
  yt/frontends/flash/tests/test_outputs.py
  yt/frontends/gadget_fof/tests/test_outputs.py
  yt/frontends/gamer/tests/test_outputs.py
  yt/frontends/gdf/tests/test_outputs_nose.py
  yt/frontends/halo_catalog/tests/test_outputs.py
  yt/frontends/moab/tests/test_c5.py
  yt/frontends/nc4_cm1/tests/test_outputs.py
  yt/frontends/open_pmd/tests/test_outputs.py
  yt/frontends/owls_subfind/tests/test_outputs.py
  yt/frontends/ramses/tests/test_outputs.py
  yt/frontends/rockstar/tests/test_outputs.py
  yt/frontends/swift/tests/test_outputs.py
  yt/frontends/ytdata/tests/test_unit.py
  yt/geometry/coordinates/tests/test_spherical_coordinates.py
  yt/geometry/tests/test_particle_octree.py
  yt/testing.py
  yt/tests/test_funcs.py
  yt/utilities/answer_testing/framework.py
  yt/utilities/answer_testing/level_sets_tests.py
  yt/utilities/lib/cykdtree/tests/test_utils.py
  yt/utilities/lib/tests/test_alt_ray_tracers.py
  yt/utilities/tests/test_cosmology.py
  yt/visualization/tests/test_color_maps.py
  yt/visualization/tests/test_offaxisprojection.py
  yt/visualization/tests/test_plotwindow.py
Labels: docs, refactor, deprecation

#4450 STY: hotfix linting issue
  yt/visualization/tests/test_offaxisprojection.py
Labels: bug, blocker, code style

#4134 ENH: Enable exporting GAMER and FLASH datasets to octrees
  yt/frontends/stream/data_structures.py
  yt/geometry/oct_container.pyx
  yt/loaders.py
Labels: enhancement, code frontends

#4440 Off-axis (non-SPH) particle projections
  doc/source/visualizing/FITSImageData.ipynb
  doc/source/visualizing/plots.rst
  tests/tests.yaml
  yt/__init__.py
  yt/utilities/lib/pixelization_routines.pyx
  yt/visualization/api.py
  yt/visualization/fits_image.py
  yt/visualization/fixed_resolution.py
  yt/visualization/particle_plots.py
  yt/visualization/plot_window.py
  yt/visualization/tests/test_fits_image.py
  yt/visualization/tests/test_particle_plot.py
Labels: enhancement, viz: 2D, new feature, deprecation

#4452 REL: bump version to 4.2.0
  doc/source/conf.py
  pyproject.toml
  yt/_version.py
Labels: infrastructure

#4453 MNT: bump dev version
  doc/source/conf.py
  pyproject.toml
  yt/_version.py
Labels: infrastructure
