Repository yt-project/yt, pull requests merged in 2024-06, with the labels that each got.

#4920 BUG: fix deprecated implicit casting of arrays with ndim>0 to int scalar
  yt/frontends/amrex/data_structures.py
  yt/frontends/athena/data_structures.py
  yt/frontends/chombo/data_structures.py
  yt/frontends/gdf/data_structures.py
  yt/frontends/stream/data_structures.py
Labels: bug

#4908 ENH: add support for molecular fields (AMRex)
  nose_ignores.txt
  tests/tests.yaml
  yt/frontends/amrex/fields.py
  yt/frontends/amrex/tests/test_field_parsing.py
Labels: enhancement, code frontends

#4913 BLD: run pytest on wheels and sdist
  .github/workflows/wheels.yaml
  pyproject.toml
Labels: tests: running tests, infrastructure, build

#4884 BUG: Fix tipsy file handler opening
  yt/frontends/tipsy/io.py
Labels: bug, code frontends

#4923 DOC: fix typo in the debugging signal names
  doc/source/developing/debugdrive.rst
Labels: docs

#4925 DOC: replace boxlib with amrex references in the docs
  doc/source/developing/creating_frontend.rst
  doc/source/examining/loading_data.rst
  doc/source/reference/api/api.rst
  pyproject.toml
Labels: docs

#4929 BUG: ensure type safety in a call to np.logspace
  yt/frontends/art/io.py
Labels: bug, code frontends

#4930 BLD: require numpy 2.0.0 (stable) at build time
  pyproject.toml
  tests/tests.yaml
  yt/_maintenance/numpy2_compat.py
  yt/fields/vector_operations.py
Labels: bug, tests: running tests, build

#4794 TYP: upgrade mypy and type-check extras
  pyproject.toml
  yt/frontends/rockstar/definitions.py
Labels: infrastructure, dependencies
