Repository yt-project/yt, pull requests merged in 2024-01, with the labels that each got.

#4776 DOC: fix a broken docs example
  doc/source/cookbook/simple_slice_matplotlib_example.py
Labels: bug, docs

#4777 Backport PR #4776 on branch yt-4.3.x (DOC: fix a broken docs example)
  doc/source/cookbook/simple_slice_matplotlib_example.py
Labels: bug, docs

#4778 explicitly set minimum Python to 3.9.2
  .github/workflows/build-test.yaml
  pyproject.toml
Labels: bug, infrastructure, dependencies

#4758 ENH: allow boxlib frontend to read 1D cylindrical datasets
  yt/frontends/boxlib/data_structures.py
  yt/frontends/boxlib/tests/test_outputs.py
  yt/sample_data_registry.json
Labels: bug, code frontends

#4780 Backport PR #4758 on branch yt-4.3.x (ENH: allow boxlib frontend to read 1D cylindrical datasets)
  yt/frontends/boxlib/data_structures.py
  yt/frontends/boxlib/tests/test_outputs.py
  yt/sample_data_registry.json
Labels: bug, code frontends

#4762 ENH: add check for finite values in extrema
  yt/data_objects/derived_quantities.py
  yt/data_objects/tests/test_derived_quantities.py
Labels: enhancement

#4784 TST: ignore deprecation warning from pandas (Pyarrow will become a required dependency)
  conftest.py
Labels: bug, tests: running tests

#4791 Backport PR #4784 on branch yt-4.3.x (TST: ignore deprecation warning from pandas (Pyarrow will become a required dependency))
  conftest.py
Labels: bug, tests: running tests

#4779 Backport PR #4778 on branch yt-4.3.x (explicitly set minimum Python to 3.9.2)
  .github/workflows/build-test.yaml
  pyproject.toml
Labels: bug, infrastructure, dependencies

#4793 Backport PR #4792 on branch yt-4.3.x (BUG: enforce Figure dpi in _show_mpl)
  yt/visualization/volume_rendering/scene.py
Labels: bug, viz: volume rendering
