Repository yt-project/yt, pull requests merged in 2024-12, with the labels that each got.

#5069 Backport PR #5068 on branch yt-4.4.x (Bump the actions group in /.github/workflows with 2 updates)
  .github/workflows/wheels.yaml
Labels: infrastructure, dependencies, github_actions

#5059 [BUG] Fix off-axis rendering when center is not [0.5, 0.5, 0.5], fix periodicity
  yt/visualization/plot_window.py
  yt/visualization/tests/test_offaxisprojection.py
  yt/visualization/volume_rendering/off_axis_projection.py
Labels: bug, viz: 2D, index: octree

#5070 STY: apply autofixes for RUF031
  yt/data_objects/tests/test_derived_quantities.py
  yt/data_objects/tests/test_particle_trajectories_pytest.py
  yt/data_objects/tests/test_rays.py
  yt/frontends/amrex/tests/test_outputs.py
  yt/frontends/parthenon/tests/test_outputs.py
  yt/frontends/stream/io.py
  yt/frontends/stream/tests/test_stream_stretched.py
  yt/geometry/coordinates/geographic_coordinates.py
  yt/geometry/coordinates/tests/test_sph_pixelization_pytestonly.py
  yt/visualization/tests/test_offaxisprojection_pytestonly.py
Labels: code style, refactor

#5077 [FIX] Correctly normalize off-axis projections for octree datasets
  yt/visualization/tests/test_offaxisprojection.py
  yt/visualization/volume_rendering/off_axis_projection.py
Labels: bug, viz: 2D

#5078 Backport PR #5077 on branch yt-4.4.x ([FIX] Correctly normalize off-axis projections for octree datasets)
  yt/visualization/tests/test_offaxisprojection.py
  yt/visualization/volume_rendering/off_axis_projection.py
Labels: bug, viz: 2D

#5079 Backport PR #5063 on branch yt-4.4.x ([BUG] Ensure positions are dimensionless in plot callbacks)
  yt/visualization/plot_modifications.py
  yt/visualization/tests/test_image_comp_2D_plots.py
Labels: bug, viz: 2D

#5084 use .render instead of ._setup_plots in docs
  doc/source/cookbook/custom_colorbar_tickmarks.ipynb
  doc/source/cookbook/geographic_xforms_and_projections.ipynb
Labels: docs

#5083 BUG: fix compatibility with matplotlib 3.10 for images that have both a custom background color and a non-transparent 'bad' color
  yt/visualization/base_plot_types.py
Labels: bug, viz: 2D
