Repository yt-project/yt, pull requests merged in 2024-11, with the labels that each got.

#5039 fix broken numfocus link
  README.md
Labels: docs

#5042 pin xradar<0.8.0 in tests
  pyproject.toml
Labels: bug, tests: running tests, dependencies

#4783 Ray object dl for SPH data: interpolate kernel table for (b/hsml)**2 instead of b/hsml
  yt/data_objects/selection_objects/ray.py
  yt/data_objects/tests/test_rays.py
Labels: bug, blocker

#5018 PERF: release the GIL in cylindrical pixelizer
  yt/utilities/lib/pixelization_routines.pyx
Labels: enhancement, viz: 2D, performance, coordinates: non-cartesian

#5048 switch xradar pin to arm-pyart pin in tests
  pyproject.toml
Labels: code frontends, infrastructure

#5049 Backport PR #5048 on branch yt-4.4.x (switch xradar pin to arm-pyart pin in tests)
  pyproject.toml
Labels: code frontends, infrastructure

#5043 cf_radial: fix deprecated dims access, add pytest tests with mock ds
  conftest.py
  nose_ignores.txt
  tests/tests.yaml
  yt/frontends/cf_radial/data_structures.py
  yt/frontends/cf_radial/tests/test_cf_radial_pytest.py
Labels: code frontends, infrastructure

#5050 Backport PR #5043 on branch yt-4.4.x (cf_radial: fix deprecated dims access, add pytest tests with mock ds)
  conftest.py
  nose_ignores.txt
  tests/tests.yaml
  yt/frontends/cf_radial/data_structures.py
  yt/frontends/cf_radial/tests/test_cf_radial_pytest.py
Labels: code frontends, infrastructure

#5045 REL: bump version number to 4.4.0
  doc/source/conf.py
  pyproject.toml
  yt/_version.py
Labels: infrastructure

#5052 BUG: fix load_uniform_grid with cell_widths and multiple fields
  yt/frontends/stream/tests/test_stream_stretched.py
  yt/loaders.py
Labels: bug, code frontends, frontend: stream

#5056 Backport PR #5052 on branch yt-4.4.x (BUG: fix load_uniform_grid with cell_widths and multiple fields)
  yt/frontends/stream/tests/test_stream_stretched.py
  yt/loaders.py
Labels: bug, code frontends, frontend: stream

#5054 BUG: fix error message when trying to load a Parthenon dataset without h5py installed
  yt/frontends/parthenon/data_structures.py
Labels: bug, code frontends, UX, frontend: parthenon

#5046 MNT: bump dev version number to 4.5.dev0
  doc/source/conf.py
  pyproject.toml
  yt/_version.py
Labels: infrastructure

#5058 Backport PR #5054 on branch yt-4.4.x (BUG: fix error message when trying to load a Parthenon dataset without h5py installed)
  yt/frontends/parthenon/data_structures.py
Labels: bug, code frontends, UX, frontend: parthenon

#5051 RFC: refactor geometry matching clauses with Python 3.10's pattern matching
  yt/data_objects/selection_objects/data_selection_objects.py
  yt/data_objects/static_output.py
  yt/fields/field_info_container.py
  yt/fields/magnetic_field.py
  yt/frontends/amrex/data_structures.py
  yt/frontends/athena_pp/data_structures.py
  yt/frontends/flash/data_structures.py
  yt/frontends/parthenon/data_structures.py
  yt/visualization/plot_modifications.py
  yt/visualization/plot_window.py
Labels: refactor
