Repository yt-project/yt, pull requests merged in 2024-05, with the labels that each got.

#4888 MNT: build macOS amr64 wheels without cross-compiling
  .github/workflows/wheels.yaml
Labels: enhancement, build

#4893 BUG: Fix geographic coords convert_to_cartesian with units
  yt/geometry/coordinates/geographic_coordinates.py
  yt/geometry/coordinates/tests/test_geographic_coordinates.py
Labels: bug, coordinates: geographic

#4894 BLD: only compile fixed_interpolator.cpp once
  setup.py
  setupext.py
  yt/utilities/lib/grid_traversal.pyx
  yt/utilities/lib/image_samplers.pyx
  yt/utilities/lib/marching_cubes.pyx
  yt/utilities/lib/partitioned_grid.pyx
Labels: bug, build

#4898 BLD: fix bleeding-edge build script
  .github/workflows/bleeding-edge.yaml
  setup.py
  setupext.py
  yt/funcs.py
Labels: bug, tests: running tests, build

#4901 some spelling fixes
  CONTRIBUTING.rst
  doc/cheatsheet.tex
  doc/source/analyzing/fields.rst
  doc/source/developing/testing.rst
  yt/frontends/halo_catalog/io.py
Labels: docs

#4877 Reduce rendered images without considering opacity
  yt/utilities/amr_kdtree/amr_kdtools.py
  yt/utilities/amr_kdtree/amr_kdtree.py
  yt/visualization/volume_rendering/render_source.py
Labels: bug, enhancement, viz: volume rendering

#4904 Move field resolution inside conditional.
  yt/data_objects/data_containers.py
Labels: bug

#4907 BUG: Make sure fields are read in the order they appear in the file
  yt/frontends/ramses/io_utils.pyx
  yt/frontends/ramses/tests/test_outputs.py
Labels: bug, code frontends

#4909 BLD: minimally test wheels and sdist
  .github/workflows/wheels.yaml
Labels: infrastructure, build

#4911 BLD: fix segfault with manylinux2014
  .github/workflows/wheels.yaml
Labels: infrastructure, build

#4891 BUG: avoid ResourceWarnings in the amrex frontend
  yt/frontends/amrex/data_structures.py
Labels: bug

#4912 TST: cleanup unnecessary warning filter
  conftest.py
Labels: tests: running tests, dead code

#4914 CLN: drop unused and duplicated parsing logic in AMRex frontend
  yt/frontends/amrex/fields.py
Labels: code frontends, dead code
