Repository yt-project/yt, pull requests merged in 2024-03, with the labels that each got.

#4809 MNT: move ruff configuration to non-deprecated namespaces
  .pre-commit-config.yaml
  pyproject.toml
Labels: infrastructure

#4853 TST: temporarily pin pytest<8.0
  pyproject.toml
Labels: bug, tests: running tests

#4855 Backport PR #4853 on branch yt-4.3.x (TST: temporarily pin pytest<8.0)
  pyproject.toml
Labels: bug, tests: running tests

#4835 CLN: remove untested and broken notebook command from CLI
  doc/cheatsheet.tex
  doc/source/quickstart/index.rst
  doc/source/reference/configuration.rst
  doc/source/visualizing/plots.rst
  yt/config.py
  yt/utilities/command_line.py
Labels: dead code

#4857 Backport PR #4835 on branch yt-4.3.x (CLN: remove untested and broken notebook command from CLI)
  doc/cheatsheet.tex
  doc/source/quickstart/index.rst
  doc/source/reference/configuration.rst
  doc/source/visualizing/plots.rst
  yt/config.py
  yt/utilities/command_line.py
Labels: dead code
