Repository yt-project/yt, pull requests merged in 2024-09, with the labels that each got.

#4941 DEP: make ipywidgets/IPython optional dependencies again
  pyproject.toml
  yt/_maintenance/ipython_compat.py
  yt/data_objects/static_output.py
  yt/fields/field_type_container.py
  yt/funcs.py
  yt/visualization/image_writer.py
  yt/visualization/plot_container.py
  yt/visualization/profile_plotter.py
  yt/visualization/volume_rendering/old_camera.py
  yt/visualization/volume_rendering/scene.py
Labels: enhancement, dependencies

#4980 adjust platform_dep.h for recent MSVS versions
  .github/workflows/wheels.yaml
  yt/utilities/lib/platform_dep.h
Labels: bug

#4983 DEP: move dev-only dependencies to requirements files
  .github/dependabot.yml
  .github/workflows/type-checking.yaml
  MANIFEST.in
  doc/source/developing/building_the_docs.rst
  doc/source/developing/testing.rst
  pyproject.toml
  requirements/docs.txt
  requirements/minimal_env.txt
  requirements/typecheck.txt
  tests/ci_install.sh
Labels: infrastructure, dependencies

#4974 RFC: enable `flake8-type-checking` ruleset
  pyproject.toml
  yt/data_objects/static_output.py
  yt/frontends/ramses/io.py
  yt/visualization/fixed_resolution.py
  yt/visualization/plot_window.py
  yt/visualization/profile_plotter.py
Labels: code style, refactor

#4978 MNT: add pep723 metadata to test helper script
  tests/unpin_requirements.py
Labels: infrastructure

#4973 WHL: enable cp313 wheels
  .github/workflows/wheels.yaml
  pyproject.toml
Labels: infrastructure, build

#4994 fix Machnumber field spelling in amrex frontend for Castro
  yt/frontends/amrex/fields.py
Labels: enhancement, code frontends

#4998 STY: autofix RUF031 (`incorrectly-parenthesized-tuple-in-subscript`)
  pyproject.toml
Labels: enhancement, code style

#5000 BUG: ensure YTSlice.coord has units
  yt/data_objects/selection_objects/slices.py
  yt/data_objects/tests/test_sph_data_objects.py
  yt/funcs.py
Labels: bug, viz: 2D

#4989 MNT: restrict dependabot pip updates to requirements/typecheck.txt
  .github/dependabot.yml
  requirements/typecheck.txt
Labels: infrastructure, dependencies

#5008 TYP: hotfix unsolvable type-checking requirements
  .github/workflows/type-checking.yaml
  pyproject.toml
  requirements/typecheck.txt
  yt/data_objects/construction_data_containers.py
Labels: bug, dependencies
