Repository yt-project/yt, pull requests merged in 2024-04, with the labels that each got.

#4852 TST: migrate module-level setup/teardown functions to pytest
  nose_ignores.txt
  pyproject.toml
  yt/data_objects/tests/test_compose.py
  yt/data_objects/tests/test_covering_grid.py
  yt/data_objects/tests/test_cutting_plane.py
  yt/data_objects/tests/test_data_collection.py
  yt/data_objects/tests/test_derived_quantities.py
  yt/data_objects/tests/test_ellipsoid.py
  yt/data_objects/tests/test_extract_regions.py
  yt/data_objects/tests/test_fluxes.py
  yt/data_objects/tests/test_image_array.py
  yt/data_objects/tests/test_numpy_ops.py
  yt/data_objects/tests/test_particle_trajectories.py
  yt/data_objects/tests/test_points.py
  yt/data_objects/tests/test_projection.py
  yt/data_objects/tests/test_slice.py
  yt/data_objects/tests/test_spheres.py
  yt/fields/tests/test_magnetic_fields.py
  yt/fields/tests/test_xray_fields.py
  yt/utilities/grid_data_format/tests/test_writer.py
  yt/utilities/lib/tests/test_alt_ray_tracers.py
  yt/utilities/lib/tests/test_sample.py
  yt/utilities/tests/test_decompose.py
  yt/utilities/tests/test_interpolators.py
  yt/utilities/tests/test_minimal_representation.py
  yt/utilities/tests/test_periodicity.py
  yt/utilities/tests/test_selectors.py
  yt/utilities/tests/test_set_log_level.py
  yt/visualization/tests/test_export_frb.py
  yt/visualization/tests/test_geo_projections.py
  yt/visualization/tests/test_line_plots.py
  yt/visualization/tests/test_mesh_slices.py
  yt/visualization/tests/test_particle_plot.py
  yt/visualization/tests/test_plotwindow.py
  yt/visualization/tests/test_splat.py
  yt/visualization/volume_rendering/tests/test_composite.py
  yt/visualization/volume_rendering/tests/test_lenses.py
  yt/visualization/volume_rendering/tests/test_points.py
  yt/visualization/volume_rendering/tests/test_save_render.py
  yt/visualization/volume_rendering/tests/test_scene.py
  yt/visualization/volume_rendering/tests/test_sigma_clip.py
  yt/visualization/volume_rendering/tests/test_simple_vr.py
  yt/visualization/volume_rendering/tests/test_varia.py
  yt/visualization/volume_rendering/tests/test_vr_cameras.py
  yt/visualization/volume_rendering/tests/test_zbuff.py
Labels: bug, tests: running tests, pytest

#4862 Backport PR #4852 on branch yt-4.3.x (TST: migrate module-level setup/teardown functions to pytest)
  nose_ignores.txt
  pyproject.toml
  yt/data_objects/tests/test_compose.py
  yt/data_objects/tests/test_covering_grid.py
  yt/data_objects/tests/test_cutting_plane.py
  yt/data_objects/tests/test_data_collection.py
  yt/data_objects/tests/test_derived_quantities.py
  yt/data_objects/tests/test_ellipsoid.py
  yt/data_objects/tests/test_extract_regions.py
  yt/data_objects/tests/test_fluxes.py
  yt/data_objects/tests/test_image_array.py
  yt/data_objects/tests/test_numpy_ops.py
  yt/data_objects/tests/test_particle_trajectories.py
  yt/data_objects/tests/test_points.py
  yt/data_objects/tests/test_projection.py
  yt/data_objects/tests/test_slice.py
  yt/data_objects/tests/test_spheres.py
  yt/fields/tests/test_magnetic_fields.py
  yt/fields/tests/test_xray_fields.py
  yt/utilities/grid_data_format/tests/test_writer.py
  yt/utilities/lib/tests/test_alt_ray_tracers.py
  yt/utilities/lib/tests/test_sample.py
  yt/utilities/tests/test_decompose.py
  yt/utilities/tests/test_interpolators.py
  yt/utilities/tests/test_minimal_representation.py
  yt/utilities/tests/test_periodicity.py
  yt/utilities/tests/test_selectors.py
  yt/utilities/tests/test_set_log_level.py
  yt/visualization/tests/test_export_frb.py
  yt/visualization/tests/test_geo_projections.py
  yt/visualization/tests/test_line_plots.py
  yt/visualization/tests/test_mesh_slices.py
  yt/visualization/tests/test_particle_plot.py
  yt/visualization/tests/test_plotwindow.py
  yt/visualization/tests/test_splat.py
  yt/visualization/volume_rendering/tests/test_composite.py
  yt/visualization/volume_rendering/tests/test_lenses.py
  yt/visualization/volume_rendering/tests/test_points.py
  yt/visualization/volume_rendering/tests/test_save_render.py
  yt/visualization/volume_rendering/tests/test_scene.py
  yt/visualization/volume_rendering/tests/test_sigma_clip.py
  yt/visualization/volume_rendering/tests/test_simple_vr.py
  yt/visualization/volume_rendering/tests/test_varia.py
  yt/visualization/volume_rendering/tests/test_vr_cameras.py
  yt/visualization/volume_rendering/tests/test_zbuff.py
Labels: bug, tests: running tests, pytest

#4864 RFC: Replace np.random.random use with np.random.default_rng
  yt/fields/field_detector.py
  yt/testing.py
  yt/utilities/initial_conditions.py
  yt/visualization/volume_rendering/zbuffer_array.py
Labels: code style, refactor

#4867 Backport PR #4854 on branch yt-4.3.x (TST: set (very tight) error tolerance margins in `test_sph_data_objects.py`)
  yt/data_objects/tests/test_sph_data_objects.py
Labels: bug, tests: running tests

#4839 Bug: fix geographic coordinate conversions
  nose_ignores.txt
  tests/tests.yaml
  yt/geometry/coordinates/geographic_coordinates.py
  yt/geometry/coordinates/tests/test_geographic_coordinates.py
Labels: bug, coordinates: geographic

#4869 Manual backport for #4839
  nose_ignores.txt
  tests/tests.yaml
  yt/geometry/coordinates/geographic_coordinates.py
  yt/geometry/coordinates/tests/test_geographic_coordinates.py
Labels: bug, coordinates: geographic

#4859 BLD: add support for numpy 2
  pyproject.toml
Labels: enhancement, build

#4870 Backport PR #4859: BLD: add support for numpy 2
  pyproject.toml
Labels: enhancement, dependencies, build

#4865 REL: bump version number to 4.3.1
  doc/source/conf.py
  pyproject.toml
  yt/_version.py
Labels: infrastructure

#4741 Use stamping approach to deposit off-axis cells
  yt/utilities/lib/image_utilities.pyx
  yt/utilities/lib/interpolators.pyx
  yt/visualization/volume_rendering/off_axis_projection.py
Labels: enhancement, proposal, performance, new feature, index: octree, index: grid

#4879 correct errors in capital letter
  yt/frontends/ramses/fields.py
  yt/frontends/ramses/io.py
Labels: bug, code frontends

#4872 BUG: Always use the coordinate system normal for computing angular momentum components for particles
  yt/fields/particle_fields.py
Labels: bug

#4882 BUG: Update Qt backend entries in BACKEND_SPECS
  yt/visualization/base_plot_types.py
Labels: bug, viz: 2D

#4875 BUG: create duplicate of MPI communicator, to avoid double comm.Free
  yt/utilities/parallel_tools/parallel_analysis_interface.py
Labels: bug, backport-stable

#4878 ENH: Make Hilbert intersection faster
  yt/frontends/ramses/hilbert.py
  yt/frontends/ramses/tests/test_hilbert.py
Labels: code frontends, refactor

#4525 ENH: Add a few bitarray functions and tests
  yt/utilities/lib/bitarray.pxd
  yt/utilities/lib/bitarray.pyx
  yt/utilities/lib/tests/test_bitarray.py
Labels: enhancement, performance, index: grid

#4885 ENH: tipsy use max_rows instead of skip_footer for ascii aux read
  yt/frontends/tipsy/io.py
Labels: enhancement, code frontends

#4868 STY: migrate formatting from black to ruff-format
  .git-blame-ignore-revs
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  tests/report_failed_answers.py
  yt/data_objects/construction_data_containers.py
  yt/data_objects/level_sets/clump_handling.py
  yt/data_objects/profiles.py
  yt/data_objects/tests/test_dataset_access.py
  yt/frontends/chimera/io.py
  yt/frontends/chombo/data_structures.py
  yt/frontends/enzo/data_structures.py
  yt/frontends/enzo/simulation_handling.py
  yt/frontends/gamer/data_structures.py
  yt/frontends/ramses/data_structures.py
  yt/frontends/ramses/io.py
  yt/frontends/ramses/tests/test_outputs.py
  yt/frontends/sdf/io.py
  yt/frontends/stream/io.py
  yt/funcs.py
  yt/geometry/coordinates/tests/test_geographic_coordinates.py
  yt/utilities/answer_testing/framework.py
  yt/visualization/volume_rendering/render_source.py
Labels: infrastructure, code style
