Repository yt-project/yt, pull requests merged in 2024-02, with the labels that each got.

#4797 correct domain_dimensions in non-fixed block size uniform grid FLASH output
  yt/frontends/flash/data_structures.py
Labels: bug, code frontends

#4810 Backport PR #4798 on branch yt-4.3.x (Bump the actions group in /.github/workflows with 1 update)
  .github/workflows/wheels.yaml
Labels: infrastructure, dependencies

#4800 Backport PR #4797 on branch yt-4.3.x (correct domain_dimensions in non-fixed block size uniform grid FLASH output)
  yt/frontends/flash/data_structures.py
Labels: bug, code frontends

#4802 Fix bug where race condition results in incorrect fields categorization when computing particle_trajectories
  yt/data_objects/particle_trajectories.py
Labels: bug, index: particle

#4812 Backport PR #4805 on branch yt-4.3.x (ENH: add support for Quokka datasets)
  yt/frontends/boxlib/data_structures.py
Labels: enhancement, code frontends

#4811 Backport PR #4802 on branch yt-4.3.x (Fix bug where race condition results in incorrect fields categorization when computing particle_trajectories)
  yt/data_objects/particle_trajectories.py
Labels: bug, index: particle

#4782 Updates for GAMER SR fields
  doc/source/examining/loading_data.rst
  tests/tests.yaml
  yt/frontends/gamer/cfields.pyx
  yt/frontends/gamer/data_structures.py
  yt/frontends/gamer/fields.py
  yt/sample_data_registry.json
Labels: bug, enhancement

#4801 Fix order of Athena++ cylindrical coords
  yt/frontends/athena_pp/data_structures.py
Labels: bug, code frontends, coordinates: non-cartesian

#4537 RFC: refactor ParticleProjectionPlot for consistency with ProjectionPlot
  yt/visualization/particle_plots.py
Labels: refactor

#4819 Catch Py312+ warning when using ratarmount
  conftest.py
Labels: bug, tests: running tests, pytest

#4821 Backport PR #4819 on branch yt-4.3.x (Catch Py312+ warning when using ratarmount)
  conftest.py
Labels: bug, tests: running tests, pytest

#4825 BUG: use the validated center for YTCuttingPlane set_field_parameter
  yt/data_objects/selection_objects/slices.py
Labels: bug

#4826 Backport PR #4815 on branch yt-4.3.x (BUG: Assign domain dims after updates in Athena)
  yt/frontends/athena/data_structures.py
Labels: bug, code frontends

#4827 Backport PR #4825 on branch yt-4.3.x (BUG: use the validated center for YTCuttingPlane set_field_parameter)
  yt/data_objects/selection_objects/slices.py
Labels: bug

#4820 Backport PR #4801 on branch yt-4.3.x (Fix order of Athena++ cylindrical coords)
  yt/frontends/athena_pp/data_structures.py
Labels: bug, code frontends, coordinates: non-cartesian

#4806 RFC: replace vendored version of numpy.trapz with supported API in numpy 2
  yt/_maintenance/numpy2_compat.py
Labels: bug, refactor

#4829 RFC: avoid usage of deprecated usage numpy.core (numpy 2 compat)
  yt/arraytypes.py
  yt/frontends/fits/data_structures.py
Labels: bug, refactor

#4832 Backport PR #4829 on branch yt-4.3.x (RFC: avoid usage of deprecated usage numpy.core (numpy 2 compat))
  yt/arraytypes.py
  yt/frontends/fits/data_structures.py
Labels: bug, refactor

#4830 BLD: Ditch `np.int_t`, removed in numpy 2's C API (use `np.int64_t` instead)
  yt/geometry/coordinates/cartesian_coordinates.py
  yt/geometry/grid_container.pyx
  yt/geometry/grid_visitors.pxd
  yt/utilities/lib/alt_ray_tracers.pyx
  yt/utilities/lib/interpolators.pyx
  yt/utilities/lib/mesh_triangulation.pyx
  yt/utilities/lib/pixelization_routines.pyx
  yt/utilities/linear_interpolators.py
Labels: bug, build

#4837 Backport PR #4830 on branch yt-4.3.x (BLD: Ditch `np.int_t`, removed in numpy 2's C API (use `np.int64_t` instead))
  yt/geometry/coordinates/cartesian_coordinates.py
  yt/geometry/grid_container.pyx
  yt/geometry/grid_visitors.pxd
  yt/utilities/lib/alt_ray_tracers.pyx
  yt/utilities/lib/interpolators.pyx
  yt/utilities/lib/mesh_triangulation.pyx
  yt/utilities/lib/pixelization_routines.pyx
  yt/utilities/linear_interpolators.py
Labels: bug, build

#4828 BUG: fix parameter parsing for Castro and MAESTRO
  yt/frontends/boxlib/data_structures.py
  yt/frontends/boxlib/tests/test_outputs.py
Labels: bug, code frontends

#4840 Backport PR #4828 on branch yt-4.3.x (BUG: fix parameter parsing for Castro and MAESTRO)
  yt/frontends/boxlib/data_structures.py
  yt/frontends/boxlib/tests/test_outputs.py
Labels: bug, code frontends
