Repository yt-project/yt, pull requests merged in 2025-10, with the labels that each got.

#5293 TST: avoid mpl API pending-deprecation (`Colormap.set_bad`)
  yt/visualization/tests/test_image_comp_2D_plots.py
Labels: tests: running tests, refactor

#5294 IPython.core.display.display has been removed
  yt/units/__init__.py
Labels: bug

#5287 BLD: avoid direct dependency on wheel library
  pyproject.toml
  setup.py
  setupext.py
Labels: refactor, build

#5297 Backport PR #5294 on branch yt-4.4.x (IPython.core.display.display has been removed)
  yt/units/__init__.py
Labels: bug
