Repository yt-project/yt, pull requests merged in 2025-07, with the labels that each got.

#5197 TST: filter out an indirect deprecation warning from Pillow via matplotlib
  conftest.py
Labels: bug, blocker, tests: running tests

#5169 [BUG] RAMSES: temperature units are incorrect
  yt/frontends/ramses/data_structures.py
Labels: bug, code frontends, frontend: ramses

#5210 Backport PR #5209 on branch yt-4.4.x (BUG: fix missing `refine_by` attribute in `SwiftDataset`)
  yt/frontends/swift/data_structures.py
Labels: bug, frontend: swift, workshop-2025

#5221 BUG: Fix partition_index_2d
  yt/utilities/parallel_tools/parallel_analysis_interface.py
Labels: bug, parallelism, workshop-2025

#5213 Represent comoving with a `c` prefix
  yt/data_objects/static_output.py
Labels: enhancement, refactor, workshop-2025

#5228 WHL: bump cibuildwheel to 3.1.1, start testing wheels on CPython 3.14
  .github/workflows/wheels.yaml
  pyproject.toml
Labels: enhancement, tests: running tests, build

#5234 Backport PR #5228 on branch yt-4.4.x (WHL: bump cibuildwheel to 3.1.1, start testing wheels on CPython 3.14)
  .github/workflows/wheels.yaml
  pyproject.toml
Labels: enhancement, tests: running tests, build

#5240 Backport PR #5233 on branch yt-4.4.x (MNT: adjust PyPI trove classifiers)
  MANIFEST.in
  pyproject.toml
Labels: docs, build

#5204 [BUGFIX] Fix #5203
  yt/data_objects/selection_objects/data_selection_objects.py
Labels: bug
