Repository yt-project/yt, pull requests merged in 2025-08, with the labels that each got.

#5131 ENH/DEP: use a more robust, external implementation of the Line Integral Convolution (LIC) algorithm
  .gitignore
  minimal_requirements.txt
  pyproject.toml
  yt/utilities/lib/api.py
  yt/utilities/lib/line_integral_convolution.pyx
  yt/visualization/plot_modifications.py
Labels: bug, viz: 2D, proposal, performance, dependencies

#5185 WHL: test musllinux wheels
  .github/workflows/wheels.yaml
  pyproject.toml
Labels: enhancement, tests: running tests

#5256 fix/update tfh tutorial
  doc/source/visualizing/TransferFunctionHelper_Tutorial.ipynb
Labels: bug, docs, viz: volume rendering

#5264 Backport PR #5246 on branch yt-4.4.x (CLN: cleanup obsolete workarounds in bleeding edge CI)
  .github/workflows/bleeding-edge.yaml
Labels: tests: running tests, dead code

#5261 Backport PR #5185 on branch yt-4.4.x (WHL: test musllinux wheels)
  .github/workflows/wheels.yaml
  pyproject.toml
Labels: enhancement, tests: running tests

#5262 Backport PR #5256 on branch yt-4.4.x (fix/update tfh tutorial)
  doc/source/visualizing/TransferFunctionHelper_Tutorial.ipynb
Labels: bug, docs, viz: volume rendering

#5265 [BUG] minor Fix dataset hashing for non-ASCII paths by encoding `parameter_filename` as UTF-8
  yt/data_objects/static_output.py
Labels: bug

#5267 Backport PR #5266 on branch yt-4.4.x (Fix formatting of **CONTRIBUTING.rst**)
  CONTRIBUTING.rst
Labels: bug, docs

#5211 Removing YTSphereTooSmall
  yt/data_objects/selection_objects/spheroids.py
  yt/utilities/exceptions.py
  yt/visualization/volume_rendering/tests/test_composite.py
  yt/visualization/volume_rendering/tests/test_points.py
  yt/visualization/volume_rendering/tests/test_zbuff.py
Labels: enhancement, discussion, workshop-2025

#5273 BUG: fix an incoming deprecation warning from numpy 2.4 (np.minimum and np.maximum's out argument must be passed as keyword)
  yt/fields/field_functions.py
  yt/frontends/tipsy/io.py
  yt/utilities/amr_kdtree/amr_kdtools.py
  yt/utilities/initial_conditions.py
  yt/visualization/volume_rendering/old_camera.py
Labels: bug

#5274 Backport PR #5273 on branch yt-4.4.x (BUG: fix an incoming deprecation warning from numpy 2.4 (np.minimum and np.maximum's out argument must be passed as keyword))
  yt/fields/field_functions.py
  yt/frontends/tipsy/io.py
  yt/utilities/amr_kdtree/amr_kdtools.py
  yt/utilities/initial_conditions.py
  yt/visualization/volume_rendering/old_camera.py
Labels: bug
