Repository yt-project/yt, pull requests merged in 2025-02, with the labels that each got.

#5112 BUG: fix NaNs in off-center FRB slices from ds.r
  yt/data_objects/region_expression.py
  yt/data_objects/tests/test_dataset_access.py
Labels: bug

#5113 Backport PR #5112 on branch yt-4.4.x (BUG: fix NaNs in off-center FRB slices from ds.r)
  yt/data_objects/region_expression.py
  yt/data_objects/tests/test_dataset_access.py
Labels: bug

#5025 BUG: fix ds.all_data() for spherical AMReX datasets
  yt/frontends/amrex/data_structures.py
  yt/frontends/amrex/tests/test_outputs.py
  yt/sample_data_registry.json
Labels: bug, code frontends, frontend: amrex

#5090 BUG: Properly reference weight field in profile code for particle-based datasets
  yt/data_objects/profiles.py
  yt/data_objects/tests/test_profiles.py
Labels: bug, viz: 2D

#5110 Backport PR #5108 to yt-4.4.x (Bump pypa/gh-action-pypi-publish to 1.12.4)
  .github/workflows/wheels.yaml
Labels: infrastructure, dependencies, github_actions

#5120 Backport PR #5081 on branch yt-4.4.x (BUG: calculate default depth for off axis projections)
  pyproject.toml
  yt/visualization/fixed_resolution.py
  yt/visualization/plot_window.py
  yt/visualization/tests/test_offaxisprojection_pytestonly.py
Labels: bug, viz: 2D

#5122 Backport PR #5025 to yt-4.4.x (BUG: fix ds.all_data() for spherical AMReX datasets)
  yt/frontends/amrex/data_structures.py
  yt/frontends/amrex/tests/test_outputs.py
  yt/sample_data_registry.json
Labels: bug, code frontends, frontend: amrex

#5124 Backport PR #5090 on branch yt-4.4.x (BUG: Properly reference weight field in profile code for particle-based datasets)
  yt/data_objects/profiles.py
  yt/data_objects/tests/test_profiles.py
Labels: bug, viz: 2D
