Repository yt-project/yt, pull requests merged in 2025-04, with the labels that each got.

#5137 update testing.integrate_kernel type hints
  yt/testing.py
Labels: bug

#5148 Backport PR #5137 on branch yt-4.4.x (update testing.integrate_kernel type hints)
  yt/testing.py
Labels: bug

#5147 Backport PR #5146 on branch yt-4.4.x (Bump pypa/cibuildwheel from 2.22.0 to 2.23.2 in /.github/workflows in the actions group)
  .github/workflows/wheels.yaml
Labels: infrastructure, dependencies, github_actions

#5088 BUG: Removing code that removes field type in set_title()
  yt/visualization/profile_plotter.py
  yt/visualization/tests/test_profile_plots.py
Labels: bug, viz: 2D

#5155 BUG: Better behavior when Cholla doesn't write "mu" attribute
  yt/frontends/cholla/data_structures.py
  yt/frontends/cholla/fields.py
Labels: bug, frontend: cholla
